Energinet-DataHub/greenforce-frontend

package.json

You can now run "yarn task" to get a list of tasks to run
Pick a task from the list to run it

Added a task picker

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-client-secret-view.component.ts

- prevent drawer from closing on button click (workaround)
- update translations
- https://github.com/Energinet-DataHub/team-titans/issues/326

fix(dh): prevent drawer from closing 

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/dh-b2b-access-tab.component.ts

- https://github.com/Energinet-DataHub/team-titans/issues/326

feat(dh): add icon to empty state

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/picker/datepicker/watt-datepicker.component.ts

- https://github.com/Energinet-DataHub/team-titans/issues/344

fix(watt): change default value of `startAt` Input

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/market-participant/actors/data-access-api/src/index.ts
libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-party-b2b-access.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-uploader.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-replace-certificate-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-client-secret-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-generate-client-secret.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/dh-b2b-access-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-audit-log.service.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts

- https://github.com/Energinet-DataHub/Internal-Repo/issues/778

fix(dh): refresh audit log after changes in B2B access 

---

libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-user-roles-by-eicfunction.ts

mock graphql

---

build/infrastructure/eo/configuration.yaml
libs/eo/certificates/domain/index.ts
libs/eo/certificates/feature-overview/eo-certificates-table.component.ts
libs/eo/claims/data-access-api/claims.service.ts
libs/eo/claims/feature-overview/claims-table.component.ts
libs/eo/claims/feature-overview/claims.component.ts

- Add `start` and `end` columns to the claims table.
- Sort the claims table so the newest claims are shown first as default. 
- Make sure the claims table is searchable with the new values. 
- Add certificate type for the certificates table.
- #0000

Add support for manual testing / verification of claims and consumption  

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts
libs/dh/shared/ui-validators/src/index.ts
libs/dh/shared/ui-validators/src/lib/dh-gln-or-eic.validator.spec.ts
libs/dh/shared/ui-validators/src/lib/dh-gln-or-eic.validator.ts

feat(dh): allow dash in eic validator

---

docs/dh/logging.md
libs/dh/auth/feature-msal/src/index.ts
libs/dh/auth/feature-msal/src/lib/dh-b2c-config.ts
libs/dh/core/shell/src/lib/dh-core-shell.providers.ts
libs/dh/core/shell/src/lib/dh-core-shell.routes.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipantUser.ts
libs/dh/shared/feature-authorization/src/lib/dh-signup-mitid.component.html
libs/dh/shared/feature-authorization/src/lib/dh-signup-mitid.component.ts

- update Logging docs
- revert changes to MSAL config 
- minor adjustments to MitID signup component
- fix broken MSAL initialization
- remove MsalModule and organize providers
- remove unused route
- add mock
- N/A

fix(dh): various adjustments

---

build/infrastructure/eo/configuration.yaml
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-audit-logs.component.ts
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-market-roles.component.ts
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-roles.component.ts
libs/dh/admin/feature-permissions/src/lib/permissionAuditLog.ts
libs/dh/admin/feature-permissions/src/lib/shared/dh-get-permissions-watch-query.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.ts
libs/dh/admin/feature-user-management/src/lib/userRoleAuditLog.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/admin-get-permission-details.ts
libs/dh/shared/data-access-mocks/src/lib/data/admin-get-permissions.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-actor-audit-logs.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-grid-area-overview.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-user-role-audit-logs.ts
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/shared/domain/src/index.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts
libs/dh/wholesale/domain/src/grid-areas.ts
libs/dh/wholesale/domain/src/settlement-report-process.ts
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.ts
tsconfig.base.json

- remove non-existing paths from `tsconfig.base.json`
- import GraphQL artifacts from `dh/shared/domain/graphql` path
- remove `graphql` export from `dh/shared/domain` path
- remove unused feature flags
- bump created date in feature flags
- N/A

refactor(dh): various adjustments

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

- https://github.com/Energinet-DataHub/team-titans/issues/359

Fix error text

---

libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

- https://github.com/Energinet-DataHub/team-titans/issues/346
- https://github.com/Energinet-DataHub/team-titans/issues/347

feat(dh): set button in loading state in request calculation

---

libs/dh/admin/feature-create-user-role/src/lib/dh-create-user-role-modal.component.ts
libs/dh/admin/feature-edit-permission-modal/src/lib/dh-edit-permission-modal.component.ts
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/admin/feature-invite-user-modal/src/lib/dh-assignable-user-roles/dh-assignable-user-roles.component.ts
libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.ts
libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-audit-logs.component.ts
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-market-roles.component.ts
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-roles.component.ts
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-audit-change-cell.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-master-data.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-audit-logs.component.ts
libs/dh/admin/feature-user-management/src/lib/shared/dh-role-status.component.ts
libs/dh/admin/feature-user-management/src/lib/shared/dh-user-status.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.ts

refactor(dh): remove `CommonModule`

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/styles/@energinet-datahub/watt/theme/material-overwrites/datepicker.scss

fix(watt): set date-in-range color in datepicker

---

libs/dh/admin/feature-edit-permission-modal/src/lib/dh-edit-permission-modal.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.ts

fix(dh): add missing `NgIf` imports

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts

fix(dh): add missing import

---

libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts
libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.html
libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts

fix(dh): remove row highlight when drawer closes

---

libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts

- fix logic for loading and resetting document content 
- https://github.com/Energinet-DataHub/team-titans/issues/339

fix(dh): adjustments to message archive

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts

fix(dh): show grid area only to grid access provider

---

libs/dh/admin/feature-user-roles/src/test-setup.ts
libs/dh/charges/feature-create-prices/src/test-setup.ts
libs/dh/charges/feature-prices/src/test-setup.ts
libs/dh/esett/feature-balance-responsible/src/test-setup.ts
libs/dh/esett/feature-metering-gridarea-imbalance/src/test-setup.ts
libs/dh/market-participant/actors/feature-actors/src/test-setup.ts
libs/dh/market-participant/actors/feature-market-roles/src/test-setup.ts
libs/dh/metering-point/feature-overview/src/test-setup.ts
libs/dh/metering-point/feature-search/src/test-setup.ts
libs/dh/shared/feature-authorization/src/test-setup.ts
libs/dh/wholesale/feature-calculations/src/test-setup.ts
libs/dh/wholesale/feature-request-calculation/src/test-setup.ts
libs/dh/wholesale/feature-settlement-reports/src/test-setup.ts

fix(dh): fix test setup

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-organization-step.component.ts

- https://github.com/Energinet-DataHub/team-titans/issues/364

fix(dh): align headline and button

---

apps/dh/app-dh/src/index.html
apps/dh/app-dh/src/styles.scss

Let it snow let it snow

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-actor-step.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts

- close modal only on success
- conditionally fetch data
- add mock
- https://github.com/Energinet-DataHub/team-titans/issues/371

fix(dh): close modal only on success

---

libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.html

readded at for actor edit 
- #0000

readded at for actor edit 

---

libs/dh/message-archive/data-access-api/src/lib/dh-message-archive-data-access-api.store.ts
libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.html
libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts

- persist selected sorting
- import standalone Transloco artifacts
- https://github.com/Energinet-DataHub/team-titans/issues/348

feat(dh): persist selected sorting in message archive

---

libs/dh/core/shell/src/lib/dh-core-shell.component.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/status-badge/dh-actor-status-badge.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/table/dh-actors-table.component.ts
libs/dh/market-participant/actors/feature-market-roles/src/lib/dh-market-roles-overview.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/dh-organizations-overview.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.ts
libs/dh/market-participant/grid-areas/overview/src/lib/dh-market-participant-gridarea-overview.component.ts

refactor(dh): replace TranslocoModule with standalone artifacts

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/text-field/+storybook/storybook-autocomplete.component.ts
libs/watt/src/lib/components/text-field/+storybook/watt-text-field.stories.ts
libs/watt/src/lib/components/text-field/watt-text-field.component.scss
libs/watt/src/lib/components/text-field/watt-text-field.component.ts

Add autocomplete functionality to WattTextField component

feat(watt): Add autocomplete functionality to WattTextField component

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-audit-logs-data-access-api.store.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
libs/dh/admin/feature-user-management/src/lib/shared/dh-user-status.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-actor-filter.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-status-filter.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-userrole-filter.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- refactor filters to use chips
- move filters inside card
- organize translations
- add empty message
- remove unnecessary styling
- simplify store selector
- fix tests
- https://github.com/Energinet-DataHub/team-titans/issues/363

refactor(dh): adjustments to admin page

---

libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.scss
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts

- adjustments to card title
- move paginator below table
- show error message before paginator
- set loading state on table
- add delay to mock
- https://github.com/Energinet-DataHub/team-titans/issues/363

refactor(dh): adjustments to user roles page

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.html
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.scss
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts
libs/dh/admin/feature-permissions/src/lib/shared/dh-get-permissions-watch-query.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/admin.ts

- update design of Permissions page
- search permissions locally
- add mock
- minor refactoring
- https://github.com/Energinet-DataHub/team-titans/issues/363

refactor(dh): adjustments to permissions page

---

apps/eo/e2e-eo/src/page-objects/shared.po.ts
build/infrastructure/eo/configuration.yaml
libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/shared/services/src/auth/auth.store.ts
libs/watt/src/lib/components/shell/shell.component.html
libs/watt/src/lib/components/shell/shell.component.scss

- Add user information to the sidebar
- Move `Log out` and `Help` up to the topbar
[#2091](https://github.com/Energinet-DataHub/energy-origin-issues/issues/2091)

feat(eo): add user information to the sidebar

---

libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.html
libs/watt/src/lib/components/modal/+storybook/watt-modal.stories.ts
libs/watt/src/lib/components/modal/watt-modal.component.ts

- https://github.com/Energinet-DataHub/team-titans/issues/395

Add disableEscAndBackdropClose property to watt-modal component

---

libs/dh/shared/util-application-insights/src/lib/dh-application-insights.initializer.ts
libs/dh/shared/util-application-insights/src/lib/dh-application-insights.service.ts

Optimize the bundle size by lazy loading the app insight library

Refactor Application Insights initialization

---

apps/dh/app-dh/src/main.ts

I dont think this is being used anymore. After testing i saw no difference with it or without it. 
So now its gone :-)
Sadly we could not get rid of msal/browser its being used else where.

Removed old login window logic

---

apps/dh/e2e-dh/src/e2e/b2c-healthchecks.cy.ts
libs/dh/shared/environments/src/lib/app-environment/dh-app-environment.ts
libs/dh/shared/feature-flags/src/lib/feature-flag.directive.spec.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.service.spec.ts

changed health checks to new environments

---

apps/dh/e2e-dh/src/e2e/b2c-healthchecks.cy.ts

fix(dh): use correct PreProd URL

---

libs/dh/wholesale/feature-calculations/src/lib/create/create.component.html
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts

- https://github.com/Energinet-DataHub/opengeh-wholesale/issues/1745
- https://github.com/Energinet-DataHub/opengeh-wholesale/issues/1746

fix(dh): reset input field on close

---

README.md
docs/dh/datahub-bookmarks.html

docs: update environments table and bookmarks

---

apps/dh/app-dh/project.json
apps/dh/app-dh/src/main.ts
apps/eo/app-eo/src/main.ts

- lazy-load animations to decrease main bundle
- decrease main bundle budget size to 1.9Mb
- lazy-load animations to decrease main bundle
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/2364

feat: lazy-load animations

---

apps/dh/e2e-dh/package.json
package.json

fix: update path in package.json

---

apps/dh/e2e-dh/package-lock.json

chore: update package-lock file

---

libs/eo/shared/data-access-mocks/src/lib/transfer.ts
libs/eo/transfers/src/lib/eo-transfers.service.ts

Fix formatting of the timestamps in the transfer agreements history. 
- #0000

fix(eo, transfers): Refactor transferAgreement date format

---

libs/watt/src/lib/components/textarea-field/watt-textarea-field.component.ts

fix(watt): add formControl input to textarea

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/imbalance-prices/data-access-graphql/imbalance-prices-overview.graphql
libs/dh/imbalance-prices/data-access-graphql/project.json
libs/dh/imbalance-prices/shell/src/lib/dh-imbalance-prices-shell.component.ts
libs/dh/imbalance-prices/shell/src/lib/dh-imbalance-prices.ts
libs/dh/imbalance-prices/shell/src/lib/status-badge/dh-status-badge.component.ts
libs/dh/imbalance-prices/shell/src/lib/table/dh-table.component.html
libs/dh/imbalance-prices/shell/src/lib/table/dh-table.component.ts
libs/dh/shared/data-access-mocks/src/index.ts
libs/dh/shared/data-access-mocks/src/lib/data/imbalance-prices/imbalance-prices-overview-query.ts
libs/dh/shared/data-access-mocks/src/lib/imbalance-prices-mocks.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

- add GraphQL mocks for imbalance prices overview
- connect table to GraphQL
- add missing translations
- show badge in status column
- N/A

feat(dh): connect table to GraphQL

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.html
libs/dh/shared/domain/src/lib/permission.ts

- add permission on edit button
- remove non-existing permission
- N/A

fix(dh): add permission on edit button

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/imbalance-prices/shell/src/lib/drawer/dh-drawer.component.html
libs/dh/imbalance-prices/shell/src/lib/drawer/dh-drawer.component.ts
libs/dh/imbalance-prices/shell/src/lib/file-uploader/dh-imbalance-prices-uploader.component.ts
libs/dh/imbalance-prices/shell/src/lib/table/dh-table.component.html
libs/dh/imbalance-prices/shell/src/lib/table/dh-table.component.ts

feat(dh): add basic drawer to imbalance prices

---

libs/watt/src/lib/components/expandable-card/watt-expandable-card.component.ts

fix(watt): change default toggle position

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/imbalance-prices/shell/src/lib/drawer/dh-drawer.component.html
libs/dh/imbalance-prices/shell/src/lib/drawer/dh-drawer.component.ts

- update translations
- add 1 to month param
- add bottom padding to drawer
- N/A

fix(dh): minor adjustments to imbalance prices

---

libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/shared/atomic-design/ui-organisms/src/lib/footer/eo-footer.component.ts
libs/watt/src/lib/components/shell/shell.component.scss

Fix issue with scrollbar / overflow-y
- #0000

Fix issue with scrollbar / overflow-y

---

libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts

missing requirement

---

.github/workflows/detect-changes.yml
.github/workflows/dh-cd.yml

- bump 3rd party actions to get rid of Node.js deprecation warning
- N/A

chore: bump 3rd party actions

---

.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml
README.md

- use latest v2 SonarCloud GitHub Action
- remove Coverage badge since it doesn't show actual code coverage information
- N/A

chore: update SonarCloud Actions

---

libs/dh/shared/data-access-mocks/src/lib/data/esett/mga-imbalance-search-response-query.ts
libs/dh/shared/data-access-mocks/src/lib/data/esett/service-status-query.ts
libs/dh/shared/data-access-mocks/src/lib/esett-mocks.ts

chore(dh): add eSett mocks

---

libs/eo/certificates/feature-details/eo-certificate-details.component.ts

Remove hardcoded grid area at the certificates details page. 
- #0000

Update Bidding Zone in Certificate Details Component

---

libs/dh/wholesale/feature-request-calculation/src/lib/dh-whole-request-calculation-validators.ts
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

We are missing the relation between actor and gridarea, so now we can choose between all gridareas

Choose between all grid areas

---

libs/dh/core/shell/src/lib/dh-core-shell.providers.ts
libs/dh/globalization/feature-language-picker/src/lib/language-service/dh-language.initializer.ts
libs/dh/globalization/feature-language-picker/src/lib/language-service/dh-language.service.ts
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.component.html
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.component.ts

Change langauge and save the choosen one

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/MarketParticipant/V1/MarketParticipantClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/MarketParticipant/V1/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/shared/domain/src/lib/permission.ts

Permission added
Updated MarketParticipant Client for Actor Name update and UI permission change
- #0000

Updated MarketParticipant Client for Actor Name update and UI permission change

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/profile/data-access-graphql/update-user-profile.graphql
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/user-profile-mocks.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

Its now possible to update ones userProfile

Update user profile

---

apps/dh/app-dh/project.json
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/globalization/configuration-watt-translation/src/lib/dh-watt-translation.providers.ts
libs/watt/src/lib/components/picker/datepicker/index.ts

Add translations for date picker in `DataHub`.
- #0000

feat(dh, i18n): add translations for datepicker

---

.github/workflows/dh-healthchecks.yml
.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml

Updated to version 4 to fix deprecation error
https://github.com/Energinet-DataHub/Internal-Repo/issues/867

Changed upload-artifact to version 4

---

.github/workflows/codeql.yml

- bump CodeQL Action to v3 to get rid of Node.js deprecation warnings
- N/A

chore: bump CodeQL Action to v3

---

libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts

chore(dh): add mock for Organization from CVR

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts

fix(dh): minor changes to creating an organization

---

libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.ts

- add space between chip and button
- include wrapper element in `if` check
- N/A

fix(dh): minor adjustments to eSett

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/profile/feature-profile-modal/src/index.ts
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.component.ts
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.service.ts

- refresh users in Admin when user profile is updated
- update translation
- N/A

feat(dh): refresh users in Admin when user profile is updated

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts

fix(dh): add delay before refreshing list of users

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-organization-step.component.ts

feat(dh): add Germany to create organization dropdown

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts

fix(dh): remove delay before refreshing list of users

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/eo/dashboard/shell/src/lib/eo-lottie.component.ts
workspace-tools/package.json

fix: lint errors

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

Improve status explanation.

---

.github/workflows/dh-ci-frontend.yml
NOTICE.md

Replace marvinpinto/action-automatic-releases action

---

libs/eo/shared/assets/src/assets/configuration/eo-api-environment.json
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/data-access-mocks/src/lib/transfer.ts
libs/eo/transfers/src/lib/eo-transfers.service.ts

Update transfer API endpoints and use latest versions 
- [#2495](https://github.com/Energinet-DataHub/energy-origin-issues/issues/2495)

EO: Update transfer API endpoints

---

yarn.lock

chore: update IP dependency

---

libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/dh-metering-gridarea-imbalance.store.ts

fix(dh): set correct page size

---

libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.html
libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.ts
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.ts
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/table/dh-table.component.html
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/table/dh-table.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.ts

refactor(dh): use new control-flow syntax in eSett

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts

fix(dh): add text to translation

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-actor-step.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-organization-step.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-client-secret-view.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-client-secret-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/dh-b2b-access-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/status-badge/dh-actor-status-badge.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/table/dh-actors-table.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/table/dh-actors-table.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/table/dh-table.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/table/dh-table.component.ts

- migrate `market-participant/actors` domain to new control flow syntax 
- N/A

refactor(dh): use new control flow syntax

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/delegation-tab/dh-delegation-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/shared/data-access-mocks/src/lib/token.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

feat(dh): add empty delegation tab

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-delegation/src/lib/dh-delegation-tab.component.ts

feat(dh): move button in empty state

---

libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts

fix(dh): set loading state on error

---

workspace-tools/package.json
workspace-tools/src/executors/generate-translation-keys/executor.ts

Fix linting issues on `main`
https://cloud.nx.app/runs/nsD1bxinUN
- #0000

Fix linting issues

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/MarketParticipant/V1/MarketParticipantClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/MarketParticipant/V1/swagger.json
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/shared/domain/src/lib/generated/v1/model/market-participant-eic-function.ts
schema.graphql

Added delegated market role

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-graphql/get-delegations-for-actor.graphql
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-delegation/jest.config.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/dh-delegation-tab.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/dh-delegations.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/overview/dh-delegations-overview.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/util/dh-group-delegations.spec.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/util/dh-group-delegations.ts
libs/dh/market-participant/actors/feature-delegation/src/test-setup.ts
libs/dh/market-participant/actors/feature-delegation/tsconfig.json
libs/dh/market-participant/actors/feature-delegation/tsconfig.lib.json
libs/dh/market-participant/actors/feature-delegation/tsconfig.spec.json
libs/dh/shared/data-access-mocks/src/lib/data/get-delegations-for-actor.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

feat(dh): group delegations in overview

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-delegation/src/lib/status/dh-delegation-status.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/table/dh-delegation-table.componen.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-delegations-for-actor.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

feat(dh): show status badge for delegation

---

libs/watt/src/lib/utils/date/dayjs.ts

missing custom parse format

---

libs/dh/wholesale/feature-calculations/src/lib/filters/filters.component.ts

fix(dh): reduce spacing between filters

---

libs/watt/src/lib/components/field/watt-field.component.scss

fix(watt): left padding again

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-delegation/src/lib/util/dh-group-delegations.spec.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/util/dh-group-delegations.ts

fix(dh): show all delegation message types in overview

---

.github/workflows/dh-cd.yml
.github/workflows/dh-ci-dotnet.yml
apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi.Tests/integrationtest.local.settings.sample.json
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

chore: Use new NuGet packages

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-graphql/get-delegations-for-actor.graphql
libs/dh/market-participant/actors/data-access-graphql/stop-delegations.graphql
libs/dh/market-participant/actors/feature-delegation/src/lib/dh-delegation-create-modal.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/stop/dh-delegation-stop-modal.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/table/dh-delegation-table.componen.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-delegations-for-actor.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts
schema.graphql

Stop delegation

---

libs/dh/esett/data-access-graphql/get-metering-gridarea-imbalance.graphql
libs/dh/esett/data-access-graphql/get-outgoing-message-by-id.graphql
libs/dh/esett/data-access-graphql/get-outgoing-messages.graphql
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/drawer/dh-drawer.component.html
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/table/dh-table.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.html
libs/dh/shared/domain/src/lib/generated/graphql.ts

refactor(dh): use displayName to show grid area code + name

---

libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts

feat(dh): add download to outgoing message drawer

---

libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.ts

fix(dh): refresh actors tab in organization drawer

---

libs/eo/activity-log/shell/src/lib/eo-activity-log-shell.component.ts
libs/eo/core/globalization/assets-localization/i18n/da.ts

Fix messages in activity log in `eo`

Fix translation and condition in EoActivityLogShellComponent

---

libs/dh/wholesale/feature-calculations/cypress/support/commands.ts
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.html
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts

There was a weird issue in create calculations period field. Upgrading to V2 seems to fix the problem 🤷

refac(dh): use WattDatepickerV2Component in create calculation

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/util/dh-can-delegates-for.directive.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/create/dh-delegation-create-modal.component.html
libs/dh/market-participant/actors/feature-delegation/src/lib/create/dh-delegation-create-modal.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/stop/dh-delegation-stop-modal.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/table/dh-delegation-table.componen.ts

- always show grid area dropdown in delegation set up
- do not show date if delegation is cancelled
- adjustments to stop date
- only show Delegation tab to selected market roles
- N/A

feat(dh): adjustments to delegation

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Subscription/CalculationSubscription.cs
apps/dh/api-dh/source/DataHub.WebApi/Registration/GraphQLRegistrationExtensions.cs
libs/dh/market-participant/actors/feature-delegation/src/lib/create/dh-delegation-create-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/wholesale/data-access-graphql/create-calculation.graphql
schema.graphql

This PR adds a new CalculationCreated subscription to the GraphQL API. It isn't used for anything yet, since I wanted to keep the PR small.

feat(dh): CalculationCreated

---

apps/dh/e2e-dh/src/e2e/b2c-healthchecks.cy.ts

fix(dh): fix healthcheck tests

---

libs/dh/shared/ui-util/src/lib/dh-dropdown-translator.directive.ts
libs/eo/activity-log/shell/src/lib/eo-activity-log-shell.component.cy.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.component.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts
libs/watt/src/lib/components/radio/watt-radio.component.ts
libs/watt/src/lib/components/text-field/watt-text-field.component.ts
libs/watt/src/lib/components/textarea-field/watt-textarea-field.component.ts

feat(watt): add support for sorting options in dropdown

---

libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/filters/dh-filters.component.html
libs/dh/market-participant/actors/feature-delegation/src/lib/create/dh-delegation-create-modal.component.html
libs/dh/wholesale/feature-calculations/src/lib/filters/filters.component.ts
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.html

feat(dh): add default sorting to grid area dropdown

---

libs/watt/src/lib/components/phone-field/storybook+/watt-phone-field.stories.ts
libs/watt/src/lib/components/phone-field/watt-phone-field.component.ts

feat(watt): add story to Storybook

---

libs/dh/wholesale/feature-calculations/src/lib/details/details.component.html
libs/dh/wholesale/feature-calculations/src/lib/details/details.component.ts

fix: broken drawer in calculations

---

PRODUCTION_DEPENDENCIES.md
apps/dh/api-dh/openapitools.json
apps/dh/api-dh/source/DataHub.WebApi/openapitools.json
libs/dh/shared/domain/src/lib/generated/v1/api/esett-exchange-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/imbalance-prices-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-actor-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-actor-query-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-permissions-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-assignment-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/message-archive-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/token-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/api/wholesale-settlement-report-http.service.ts
openapitools.json
package.json
yarn.lock

- update various GraphQL dependencies
- update OpenAPI Generator to latest
- #0000

chore: update dependencies

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

feat(dh): put balance responsible relations behind feature flag

---

libs/eo/core/globalization/assets-localization/i18n/da.ts

dummy change to trigger eo deployment

---

libs/dh/market-participant/actors/data-access-graphql/get-balance-responsible-relation.graphql
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.ts
libs/dh/market-participant/actors/feature-delegation/src/lib/dh-delegation-tab.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/balance-responsible-agreements.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-actors.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts

chore(dh): add mock data to balance responsible relations

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/util/dh-group-balance-responsible-agreements.ts

feat(dh): adjustments to balance responsible relations

---

.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml
README.md

chore: remove SonarCloud from workspace

---

yarn.lock

chore: update ejs dependency

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-settlement-report.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-wholesale-feature-settlement-reports-v2.component.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/table/dh-settlement-reports-table.component.html
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/table/dh-settlement-reports-table.component.ts

feat(dh): basic settlement reports list overview

---

libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-wholesale-feature-settlement-reports-v2.component.ts

fix(dh): do not show title in empty view

---

libs/dh/shared/data-access-mocks/src/lib/data/wholesale-settlement-reports.ts
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/wholesale/data-access-graphql/request-settlement-report.graphql
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.html
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

- request settlement report
- `calculationId` is empty for now. The final value will come in a follow-up PR
Note: success/error notification, and list refresh, will come in a follow-up PRs
- #0000

feat(dh): request settlement report

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-wholesale-feature-settlement-reports-v2.component.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

feat(dh): refresh list and show notification

---

.github/workflows/dh-ci-frontend.yml

Do not use softprops/action-gh-release in CI

---

libs/dh/market-participant/actors/shell/src/lib/dh-market-participant-actors-shell.component.ts

fix(dh): set height on shell element

---

apps/dh/api-dh/documents/development.md
apps/dh/api-dh/project.json
apps/dh/app-dh/project.json

This should hopefully fix the issues we see in CI.

fix: graphql schema not generated automatically

---

libs/watt/src/lib/components/radio/watt-radio.component.ts

fix(watt): bind directly to name in radio component

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

fix: clarify the resolution transition error

---

libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts

The resolution transition validation should only apply to balance fixings and aggregations.

fix: conditionally validate resolution transition

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/data/get-settlement-report-calculations-by-grid-areas.ts
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/wholesale/data-access-graphql/get-settlement-report-calculations-by-grid-areas.graphql
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-select-calculation-modal.component.ts

feat(dh): select calculation for period and grid area

---

libs/dh/core/shell/src/index.ts
libs/dh/shared/util-application-insights/src/lib/dh-application-insights.service.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-select-calculation-modal.component.ts

chore(dh): minor fixes

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

chore(dh): update translations

---

apps/dh/api-dh/documents/development.md

Update code generation documentation for:
- Verifying new generated GraphQL schemas
- Generating subsystem clients using NSwag

docs: Update dotnet code generation documentation

---

libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

refactor(dh): use map operator to create dropdown options

---

libs/eo/shared/environments/src/lib/environment.mocked.ts

fix(eo): component tests

---

libs/dh/market-participant/grid-areas/overview/src/lib/dh-market-participant-gridarea-overview.component.ts
libs/dh/market-participant/grid-areas/shell/src/lib/dh-grid-areas-shell.component.ts

Fixes https://github.com/Energinet-DataHub/team-raccoons/issues/643

Removed id from result

---

README.md
libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.store.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

feat(dh): show all grid areas to energy supplier 

---

libs/dh/admin/feature-user-roles/src/lib/edit/dh-edit-user-role-modal.component.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts
libs/watt/src/lib/components/tabs/watt-tab.component.ts
libs/watt/src/lib/components/tabs/watt-tabs.component.html
libs/watt/src/lib/components/tabs/watt-tabs.component.ts

Fixes https://github.com/Energinet-DataHub/Internal-Repo/issues/1022

added setSelectedIndex to watt-tabs component

---

libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-wholesale-feature-settlement-reports-v2.component.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

fix(dh): adjustments to settlement reports

---

libs/dh/wholesale/feature-settlement-reports-v2/src/lib/dh-wholesale-feature-settlement-reports-v2.component.ts
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

- show all grid areas to system operator role
- #0000

feat(dh): adjustments to settlement reports

---

libs/watt/src/lib/components/dropdown/watt-dropdown.component.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts

revert(watt): revert change to dropdown component

---

apps/eo/app-eo-landing-page/src/app/app.routes.ts

Fix energy track and trace redirect if the user has configured the browser for a non-supported language like `DE.` Before, this resulted in an endless redirect loop; now, we will always fall back to `EN` unless the language is `DA.` 
- #0000

Fix energy track and trace redirect

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts

refactor(dh): minor adjustments

---

libs/eo/shared/assets/src/assets/configuration/eo-azure-b2c-settings.json

Settings file for azure b2c
[ZenHub Issue](https://app.zenhub.com/workspaces/team-atlas-633199659e255a37cd1d144f/issues/gh/energinet-datahub/energy-origin-issues/2870)

add settings file

---

libs/eo/shared/assets/src/assets/configuration/eo-azure-b2c-settings.json

replace with correct issuer
[ZenHub Issue](https://app.zenhub.com/workspaces/team-atlas-633199659e255a37cd1d144f/issues/gh/energinet-datahub/energy-origin-issues/2870)

switch to MitID policy

---

libs/watt/src/lib/components/breadcrumbs/watt-breadcrumbs.component.ts

Rewrite a component a day keeps the doctor away

Rewrite for signals

---

libs/watt/src/lib/components/dropdown/watt-dropdown.component.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts

fix(watt): remove `distinctUntilChanged` operator from dropdown

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Enable settlement reports in prod.

---

libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.html
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.ts

feat(dh): set filters in url on mga imbalance page

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

fix(dh): disable settlement reports v2 on preprod

---

libs/dh/admin/feature-user-roles/src/lib/overview/dh-roles-overview-list-filter.component.html
libs/dh/admin/feature-user-roles/src/lib/overview/dh-roles-overview-list-filter.component.ts
libs/dh/admin/shared/src/dh-role-status.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

feat(dh): set filters as url params for User roles page

---

libs/dh/shared/ui-util/src/lib/dh-dropdown-translator.directive.ts

fix(dh): handle curly braces in translation keys

---

libs/dh/wholesale/feature-calculations/src/lib/filters/filters.component.ts

feat(dh): set filters as url params for Calculations page

---

libs/watt/src/lib/components/drawer/+storybook/watt-drawer.stories.ts
libs/watt/src/lib/components/dropdown/+storybook/storybook-dropdown-reactive-forms.stories.ts
libs/watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
libs/watt/src/lib/components/picker/datepicker/+storybook/watt-datepicker-reactive-forms.stories.ts
libs/watt/src/lib/components/picker/timepicker/+storybook/storybook-timepicker-reactive-forms.stories.ts

- remove double validation error from Storybook
- use new control flow syntax
- #0000

fix(watt): remove double validation error from Storybook

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/SettlementReportsQuery.cs

Fixes https://github.com/Energinet-DataHub/Internal-Repo/issues/1104

Order by start

---

libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.ts

Refactor a component a day keeps the doctor away

Refactor: signals

---

apps/eo/app-eo/src/index.html

dummy change to trigger deployment

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.routes.ts

fix(dh): drop v2 from settlement reports

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

chore(dh): bump feature flags

---

.github/workflows/ci-orchestrator.yml
.github/workflows/dh-cd.yml
.github/workflows/dh-ci-dotnet.yml
.github/workflows/dh-healthchecks.yml
.github/workflows/watt-cd.yml

- upgrade internal workflows to v14
- use version of dotnet controlled by `global.json`
- #0000

chore: upgrade actions to v14 and default dotnet

---

libs/dh/admin/feature-user-roles/src/lib/edit/dh-edit-user-role-modal.component.ts

temp: Remove user role without permissions rule.

---

libs/dh/admin/feature-user-roles/src/lib/edit/dh-edit-user-role-modal.component.ts

Reverts Energinet-DataHub/greenforce-frontend#3310

Revert "temp: Remove user role without permissions rule."

---

libs/dh/admin/shell/src/lib/dh-admin-shell.component.ts
libs/dh/admin/shell/src/lib/dh-admin-shell.routes.ts
libs/dh/core/routing/src/dhPaths.ts

fix(dh): change route "user" to "users"

---

libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

https://github.com/Energinet-DataHub/team-mosaic/issues/237

Limit energysupplier

---

libs/eo/shared/services/src/auth/auth.interceptor.spec.ts
libs/eo/shared/services/src/auth/auth.interceptor.ts

- Make sure wallet api endpoints is also intercepted and thereby have an auth header added. 
- #0000

feat(eo): intercept wallet-api

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/UserQuery.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/UserRoleQuery.cs
libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts
libs/dh/admin/data-access-graphql/get-user-role-with-permissions.graphql
libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.html
libs/dh/admin/feature-user-roles/src/lib/drawer/dh-role-drawer.component.html
libs/dh/admin/feature-user-roles/src/lib/drawer/tabs/content/dh-role-audit-logs.component.ts
libs/dh/admin/feature-user-roles/src/lib/drawer/tabs/content/dh-role-master-data.component.ts
libs/dh/admin/feature-user-roles/src/lib/drawer/tabs/content/dh-role-permissions.component.ts
libs/dh/admin/feature-user-roles/src/lib/drawer/tabs/dh-drawer-role-tabs.component.html
libs/dh/admin/feature-user-roles/src/lib/drawer/tabs/dh-drawer-role-tabs.component.ts
libs/dh/admin/feature-user-roles/src/lib/edit/dh-edit-user-role-modal.component.ts
libs/dh/admin/shared/src/dh-role-status.component.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-user-role-get-user-role-with-permissions.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/model/models.ts

refactor(dh): get user role with permissions

---

libs/dh/wholesale/domain/src/calculation.ts
libs/dh/wholesale/feature-calculations/src/lib/calculations.cy.ts
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.html
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.scss
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts
libs/dh/wholesale/feature-calculations/src/lib/grid-areas/dropdown.component.ts
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

This PR moves all of the logic concerning grid areas in create calculations into its own component. I had to skip the cypress test since I just couldn't get it to work (the query would not return the mocked data). I couldn't justify spending any more time on that, so I'm skipping it for now. We will have a talk about it later.

refac(dh): grid area in create calculation

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/UserRoleMutation.cs
libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
libs/dh/admin/data-access-graphql/update-user-and-roles.graphql
libs/dh/admin/data-access-graphql/update-user-role.graphql
libs/dh/admin/feature-user-roles/src/lib/edit/dh-edit-user-role-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-user-role-get-all.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-user-role-get-user-role-with-permissions.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/model/models.ts

refactor(dh): change update user role to use GraphQL 

---

libs/dh/wholesale/feature-calculations/src/lib/create/create.component.html
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html

fix(dh): remove min date on datepicker

---

libs/eo/transfers/src/lib/form/eo-transfers-date-time.component.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.component.scss
libs/watt/src/lib/components/field/watt-field.component.ts
libs/watt/src/lib/components/picker/shared/picker.scss

Potentially breaking (styles only though). DH and ETT has been tested.

fix(watt): add sensible defaults

---

libs/watt/src/lib/components/vater/vater-flex.component.ts
libs/watt/src/lib/components/vater/vater-stack.component.ts
libs/watt/src/lib/components/vater/vater-utility.directive.ts
libs/watt/src/lib/foundations/_vater.scss

- Add new center utility to vater
- Change offset to use padding instead of margin
- Make it possible to customize flex properties

feat(watt): new vater functions

---

libs/watt/src/lib/components/data/watt-data-table.component.ts
libs/watt/src/lib/components/drawer/watt-drawer.component.scss

- Add option to disable paginator
- Fix drawer loading overlay z-index

fix(watt): tweaks for watt-data-table in drawers

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/UserRoleMutation.cs
libs/dh/admin/data-access-api/src/index.ts
libs/dh/admin/data-access-api/src/lib/dh-create-user-role.store.ts
libs/dh/admin/data-access-graphql/create-user-role.graphql
libs/dh/admin/feature-user-roles/src/lib/create/dh-create-user-role-modal.component.html
libs/dh/admin/feature-user-roles/src/lib/create/dh-create-user-role-modal.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/model/models.ts

refactor(dh): use GraphQL to create user role

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts

fix(dh): refresh data after updating user role

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/EdiB2CMutation.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/data-access-graphql/request-calculation.graphql
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts
libs/watt/src/lib/components/field/watt-field.component.ts

- Rename gridAreas to gridArea in translation
- Complete inner observable when destroyed
- Rename topbartitle and sidebar for request calculation
- Change resolution to priceType + dynamic validation
- Remove resolution field from GraphQL mutation

feat(dh): price type in request calculation

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/SettlementReports/Dto/SettlementReportRequestDto.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/SettlementReportMutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/SettlementReports/RequestSettlementReportInput.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.html
libs/dh/wholesale/feature-settlement-reports-v2/src/lib/modal/dh-request-settlement-report-modal.component.ts

feat: Support for splitting large files in settlement reports.

---

libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.ts

Fixed nullref

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Resolvers/EsettExchangeResolvers.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/ExchangeEvent/EsettExchangeEventType.cs
libs/dh/esett/data-access-graphql/get-outgoing-message-by-id.graphql
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/esett-detailed-exchange-events.ts

Reverts Energinet-DataHub/greenforce-frontend#3368

Revert "Refactor/provide download urls in outgoing messages"

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/imbalance-prices/shell/src/lib/dh-imbalance-prices-shell.routes.ts

Lock Imbalance Prices behind manage permission.

---

libs/eo/certificates/data-access-api/eo-certificates.service.ts
libs/eo/certificates/feature-details/eo-certificate-details.component.ts
libs/eo/certificates/feature-overview/eo-certificates-overview.component.ts
libs/eo/certificates/shell/certificates.routes.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.json
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/services/src/api-versioning/api-versioning.interceptor.ts

- Add pagination to certificates overview
- Use new endpoint for fetching a single certificate for certificate details
- Adjust api version interceptor to version endpoints at wallet-api
- Remove search functionality of certificates since it's not supported by the API
- Remove sort by metering point of certificates since it's not supported by the API
- #0000

feat(eo, certificates): add pagination

---

apps/dh/api-dh/documents/development.md
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/WholesaleClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/swagger.json

Update Wholesale client to ensure latest endpoints are used and obsolete ones are removed.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/217

chore: Update Wholesale client

---

libs/eo/shared/services/src/api-versioning/api-versioning.interceptor.ts

change ett version header

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-actors.ts

- allow Signal writes in effect
- forward `closed` event when drawer is closed
- fix mock data
- #0000

fix(dh): minor fixes in market participants

---

libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.ts

fix(dh): refresh market participants on edit

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/EdiB2CMutation.cs
libs/dh/wholesale/data-access-graphql/request-calculation.graphql
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

- Make gridArea optional in GraphQL
- Remove empty check for nullable fields

fix(dh): make gridArea in request calculation optional

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/shared/domain/src/lib/permission.ts
libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.routes.ts

Added the new calculations view permission to frontend.

Updated calculations permission to view

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Attribute/PreserveParentAsAttribute.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/UserQuery.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Resolvers/MarketParticipantResolvers.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/Actor/ActorType.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/Actor/ActorUserRole.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/User/UserType.cs

Made it possible to to get what actors a associated with a user, and what userroles the user have assign to the actors
```
query userWithActors {
userById(id: "00dd083e-4825-4a7a-34dd-08dbecd83745") {
name
actors {
name
id
organization {
name
}
glnOrEicNumber
userRoles {
name
assigned
}
}
}
}
```

Queryactors on user

---

apps/dh/api-dh/documents/development.md
libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-party-b2b-access.store.ts

fix(dh): do not cache market participant credentials

---

libs/eo/auth/data-access/organization-id.interceptor.ts

remove orgid

---

libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.ts

In combination with https://github.com/Energinet-DataHub/geh-market-participant/pull/960 only allow with permission actor:manage to change the actor name

Block access to edit actorname if not actor:manage

---

libs/dh/imbalance-prices/shell/src/lib/table-day-view/dh-table-day-view.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/imbalance-prices/imbalance-prices-month-overview-query.ts

fix(dh): show 0 imbalance price in day view

---

libs/dh/admin/feature-user-management/src/lib/overview/dh-users-overview.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

feat(dh): translate environment name in download file

---

libs/dh/imbalance-prices/shell/src/lib/status-badge/dh-status-badge.component.ts
libs/dh/imbalance-prices/shell/src/lib/table-month-view/dh-table-month-view.component.html
libs/dh/imbalance-prices/shell/src/lib/table-month-view/dh-table-month-view.component.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flag.directive.ts
libs/gf/globalization/configuration-danish-locale/src/lib/danish-locale.integration.spec.ts

- Closes #3065 
- Closes #3068

refactor(dh): use Signal inputs

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj

Upgrade usages of Energinet.DataHub.Core.TestCommon and Energinet.DataHub.Core.FunctionApp.TestCommon to v6.1.0
- #0000

Upgraded TestCommon packages usage to 6.1.0

---

libs/dh/core/shell/src/lib/dh-core-login.component.ts
libs/dh/shared/feature-authorization/src/lib/dh-actor-token.service.ts

fix(dh): move failed login tracking

---

libs/eo/shared/assets/src/assets/html/onboarding-demo.html
libs/eo/shared/assets/src/assets/html/onboarding-demo.js

feat(eo, onboarding): add demo page

---

libs/eo/shared/assets/src/assets/html/onboarding-demo.js

rename onboarding status from success to granted

---

libs/dh/shared/feature-authorization/src/lib/dh-actor-token.service.ts

fix(dh): prevent logging the same event multiple times

---

libs/dh/admin/feature-user-management/src/lib/invite/dh-assignable-user-roles/dh-assignable-user-roles.component.html
libs/dh/admin/feature-user-management/src/lib/invite/dh-assignable-user-roles/dh-assignable-user-roles.component.ts
libs/dh/admin/feature-user-management/src/lib/invite/dh-invite-user-modal.component.html
libs/dh/admin/feature-user-management/src/lib/invite/dh-invite-user-modal.component.ts

fix(dh): clear user role selection when market participant changes

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculations/src/lib/details/details.component.html
libs/dh/wholesale/feature-calculations/src/lib/details/details.component.ts
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts

- Make translation more consistent
- Reorder columns
- Add more info to details
- Remove copy to clipboard functionality

fix(dh): calculation details tweaks

---

libs/eo/auth/data-access/auth.service.ts

- manually clear session storage on logout
- #0000

fix(eo, auth): manually clear session storage on logout

---

libs/dh/shared/feature-authorization/src/lib/dh-actor-token.service.ts

fix(dh): make sure logout and log to AppInsights is only called once

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
libs/dh/admin/data-access-graphql/get-all-users.graphql

feat(dh): use selected filters in users download

---

libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts

-  Add link to the footer for project origin
- #0000

feat(eo, landing-page): add link to the footer for project origin

---

libs/eo/consent/feature-grant-consent/grant-consent.component.ts

- Remove checkbox of accepting terms from grant consent dialog
- [#3302](https://github.com/Energinet-DataHub/energy-origin-issues/issues/3302)

feat(eo, consent): remove terms from grant consent dialog

---

libs/dh/shared/data-access-mocks/src/lib/data/wholesale-settlement-reports.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts

feat(dh): show id in settlement reports table

---

libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts

fix(dh): remove id column from settlement reports

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/RequestCalculationDataType.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/EdiB2CMutation.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/data-access-graphql/mutation/request-calculation.graphql
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.html
libs/dh/wholesale/feature-request-calculation/src/lib/dh-wholesale-request-calculation.ts

- Add new combined enum for priceType and meteringPointType
- Update query to use new RequestCalculationDataType
- Update request calculation view to use new mutation

feat(dh): request aggregated data from wholesale calculations

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/SettlementReports/Dto/RequestedSettlementReportDto.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/SettlementReportsQuery.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/SettlementReports/SettlementReport.cs

add filter params to settlement report return dto

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/data/wholesale-settlement-reports.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/drawer/dh-settlement-report-drawer.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.html

feat(dh): show list of grid areas in table and drawer

---

libs/eo/shared/assets/src/assets/configuration/eo-api-environment.json
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

adjust api versions

---

libs/dh/shared/data-access-mocks/src/lib/data/wholesale-settlement-reports.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.html

feat(dh): do not show download button for empty reports

---

libs/dh/wholesale/feature-settlement-reports/src/lib/drawer/dh-settlement-report-drawer.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts

feat(dh): show grid area in file name

---

libs/dh/core/shell/src/lib/dh-core-shell.component.html
libs/dh/core/shell/src/lib/dh-core-shell.component.ts
libs/dh/core/shell/src/lib/dh-notifications-center.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

feat(dh): basic notifications center

---

libs/dh/message-archive/shell/src/lib/dh-message-archive-shell.routes.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Enable the new version of message archive for everybody! I will make a PR afterwards that removes the old code and finally, the swagger gen.

feat(dh): enable message archive v2

---

libs/dh/admin/feature-user-roles/src/lib/overview/dh-roles-overview-list-filter.component.html
libs/dh/admin/feature-user-roles/src/lib/overview/dh-roles-overview-list-filter.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/message-archive/feature-search/src/lib/details.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-actors.ts
libs/dh/shared/data-access-mocks/src/lib/data/message-archive-search-response-logs.ts
libs/dh/shared/data-access-mocks/src/lib/message-archive.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.component.html

- change notification icon depending on "read" state
- show dropdown only to FAS users
- update mocks
- check for Signal value before usage
- #0000

fix: various fixes

---

libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.html
libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.ts

- add copy to clipboard icon to expandable card under user roles tab
- fix badge in expandable card
- #0000

feat(dh): add copy to clipboard to user roles tab

---

build/infrastructure/eo/host/Dockerfile
libs/eo/core/shell/src/lib/eo-account-menu.ts

chore(eo): update Dockerfile to use alpine-slim image

---

libs/dh/core/feature-notifications/src/lib/dh-notification-banner.service.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts

- style notification list
- show red notification dot on top of icon
- show banner on new notifications
- move logic to service
- rename type property
- #0000

feat(dh): improvements to notifications

---

libs/dh/core/feature-notifications/src/lib/dh-notification-banner.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notification-banner.service.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/admin/user-overview-items.ts

- display notification metadata in banner
- update mocks
- #0000

feat(dh): update banner to display notification metadata

---

apps/dh/api-dh/source/DataHub.WebApi/ApiClientSettings.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Notifications/Dto/NotificationDto.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Notifications/INotificationsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Notifications/NotificationsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Subscription/NotificationSubscription.cs
apps/dh/api-dh/source/DataHub.WebApi/Registration/DomainRegistrationExtensions.cs

Added polling of notifications

Poll notification backend

---

.github/workflows/frontend-ci.yml

Username should be variable instead of secret
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2405

add DHE2EUsername As Variable

---

libs/eo/auth/data-access/actor.service.ts

- fallback to org_ids if org_id claim does not exist
- #0000

fix(eo, auth): fallback to org_ids if org_id claim does not exist

---

libs/dh/core/feature-notifications/src/lib/dh-notification-banner.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notification-banner.service.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

feat(dh): translate notifications

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Enable MitID in preprod

---

libs/dh/core/feature-notifications/src/lib/dh-notification.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- remove notification from list when marked as read
- show tooltip on hover
- show icon on hover
- #0000

feat(dh): adjustments to notifications

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Subscription/NotificationSubscription.cs

feat(dh): get initial list of notifications without delay

---

libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/core/feature-notifications/src/lib/dh-notification-banner.service.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notification.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/shared/data-access-mocks/src/lib/notifications-mocks.ts

feat(dh): click-to-navigate in notifications

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/NotificationType.cs
libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/notifications-mocks.ts

feat(dh): add support for failed settlement report notification

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/NotificationType.cs
libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/notifications-mocks.ts

feat(dh): add support for new balance responsible notification

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/SettlementReportsQuery.cs
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.service.ts
libs/dh/shared/domain/src/index.ts
libs/dh/shared/domain/src/lib/dh-settlement-report.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/button/dh-request-settlement-report-button.component.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/drawer/dh-settlement-report-drawer.component.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports.service.ts

- move type to shared domain in preparation to be used in notifications
- move logic related to download of settlement reports in preparation to be used in notifications
- add settlement report query
- minor adjustments
- #0000

refactor(dh): code organization

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/SettlementReports/ISettlementReportsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/SettlementReports/SettlementReportsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/SettlementReportMutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/SettlementReports/CancelSettlementReportInput.cs
libs/dh/wholesale/data-access-graphql/mutation/cancel-settlement-report.graphql

Cancel settlement report job

---

libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts

fix(dh): do not show multiple banners for same notification

---

libs/dh/core/feature-notifications/src/lib/dh-notification.component.scss
libs/dh/core/feature-notifications/src/lib/dh-notification.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.component.ts
libs/dh/core/feature-notifications/src/lib/dh-notifications-center.service.ts
libs/dh/core/feature-notifications/src/lib/dh-settlement-report-notification.component.ts
libs/dh/shared/util-settlement-reports/src/index.ts
libs/dh/shared/util-settlement-reports/src/lib/dh-settlement-report-name.ts
libs/dh/shared/util-settlement-reports/src/lib/dh-settlement-report-partial.ts
libs/dh/shared/util-settlement-reports/src/lib/dh-settlement-reports.service.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts

- move util function to own file
- remove action button from base notification component
- create download settlement report notification component
- #0000

feat(dh): show settlement report file name in notification

---

libs/dh/esett/feature-outgoing-messages/src/lib/status-badge/dh-outgoing-message-status-badge.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.ts

refactor(dh): use Signals in components

---

libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts
libs/dh/imbalance-prices/shell/src/lib/drawer/dh-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/esett-detailed-exchange-events.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-settlement-reports-table.component.ts
workspace-tools/package.json

- use `output` function in components
- update mocks
- bump dependency to get rid of a lint error
- #0000

refactor(dh): use output function in components

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-organizations/src/lib/details/tabs/dh-organization-history.component.ts

Show when a domain is added/removed in audit log

---

libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/actor-audit-log-tab/dh-actor-audit-log-tab.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/actor-audit-log-tab/dh-actor-audit-log-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-filter.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-audit-log.service.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/util/dh-can-delegates-for.directive.ts
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/table/dh-actors-table.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/table/dh-actors-table.component.ts

refactor(dh): use Signals in market participants page

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-delegation/src/lib/create/dh-delegation-create-modal.component.ts

Also fixes translations for RSM-12

Remove one delegation from EnergySupplier

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.html

fix(dh): display permission name in drawer

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

update canceled status

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/MergeMarketParticipantsMutation.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-graphql/mutation/merge-market-participants.graphql
libs/dh/market-participant/actors/feature-actors/src/lib/merge/dh-merge-market-participants.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/merge/dh-unique-market-participants.validator.ts
libs/dh/shared/data-access-mocks/src/lib/data/market-participant-actors.ts
libs/dh/shared/data-access-mocks/src/lib/market-participant.ts

- add simple Mutation in BFF to accept params from FE
- add mutation mock
- move validator to separate file
- fix validator to handle `null` values
- save form data using validator
- show dialog on success
- show dialog on error
- refetch queries after mutation execution is done
- #0000

feat(dh): improvements to merge of market participants

---

.devcontainer/devcontainer.json

This is an experiment with GitHub's codespaces, to see if we can create a reliable setup for some quick and easy development work.

feat: add devcontainer.json

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/NotificationType.cs
libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/notifications-mocks.ts

feat(dh): add support for market participants consolidation notification

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

feat(dh): enable merge market participants on test-01

---

build/infrastructure/eo/host/nginx.conf

feat(nginx): add redirect from www to non-www for energytrackandtrace.dk

---

libs/dh/market-participant/actors/feature-actors/src/lib/merge/dh-merge-market-participants.component.ts

fix(dh): set min date for merge of market participants

---

libs/dh/admin/feature-user-management/src/lib/edit/edit.component.ts

Fixes https://github.com/Energinet-DataHub/team-raccoons/issues/970

Refetch details

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/UserRoleQuery.cs
libs/dh/admin/data-access-graphql/query/get-user-roles-for-csv.graphql
libs/dh/admin/feature-user-roles/src/lib/download.component.ts
libs/dh/admin/feature-user-roles/src/lib/table.component.ts

Fixes https://github.com/Energinet-DataHub/team-raccoons/issues/969

Fix download

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/GridArea/GridAreaAuditedChangeAuditLogDtoType.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/grid-areas/src/audit-log.component.ts

fix(dh): adjustments to grid area and market participant details

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/merge/dh-merge-market-participants.component.ts

fix(dh): values in grid access provider dropdown

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/grid-areas/src/audit-log.component.ts

feat(dh): add grid area owner to translation

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/GridArea/CalculateGridAreaStatusTest.cs
apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/CalculateGridAreaStatusTest.GetGridAreasWithStatus.verified.json
apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/GridAreaStatus.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Resolvers/GridAreaResolver.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/grid-areas/src/status-badge.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-grid-area-overview.ts

fix(dh): remove unused badge status

---

.github/workflows/ci-orchestrator.yml

Add merge_group trigger
- #0000

Add merge_group trigger

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-error-handling.ts

- changes in #2707 caused translation of existing API errors to fail. This PR brings back some logic that was removed in #2707 
- #0000

fix(dh): fix API error translation logic 

---

libs/dh/shared/assets/src/assets/configuration/dh-app-environment.local.json
libs/dh/shared/environments/src/lib/app-environment/dh-app-environment.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.service.spec.ts
libs/dh/shared/util-application-insights/src/lib/dh-application-insights.service.ts

fix(dh): use connection string to configure App Insights

---

PRODUCTION_DEPENDENCIES.md
bun.lock
package.json

- bump `mermaid` dependency to fix security vulnerability 
- #0000

chore: bump mermaid dependency

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-organization-step.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-company-name-max-length.validator.ts

feat(dh): set max length on organization name

---

.github/workflows/ci-orchestrator.yml
.github/workflows/detect-changes.yml

Add missing needs in allow_merge clause

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/index.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/dh/metering-point/feature-search/src/lib/dh-is-valid-metering-point-id.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point.routes.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point.validator.ts
libs/dh/metering-point/feature-search/src/lib/dh-search.component.ts

feat(dh): make metering point search page and navigation to overview

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-energy-supplier.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/watt/src/lib/foundations/breakpoints/_breakpoints.import.scss

feat(dh): improvements to metering point overview

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-actual-address.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-address-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-contact-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts

feat(dh): address and contact modals

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-highlights.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-status.component.ts

feat(dh): status and highlights badges in metering point

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-address-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-contact-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-highlights.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/watt/src/lib/foundations/_variables.scss

- improvements to metering point overview page
- change color of `warning` icon
- #0000

feat(dh): improvements to metering point

---

apps/eo/e2e-eo/src/e2e/third-party/third-party.ts

This PR aims to fix the flaky e2e tests in the eo app 🙂

Fix flaky tests in eo

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts

chore(dh): remove connection date

---

libs/dh/admin/feature-permissions/src/lib/details/edit.component.ts
libs/dh/admin/feature-user-management/src/lib/details/details.component.html
libs/dh/admin/feature-user-roles/src/lib/user-roles.component.html
libs/dh/admin/feature-user-roles/src/lib/user-roles.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.html
libs/watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/watt/src/lib/foundations/icon/icons.ts
libs/watt/src/lib/foundations/typography/index.scss
libs/watt/src/lib/utils/date/watt-date.pipe.spec.ts
libs/watt/src/lib/utils/date/watt-format-date.ts

- replace menu icon with three vertical dots
- use `id` in for loop
- remove badge from component
- remove tabs from component
- wrap market role in parenthesis in title
- add new icon
- remove comma from long date format
- set `font-weight` on `b` tag
- #0000

feat(dh): minor adjustments

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-customer-cpr.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts

- design adjustments accordign to Figma
- add customer id input to component
- #0000

feat(dh): design adjustments to customer card

---

libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts
libs/eo/core/globalization/assets-localization/i18n/translation-keys.ts
libs/eo/core/globalization/assets-localization/translations.ts
libs/eo/transfers/src/lib/form/eo-receiver-input.component.ts
libs/eo/transfers/src/lib/form/eo-transfers-form.component.ts

Adds a small consent label for each of the POA receivers the user has access to
Image of new look:

Consent label in receiver input field

---

libs/dh/metering-point/feature-search/src/lib/dh-can-activate-metering-point-overview.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

fix(dh): handle non-existing metering point

---

libs/dh/esett/feature-outgoing-messages/src/lib/table.component.ts

fix(dh): change default sorting on eSett outgoing messages

---

apps/dh/api-dh/source/DataHub.WebApi/Modules/ProcessManager/Requests/Types/RequestCalculatedEnergyTimeSeriesResultType.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/ProcessManager/Requests/Types/RequestCalculatedWholesaleServicesResultType.cs

refac: Log argument out of range value for actor requests

---

.github/CODEOWNERS

https://app.zenhub.com/workspaces/team-fusion-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2847

2847: remove Outlaws and Ratatosk

---

libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts

As title says; adds link to footer 🙂

Adds new link to footer

---

libs/dh/esett/feature-outgoing-messages/src/lib/table.component.ts

fix(dh): set default sorting on eSett outgoing messages

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-meter-data.component.ts

feat(dh): add new columns to meter data

---

apps/dh/e2e-dh/cypress.config.ts
apps/dh/e2e-dh/package-lock.json
apps/dh/e2e-dh/package.json
apps/dh/e2e-dh/src/e2e/app-shell.cy.ts

- check for existence of market participant name in test
- update dependencies
- set `viewportWidth` to 1280 in config
This PR introduces a quick solution to #4010 until a better approach is agreed upon

fix(e2e-dh): check market participant name in test

---

apps/dh/e2e-dh/cypress-acceptance-tests.config.ts

fix(e2e-dh): set viewportWidth in config

---

apps/dh/e2e-dh/src/e2e/app-shell.cy.ts

fix(e2e-dh): fix acceptance test

---

apps/dh/e2e-dh/src/e2e/app-shell.cy.ts

fix(e2e-dh): remove unstable test assertion

---

libs/dh/electricity-market/src/simple-view/file-uploader/dh-metering-points-master-data-uploader.component.ts

fix(dh): correct endpoint url

---

apps/dh/e2e-dh/src/e2e/app-shell.cy.ts
libs/dh/shared/data-access-mocks/src/lib/wholesale.mocks.ts
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.spec.ts
libs/dh/wholesale/feature-calculations/src/lib/calculations.cy.ts

fix(dh): minor adjustments

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts

feat(dh): translate master data properties

---

libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts

Adds a link to project origin in our help section

Project Origin link

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/graphql/get-metering-point-by-id.graphql
libs/dh/metering-point/feature-overview/src/lib/dh-address-details.component.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): adjustments to metering point

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

feat(dh): enable electricity market in test_001

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Modules/ElectricityMarket/ElectricityMarketOperations.cs
libs/dh/core/routing/src/dhPaths.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-debug/src/debug-metering-points/metering-points.component.ts
libs/dh/metering-point/feature-debug/src/graphql/get-metering-points-by-grid-area.graphql
libs/dh/metering-point/feature-debug/src/routes.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): metering points overview for debugging

---

libs/dh/metering-point/feature-debug/src/debug-metering-point/metering-point.component.ts
libs/dh/metering-point/feature-debug/src/debug.component.ts
libs/dh/metering-point/feature-debug/src/routes.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

fix(dh): feature flags adjustments

---

libs/dh/metering-point/feature-search/src/lib/dh-search.component.ts

feat(dh): show spinner in metering point search

---

libs/dh/metering-point/feature-overview/src/lib/dh-actual-address.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts

feat(dh): minor adjustments to metering point

---

libs/dh/metering-point/feature-overview/src/lib/dh-can-see-value.directive.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point.component.ts

feat(dh): show energy supplier card to relevant market participants

---

libs/eo/transfers/src/lib/eo-create-transfer-agreement-modal.component.ts
libs/eo/transfers/src/lib/form/eo-transfers-form.component.ts

This small addition is to make sure the forward and previous buttons of the stepper always are in the bottom by adding a fixed value to the stepper content

Min height on stepper content

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/graphql/get-metering-point-by-id.graphql
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): show CVR in UI

---

libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts

fix(dh): minor adjustments to metering point overview

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Modules/SettlementReports/SettlementReportOperations.cs

Models for migrated Wholesale calculations has been removed from the Process Manager, but we still need it to be able to get the correct calculation id from migrated calculations.

Update Process Manager package and fix breaking change for migrated calculations

---

libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts

feat(dh): adjustments to who can see certain MP properties

---

libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/shared/domain/src/lib/permission.ts

feat(dh): add permission to CPR button

---

libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-energy-supplier.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point.component.ts

feat(dh): minor adjustments to metering point page

---

libs/dh/metering-point/feature-overview/src/lib/dh-address-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-can-see.directive.spec.ts
libs/dh/metering-point/feature-overview/src/lib/dh-can-see.directive.ts
libs/dh/metering-point/feature-overview/src/lib/dh-customer-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-highlights.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point.component.ts

feat(dh): adjustments to metering point master data

---

libs/dh/metering-point/feature-debug/src/debug-metering-points/metering-points.component.ts
libs/dh/wholesale/feature-calculations/src/lib/filters/filters.component.ts

fix(dh): show correct grid area display name

---

libs/dh/metering-point/feature-overview/graphql/get-metering-point-by-id.graphql
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): adjust fields based on electrical heating value

---

.github/workflows/dh-healthchecks.yml

chore: add .NET setup step to pipeline

---

libs/dh/metering-point/feature-overview/graphql/get-metering-point-by-id.graphql
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-details.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point.component.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): adjustments to metering point layout

---

bun.lock
libs/eo/shared/components/ui-footer/footer.component.ts
libs/watt/package/package.json

Adds 2 new breakpoints to accomodate the sizes just before the sidenav collapses.
Before:
After:

New resizing

---

apps/dh/api-dh/source/DataHub.WebApi/appsettings.json.sample

Add measurements client setting to sample file

---

libs/dh/core/shell/src/lib/dh-core-shell.component.html
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point.component.ts
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts
libs/dh/shared/navigation/src/breadcrumb.service.ts

fix(dh): persist breadcrumb in matering point page

---

libs/dh/esett/feature-outgoing-messages/src/lib/table.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

fix(dh): fix spelling in eSett

---

libs/dh/metering-point/feature-overview/src/components/measurement/dh-format-observation-time.pipe.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements.component_v2.ts

refactor(dh): move format logic to pipe

---

libs/dh/metering-point/feature-overview/src/components/related/dh-related-metering-point.component.ts
libs/dh/metering-point/feature-overview/src/components/related/dh-related-metering-points.component.ts
libs/watt/package/core/color/+storybook/storybook-colors-overview.component.scss
libs/watt/package/core/styles/_box-sizing.scss
libs/watt/package/package.json
libs/watt/package/table/watt-table.component.scss

feat(dh): add current metering point in list of relateed metering points, add hover state

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

INC0442122 was caused by a breaking change, that should get fixed by this PR
[INC0442122](https://energinet.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Ddee9536547b02258574ea242036d433d&sysparm_record_target%3Dincident&sysparm_record_row%3D1&sysparm_record_rows%3D11&sysparm_record_list%3DstateNOT%2BIN6%252C7%255Eassigned_toDYNAMIC90d1921e5f510100a9ad2572f2b477fe%255Esys_class_name%253Dincident%255Eassignment_group%2521%253D33a474efdba404580b0a2aea4b961987%255Eassignment_group%2521%253D6c918f97dbb0801070e2e16c0b961956%255Eassignment_group%2521%253D1bca3cc71bff1d105402f646464bcbfb%255Eassignment_group%2521%253Df67abaaf0f79d300a3fefd4ce1050e36%255EORcaller_id%253D3e96f0730f57790020887f5ce1050ee9%255EORopened_by%253D3e96f0730f57790020887f5ce1050ee9%255EORDERBYDESCnum …

[BFF] Update MeasurementsClient to fix INC0442122

---

libs/dh/metering-point/feature-overview/src/components/can-see/dh-can-see.directive.spec.ts
libs/dh/metering-point/feature-overview/src/components/customer/dh-customer-contact-details.component.ts

fix(dh): minor adjustments to metering point page

---

libs/watt/package/package.json
libs/watt/package/segmented-buttons/watt-segmented-buttons.component.scss

Implements input from UX 🙂 
BEFORE:
AFTER:

Small styling update

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/components/measurement/dh-drawer-day-view.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day.component.ts

feat(dh): initial day view drawer

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day-details.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day.component.ts
libs/dh/metering-point/feature-overview/src/graphql/get-measurement-points.graphql
libs/dh/metering-point/feature-overview/src/graphql/get-measurements.graphql
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

feat(dh): adjustments to historic measurements view

---

libs/dh/metering-point/feature-overview/src/components/dh-metering-point.component.ts
libs/dh/metering-point/feature-search/src/routes.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Remove feature flag

---

libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day-details.component.ts
libs/watt/package/package.json
libs/watt/package/table/watt-table.component.scss

- add default sorting on table
- add margin to header column arrow
- #0000

fix: set default sorting on table

---

apps/dh/app-dh/project.json
package.json

Just an attempt at fixing the flaky unit tests in CD

fix(dh): try to run generate before tests

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-month.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-navigation.component.ts
libs/dh/metering-point/feature-search/src/routes.ts

fix(dh): adjustments to measurements

---

apps/dh/e2e-dh/package-lock.json
apps/dh/e2e-dh/package.json

chore(e2e-dh): update dependencies

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Modules/ElectricityMarket/Types/MeasurementPositionDtoType.cs
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day.component.ts
libs/dh/metering-point/feature-overview/src/graphql/get-measurements.graphql
libs/dh/shared/data-access-mocks/src/lib/metering-point.mocks.ts

fix(dh): show circle when data quality has changed

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/create/steps/dh-new-organization-step.component.ts
libs/watt/package/icon/+storybook/storybook-icon-overview.component.html
libs/watt/package/icon/flags/watt-flag-nl.ts
libs/watt/package/icon/flags/watt-flag.ts
libs/watt/package/package.json
libs/watt/package/phone-field/watt-phone-field.component.ts

feat(watt): add Netherlands to phone field

---

libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day-details.component.ts

fix(dh): minor adjustments to measurements

---

libs/eo/certificates/feature-overview/eo-certificates-overview.component.ts

adjust enddate query in frontend

---

libs/eo/certificates/domain/index.ts
libs/eo/certificates/feature-details/eo-certificate-details.component.ts
libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts
libs/eo/core/globalization/assets-localization/i18n/translation-keys.ts
libs/eo/core/globalization/assets-localization/translations.ts

As we now include municipality in the attributes, I've added them to the detail page to showcase it 🙂

Show municipality in certificate details

---

libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-month.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-year.component.ts
libs/watt/package/package.json
libs/watt/package/year-field/watt-year-field.component.ts
libs/watt/package/year-field/watt-year-field.stories.ts
libs/watt/package/yearmonth-field/watt-yearmonth-field.component.ts
libs/watt/package/yearmonth-field/watt-yearmonth-field.stories.ts

fix: minor adjustments to year and yearmonth pickers

---

libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-day.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-month.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-year.component.ts

fix(dh): set sorting on tables in measurements

---

libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/reports/feature-reports/src/routes.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts
libs/dh/shared/util-settlement-reports/src/lib/dh-settlement-report-name.ts

fix(dh): enable new Reports page

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/HealthCheck/HealthCheckFixture.cs
apps/dh/api-dh/source/DataHub.WebApi/Registration/HealthEndpointRegistrationExtensions.cs

The wholesale health checks are broken and currently block our deployment pipeline.
- #0000

fix: remove broken health checks

---

libs/dh/core/routing/src/dhPaths.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurement-reports/.eslintrc.json
libs/dh/reports/feature-measurement-reports/jest.config.ts
libs/dh/reports/feature-measurement-reports/project.json
libs/dh/reports/feature-measurement-reports/src/components/measurement-reports.component.ts
libs/dh/reports/feature-measurement-reports/src/index.ts
libs/dh/reports/feature-measurement-reports/src/test-setup.ts
libs/dh/reports/feature-measurement-reports/tsconfig.json
libs/dh/reports/feature-measurement-reports/tsconfig.lib.json
libs/dh/reports/feature-measurement-reports/tsconfig.spec.json
libs/dh/reports/feature-reports/src/reports.component.ts
libs/dh/reports/feature-reports/src/routes.ts
libs/dh/shared/feature-authorization/src/lib/permission.guard.ts
tsconfig.base.json

feat(dh): add empty Measurement report page

---

apps/dh/api-dh/documents/development.md
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

refac: Remove unused wholesale API

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/reports/feature-reports/src/reports.component.ts
libs/dh/reports/feature-reports/src/routes.ts
libs/dh/shared/domain/src/lib/permission.ts

fix(dh): use permission to protect page

---

libs/dh/core/routing/src/dhPaths.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/core/shell/src/lib/dh-primary-navigation.component.ts
libs/dh/reports/feature-missing-measurements-log/src/lib/request-log.ts
libs/dh/reports/feature-reports/src/routes.ts
libs/dh/wholesale/shared/src/gridareas-dropdown.ts

Enhancements of `request missing measurements log` requested by @MadsBloendAndersen 
- Fix `activeLink` in `reports` section of the primary navigation
- Pre-select all grid areas in the request missing measurements modal
- Go directly to request modal clicking in the navigation until the main page has some content
- Clean-up `DhReportsMissingMeasurementsLogRequestLog` component
- #0000

Enhancements of `request missing measurements log`

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/components/dh-metering-point-details.component.ts

Added to from gridarea fields

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html

fix(dh): display menu group based on permissions

---

libs/eo/certificates/domain/index.ts
libs/eo/certificates/feature-details/eo-certificate-details.component.ts
libs/eo/core/globalization/assets-localization/i18n/da.ts
libs/eo/core/globalization/assets-localization/i18n/en.ts
libs/eo/core/globalization/assets-localization/i18n/translation-keys.ts
libs/eo/core/globalization/assets-localization/translations.ts

add sponsored key to energytags

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/MeasurementsReports/MeasurementsReportsClient.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurement-reports/src/components/measurement-reports.component.ts
libs/dh/reports/feature-measurement-reports/src/components/new-report-request.component.ts
libs/dh/reports/feature-measurement-reports/src/components/overview/overview.component.html
libs/dh/reports/feature-measurement-reports/src/components/overview/overview.component.ts
libs/dh/reports/feature-measurement-reports/src/components/report-status.component.ts
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-as-modal.component.html
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-as-modal.component.ts
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/shared/data-access-graphql/src/index.ts
libs/dh/shared/data-access-graphql/src/lib/graphql/get-actors-by-eic-function-for-dropdowns.ts
libs/dh/shared/data-access-mocks/src/lib/measurements-reports.mocks.ts

feat(dh): initial request measurements report flow

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-missing-measurements-log/src/lib/page.ts
libs/dh/reports/feature-missing-measurements-log/src/lib/request-log-service.ts
libs/dh/reports/feature-missing-measurements-log/src/lib/table.ts
libs/watt/package/data/watt-data-table.component.ts
libs/watt/package/icon/+storybook/storybook-icon-overview.component.ts
libs/watt/package/icon/icons.ts
libs/watt/package/package.json

Minor "UX" adjustments for missing measurements log
Default:
After request has been created:
- #0000

Minor adjustments for missing measurements log

---

libs/eo/certificates/feature-details/eo-certificate-details.component.ts

Changes bidding zone to use actual bidding zone instead of gridarea

ETT GridArea -> BiddingZone

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/MeasurementsReports/Dto/MeasurementsReportMarketRole.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/MeasurementsReports/MeasurementsReportsClient.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurement-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/reports/feature-measurement-reports/src/components/util/start-date-and-end-date-have-same-month.validator.ts
libs/dh/reports/feature-measurement-reports/src/graphql/mutation/request-measurements-report.graphql
libs/dh/shared/data-access-graphql/src/lib/graphql/get-grid-area-options.ts
libs/dh/shared/data-access-mocks/src/lib/measurements-reports.mocks.ts

feat(dh): request measurements report

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/MeasurementsReports/IMeasurementsReportsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/MeasurementsReports/MeasurementsReportsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleMeasurementsReportController.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/MeasurementsReports/MeasurementsReportOperations.cs

fix(dh): implement download and cancel for measurements report in bff

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurement-reports/src/components/overview/overview.component.html
libs/dh/reports/feature-measurement-reports/src/components/overview/overview.component.ts
libs/dh/reports/feature-measurement-reports/src/graphql/query/get-measurements-reports.graphql
libs/dh/shared/data-access-mocks/src/lib/measurements-reports.mocks.ts
libs/dh/shared/domain/src/index.ts
libs/dh/shared/domain/src/lib/dh-measurements-report.ts
libs/dh/shared/util-reports/src/lib/dh-measurements-report-name.ts
libs/dh/shared/util-reports/src/lib/dh-measurements-report-partial.ts
libs/dh/shared/util-reports/src/lib/dh-measurements-reports.service.ts

feat(dh): download measurements report

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Enable Auth on Test-001

---

.gitignore

add Visual Studio cache directory to .gitignore
- #0000

feat: add Visual Studio cache directory to .gitignore

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Reverts Energinet-DataHub/greenforce-frontend#4371

Revert "Enable Auth on Test-001"

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/shared/data-access-mocks/src/lib/release-toggles.mocks.ts

fix(dh): put additional recipients behind release toggle

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Modules/MeasurementsReports/MeasurementsReportOperations.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/MeasurementsReports/Types/RequestMeasurementsReportInput.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts

feat(dh): support for request as in measurements reports

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Modules/MeasurementsReports/MeasurementsReportOperations.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/MeasurementsReports/Types/RequestMeasurementsReportInput.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/measurements-reports.mocks.ts
libs/watt/package/package.json
libs/watt/package/picker/datepicker/watt-datepicker.component.ts

feat(dh): add resolution dropdown to measurements reports

---

libs/dh/metering-point/feature-measurements-csv-parser/src/csv-parser.ts

- Enhance CSV parser to calculate end date based on resolution
- #0000

feat(dh, metering-point): enhance CSV parser to calculate end date

---

bun.lock
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts
libs/watt/package/package.json

fix(dh): layout alignment and max date range validation

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/access-to-measurements-tab/create/metering-point-ids.validator.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/access-to-measurements-tab/create/set-up-access-to-measurements.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/access-to-measurements-tab/overview/metering-point-ids-overview.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/actor-audit-log-tab/dh-actor-audit-log-tab.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/actor-audit-log-tab/dh-actor-audit-log-tab.component.ts
libs/dh/shared/data-access-mocks/src/lib/data/get-actor-audit-logs.ts

fix(dh): adjustments to additional recipients

---

libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurements-reports/src/components/overview/overview.component.html
libs/dh/reports/feature-settlement-reports/src/components/overview/overview.component.html
libs/dh/reports/feature-settlement-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-settlement-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/measurements-reports.mocks.ts

fix(dh): adjustments to measurements reports

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts

fix(dh): hide additional recipient tab from energy supplier

---

libs/dh/metering-point/feature-overview/src/components/can-see/dh-can-see.directive.spec.ts

Don't know why it wasn't caught before...

fix(dh): failing tests after changing to "enumsAsConst"

---

libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/reports/feature-settlement-reports/src/components/request-report/request-report-modal.component.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

- do not reset datepicker when resolution changes to sum of month
- #0000

fix(dh): minor adjustments to reports

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts
libs/watt/package/package.json
libs/watt/package/validators/watt-range.validators.ts

fix(dh): max months validation in measurements reports

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

fix(dh): enable metering points debug in test 001

---

libs/dh/core/routing/src/dhPaths.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-requests/src/index.ts
libs/dh/wholesale/feature-requests/src/lib/page-deprecated.component.ts
libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.routes.ts

fix(dh): move menu items together and deprecate previous wholesale requests location

---

apps/eo/app-eo-landing-page/project.json
apps/eo/app-eo/project.json
libs/eo/legal/assets/service-provider-terms/da.html
libs/eo/legal/assets/service-provider-terms/en.html
libs/eo/legal/assets/terms/da.html
libs/eo/legal/assets/terms/en.html

update the terms

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html

- reorder sub-menu items alphabetically according to the Danish translation
- #0000

fix(dh): reorder sub-menu items alphabetically

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Update the `ProcessManager.Client` to version `6.1.4` to ensure that new SendMeasurements are using the new SendMeasurements Topic.
- #0000

chore: update ProcessManager.Client to 6.1.4

---

apps/dh/e2e-dh/src/support/commands.ts

fix(e2e-dh): uniquely identify a session

---

apps/dh/e2e-dh/cypress-acceptance-tests.config.ts
apps/dh/e2e-dh/cypress.config.ts

fix(e2e-dh): unify e2e config

---

apps/dh/e2e-dh/cypress.config.ts
apps/dh/e2e-dh/package-lock.json
apps/dh/e2e-dh/package.json
apps/dh/e2e-dh/src/e2e/app-shell.cy.ts
apps/dh/e2e-dh/src/e2e/redirect-to-initial-url.cy.ts
apps/dh/e2e-dh/src/support/commands.ts
bun.lock
libs/watt/package/package.json
package.json

fix(e2e-dh): update Cypress and enable tests

---

libs/eo/legal/assets/terms/da.html

Update danish ett terms

---

libs/eo/metering-points/shell/src/lib/eo-metering-point-table.component.ts

https://github.com/user-attachments/assets/3d1d8ae5-ab61-4bd3-af2d-4c7d29cfca7e

Removes square from table

---

bun.lock
libs/watt/package/package.json
package.json

Removes override, that causes weird bug when trying to run apps

Removes dependency override

---

apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleMeasurementsReportController.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleSettlementReportController.cs

Reverts Energinet-DataHub/greenforce-frontend#4561

Revert "feat(dh): add revision log to download report methods"

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Modules/MarketParticipant/MarketParticipant/MarketParticipantOperations.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/MarketParticipant/MarketParticipant/Types/MarketParticipantSortType.cs
libs/dh/market-participant/feature-market-participant/src/components/market-participants.component.ts

Disabled sorting on market roles, because we dont have a way of sorting translated values serverside.

Fixed sorting and search

---

libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.html
libs/dh/reports/feature-measurements-reports/src/components/request-report/request-report-modal.component.ts

fix(dh): show checkbox in measurements reports

---

apps/dh/api-dh/source/DataHub.WebApi/Program.cs

Retrigger merge

---

.github/workflows/dh-cd.yml

fix: change workflow permission

---

libs/watt/package/package.json
libs/watt/package/table/watt-table-data-source.ts

Allow undefined sort and paginator
- [Commit on ](https://github.com/angular/components/commit/9e25efb6f0d1e02e79e537b2252c38ce7f5e34ed)

fix(watt): allow undefined sort and paginator

---

libs/watt/package/icon/+storybook/storybook-icon-overview.component.ts
libs/watt/package/icon/icons.ts
libs/watt/package/package.json

- Added new icons from material icons for use in elo dashboard

feat(watt): add dashboard icons

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Use latest PM client package
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/962

chore: Use latest PM client package

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/globalization/configuration-watt-translation/src/lib/dh-watt-translation.providers.ts
libs/watt/package/code/watt-code-intl.service.ts
libs/watt/package/code/watt-code.component.ts
libs/watt/package/package.json
libs/watt/package/search/watt-search.component.ts

Improve search field

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts
libs/dh/shared/feature-flags/vite.config.mts

- Update latest bump date and fix Vite config for feature flags
- #0000

fix: update latest bump date and fix Vite config for feature flags

---

libs/dh/admin/feature-user-management/src/lib/invite/invite.component.html

fix(dh): call signal in template

---

apps/dh/e2e-dh/package-lock.json

chore(dh): update dependency

---

libs/dh/metering-point/feature-measurements/src/components/month.component.ts
libs/dh/metering-point/feature-measurements/src/components/year.component.ts

fix(dh): check for first item in array

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-move-in/src/components/move-in.component.html
libs/dh/metering-point/feature-move-in/src/components/move-in.component.ts
libs/dh/metering-point/feature-move-in/src/types.ts

fix(dh): minor adjustments to move-in

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Change `B2C` -> `UI` in the documentType translations
- [#1067](https://github.com/Energinet-DataHub/team-mosaic/issues/1067)

Change `B2C` -> `UI` in the documentType translations

---

apps/dh/e2e-dh/src/e2e/app-shell.cy.ts
apps/dh/e2e-dh/src/e2e/language-selection.cy.ts
apps/dh/e2e-dh/src/support/commands.ts
libs/dh/message-archive/feature-search/src/lib/page.component.ts
libs/dh/message-archive/feature-search/src/lib/start.component.ts

Auto open search modal at `message-archive`
- [#1067](https://github.com/Energinet-DataHub/team-mosaic/issues/1067)

Auto open search modal at `message-archive`

---

libs/dh/metering-point/feature-move-in/src/components/move-in.component.ts
libs/dh/metering-point/feature-move-in/src/types.ts

- enable/disable CPR 2 field if Name 2 contains a value
- #0000

fix(dh): adjustments to move-in

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-move-in/src/components/customer-details.component.ts
libs/dh/metering-point/feature-move-in/src/components/move-in.component.ts
libs/dh/shared/ui-validators/src/lib/dh-cpr.validator.spec.ts
libs/dh/shared/ui-validators/src/lib/dh-cpr.validator.ts

fix(dh): add cpr validator to move-in

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-move-in/src/components/customer-details.component.ts
libs/dh/metering-point/feature-move-in/src/components/move-in.component.ts

feat(dh): add cvr validation to input field

---

apps/dh/e2e-dh/package-lock.json
apps/dh/e2e-dh/package.json

chore(e2e-dh): update dependency

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Modules/ElectricityMarket/MeteringPointNode.cs
libs/dh/metering-point/feature-overview/src/components/dh-metering-point.component.ts
libs/dh/metering-point/feature-overview/src/graphql/get-metering-point-by-id.graphql
libs/dh/metering-point/feature-search/src/components/dh-search.component.ts
libs/dh/metering-point/feature-search/src/graphql/metering-point-exists.graphql
libs/dh/metering-point/feature-upload-measurements/src/graphql/get-metering-point-upload-metadata-by-id.graphql
libs/dh/metering-point/feature-upload-measurements/src/upload-page.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

fix(dh): remove new security model flag
