.github/PULL_REQUEST_TEMPLATE.md

Correct CLA URL in pull request template.
N/A

chore: correct CLA URL in pull request template

---

angular.json
apps/dh3-admin/.eslintrc.json
apps/dh3-admin/src/app/app.component.ts
apps/dh3-admin/src/index.html
nx.json

* Change prefix for DataHub project 
* Change NX default base branch
-#

Change prefix for DataHub project

---

apps/dh3-admin/src/index.html
documentation.json
libs/ui-watt/src/lib/foundations/box-sizing.scss
libs/ui-watt/src/lib/foundations/typography/storybook/shared/typography-html-snippets.ts
libs/ui-watt/src/lib/foundations/typography/storybook/typography.component.html
libs/ui-watt/src/lib/foundations/typography/storybook/typography.component.ts
libs/ui-watt/src/lib/foundations/typography/storybook/typography.stories.ts
libs/ui-watt/src/lib/watt.scss

Adjust typography examples in Storybook
#9

Adjust typography examples in Storybook

---

.github/actions/affected/action.yml
.github/actions/affected/affected.mjs
.github/workflows/ett.yml
apps/ett-app/src/app/energy-track-and-trace-app.component.ts

- Fix affected action output.
- Fix affected action on merge runs.

ci(ett): fix affected action on merge runs

---

.github/workflows/ett.yml

ci(ett): remove debugging job

---

.github/workflows/workspace.yml
nx.json

Change tokens for nx cloud to be read-only in nx.json and read-write for our CI

chore: update tokens for nx cloud

---

.github/workflows/api-dh-app-ci.yml
.github/workflows/design-system-cd.yml
.github/workflows/ett.yml
.github/workflows/workspace.yml
README.md
libs/api-dh-app/documents/development.md
libs/api-dh-app/source/DataHub.WebApi.Tests/Integration/Controllers/WeatherForecastControllerTests.cs
libs/api-dh-app/source/DataHub.WebApi/Controllers/WeatherForecastController.cs
libs/api-dh-app/source/DataHub.WebApi/Program.cs
libs/api-dh-app/source/DataHub.WebApi/Startup.cs
libs/api-dh-app/source/DataHub.WebApi/WeatherForecast.cs

- Updated development.md to mention CI build
- Established an initial BFF CI using a shared workflow.
https://app.zenhub.com/workspaces/mighty-ducks-60ae1565be2dfe0017ff66b2/issues/energinet-datahub/mightyducks/158

Establish initial BFF CI

---

libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.html
libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.html
libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.ts
libs/ui-watt/src/lib/components/button/watt-button.module.ts
libs/ui-watt/src/lib/components/button/watt-button.stories.ts
libs/ui-watt/src/lib/components/spinner/spinner.component.html

- Support loading state in button component
- Adjust size of spinner component
- Adjust styling for text button 
- Reduce the number of stories and use controls to set individual properties
- https://github.com/Energinet-DataHub/MightyDucks/issues/215

feat(watt): support loading state in button component

---

README.md
libs/dh/core/shell/src/lib/shell/shell.component.html
libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.scss
libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.ts
libs/ui-watt/src/lib/components/shell/shell.component.html
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.ts
libs/ui-watt/src/lib/components/shell/shell.module.ts
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/ui-watt/src/lib/foundations/icon/icons.ts

- Style Shell component according to Figma (sidebar, toolbar)
- Add padding to main content
- Make Shell component responsive
- https://github.com/Energinet-DataHub/MightyDucks/issues/215

feat(watt): styling of shell component

---

libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/form-field/form-field.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.html
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon.stories.ts
libs/ui-watt/src/lib/foundations/icon/_watt-icon-variables.scss
libs/ui-watt/src/lib/foundations/icon/icon.component.scss

- Change the default icon size from 16px to 24px
- Remove margin from prefix/suffix element in input
- Add space between icon and text in button component
- https://github.com/Energinet-DataHub/MightyDucks/issues/215

feat(watt): change the default icon size

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Add translation keys for search metering point
- #0000

feat(dh): add translation keys for search metering point

---

libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.html
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.ts

refactor(watt): add prefix to classes

---

.eslintrc.json
package.json
yarn.lock

Configures the NgRx ESLint plugin specific for component-store.
- #0000

style: configure ESLint plugin:ngrx/component-store-strict

---

README.md

Document the `ACTIONS_BOT_SSH_KEY` repository secret.
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/137

docs: document `ACTIONS_BOT_SSH_KEY` secret

---

infrastructure/eo/chart/values.yaml

Changed chart structure to use dictionary.

changed chart structure to dictionary

---

.github/workflows/ett.yml

Update host container image path after #164 renamed a folder without updating the `ett.yml` workflow.
- #164

ci(ett): correct host container image path

---

infrastructure/eo/chart/Chart.yaml

updated base chart to 0.3.4

---

infrastructure/eo/chart/Chart.yaml

Bumped basechart to fix TLS error

bumped basechart

---

.github/workflows/api-dh-cd.yml

fix name of app service

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/ChargeLinksControllerTests.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/ChargeLinksController.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Startup.cs

The `Energinet.DataHub.Charges.Clients` package used in the BFF had a deserializing issue which has been [fixed](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md) in v `1.0.18`
This PR brings the BFF up to the latest versions of
* `Energinet.DataHub.Charges.Clients` 
* `Energinet.DataHub.Charges.Clients.Registration` 
- https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/792

Update packages `Energinet.DataHub.Charges.Clients` and `.Registration` - Fix deserializing issue for `ChargeLinkDto`

---

apps/dh/app-dh/src/index.html

chore(dh): update app title

---

.github/workflows/dh-infrastructure-cd.yml

Does what it says in the title👆

change metering point api endpoint

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

fix(dh): use correct translations

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/data-access-api/src/lib/generated/v1/model/charge-link-dto.ts

- Update Charges Client to `v1.0.20`
- #976

update charges client to 1.0.20

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/data-access-api/src/lib/generated/v1/model/charge-link-dto.ts

As a better solution for handling null values in auto generated typescript files is made in #210 the charges client is updated to revert back to record and package version is updated to latest build.
- #976

update charges client to version 1.0.21

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Change unit translation for both Danish and English
- #544

Refactor translation for units

---

libs/dh/metering-point/data-access-api/src/lib/dh-metering-point-data-access-api.store.ts

- Merge multiple properties into one in metering point data access store
- N/A

refactor(dh): simplify metering point data access store

---

libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.html

correction for isloading
- #226

Reorder isloading

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Vi har ønske til ovenstående ændringer. Vil I kigge på dem?
Mvh DNI og MKB
- #0000

Update til den danske version.

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

Produkter ændret fra engelsk til dansk.
- #0000

Update til den danske version

---

.github/workflows/design-system-ci.yml
.github/workflows/dh-ci.yml

add temp workflows

---

.github/actions/publish-release-content/action.yml

added publish-release-content action

---

libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Rettet efter begreberne i RSM guiden
- #0000

Update til den engelske version

---

.github/actions/publish-release-contents/action.yml

extend publish-release-contents action

---

.github/actions/publish-release-contents/action.yml

removed app from create-release-content

---

libs/ui-watt/src/lib/components/tabs/tabs.component.html

Added dynamic tab height to allow transitioning between different tab heights
https://user-images.githubusercontent.com/22943367/148401627-a620a29f-1891-4a13-9bd1-0563cdb644cd.mp4
- #548

Fix for visible scroll bar when switching between tabs

---

.github/actions/publish-release-contents/action.yml

rename webapi to bff

---

libs/dh/metering-point/feature-overview/src/lib/charges/dh-charge-item/dh-charge-item.component.scss
libs/dh/metering-point/feature-overview/src/lib/child-metering-point-tab-content/dh-child-metering-point-tab-content.component.scss
libs/ui-watt/src/lib/foundations/_table.scss

Moved the table styling into _table.scss in the design system.
Also added a minor tweak to the padding of cells in the charges table.
- #542

Make table styling global

---

libs/dh/metering-point/feature-overview/src/lib/breadcrumb/dh-breadcrumb.component.html
libs/dh/metering-point/feature-overview/src/lib/breadcrumb/dh-breadcrumb.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.html
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/identity/dh-metering-point-identity.component.html
libs/dh/metering-point/feature-overview/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.html
libs/dh/metering-point/feature-overview/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/secondary-master-data/dh-secondary-master-data.component.html
libs/dh/metering-point/feature-overview/src/lib/secondary-master-data/dh-secondary-master-data.component.ts
libs/dh/metering-point/feature-overview/src/lib/shared/dh-em-dash-fallback.pipe.ts
libs/dh/metering-point/feature-overview/src/lib/shared/dh-is-parent.pipe.ts
libs/dh/metering-point/feature-overview/src/lib/shared/dh-show-for-metering-point-type.directive.ts
libs/dh/metering-point/feature-overview/src/lib/shared/dh-yes-no.pipe.spec.ts
libs/dh/metering-point/feature-overview/src/lib/shared/dh-yes-no.pipe.ts
libs/dh/metering-point/feature-overview/src/lib/shared/em-dash.spec.ts
libs/dh/metering-point/feature-overview/src/lib/shared/metering-point-type-map.ts

- Rename pipes to be under `dh` namespace
- Rename type
- https://github.com/Energinet-DataHub/geh-metering-point/issues/580

feat(dh): rename pipes

---

.github/workflows/app-dh-cd.yml

added depedndency to is_affected

---

.github/workflows/dh-backend-cd.yml

fixed path trigger on dh-backend-cd

---

.github/workflows/frontend-ci.yml
sonar-project.properties

Add Sonar Cloud to DH3 Frontend App

Add sonarcloud to dh frontend app

---

build/ci/dh/api-dh/ci.appsettings.Development.json
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.spec.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point-search.component.spec.ts
libs/dh/shared/data-access-api/src/lib/metering-point-api-v1.spec.ts

- Test against U-001 environment in CI pipeline
- Adjust tests to use GSRN number from U-001
- https://github.com/Energinet-DataHub/geh-metering-point/issues/624

test(dh): fix failing integration tests

---

package.json

Fix security vulnerability: 
https://github.com/Energinet-DataHub/greenforce-frontend/security/dependabot/yarn.lock/trim/closed
https://github.com/storybookjs/storybook/issues/14603

chore: add resolution of trim

---

build/infrastructure/dh/env/b-002/ui-app-custom-domain.tf

Purpose of PR is to make sure both CI and CD pipelines are triggered.

Rename custom domain resource in B002 

---

package.json
yarn.lock

update `@ngneat/transloco-keys-manager` to fix security vulnerability: 
https://github.com/ngneat/transloco-keys-manager/issues/123
https://github.com/Energinet-DataHub/greenforce-frontend/security/dependabot/yarn.lock/nth-check/closed

chore: update @ngneat/transloco-keys-manager

---

libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/ui-watt/src/lib/foundations/icon/icons.ts

- Add `openInNew` icon
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/294

feat(watt): add "open in new" icon

---

libs/dh/shared/assets/src/assets/login-page/login-unified.html

add sign up link to login page
Can be tested on every environment:
https://github.com/Energinet-DataHub/green-force-art/blob/main/wiki/datahub/environments/signup-and-signin-to-datahub-app.md
[#569](https://github.com/Energinet-DataHub/geh-aggregations/issues/569)

add sign up link to login page

---

libs/dh/auth/feature-msal/src/lib/b2c-config.ts

Handle cancelling of signup flow by reloading the page, to get the application / b2c instance in fresh state to ensure the user is redirected back to the login page. 
https://github.com/Energinet-DataHub/geh-aggregations/issues/575

fix(dh): handle cancelling of signup flow

---

libs/eo/landing-page/shell/src/lib/eo-landing-page-footer.component.ts

- Fixes incorrect CVR number and phone number in the footer of the landing page.

Update to CVR and phone number in landing page footer

---

libs/ui-watt/src/index.ts
libs/ui-watt/src/lib/components/validation-message/index.ts
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.component.html
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.component.scss
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.component.ts
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.module.spec.ts
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.module.ts
libs/ui-watt/src/lib/components/validation-message/watt-validation-message.stories.ts
libs/ui-watt/src/lib/foundations/typography/+storybook/storybook-typography-overview.component.html

- Add `watt-validation-message` component
- Showcase and document component in Storybook
**Note**: The text color is set to primary because setting the text to a state color on light state color background doesn't have enough contrast to meet the accessibility standards.
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/293

feat(watt): add validation message component

---

apps/dh/app-dh/project.json
libs/dh/core/shell/src/lib/dh-core-shell.module.ts
libs/dh/metering-point/shell/src/index.ts

- Import route path from route library
- Adjust initial bundle size budget to 1.1 Mb
- #341

fix(dh): fix lazy-loading of metering point route

---

libs/ui-watt/src/lib/components/shell/shell.stories.ts

- Perform initial navigation during app initialization
- Remove `useHash` location strategy
- #142

refactor(storybook): minor adjustments to shell story

---

libs/ett/auth/data-access-api/src/lib/auth-http.service.spec.ts
libs/ett/auth/data-access-api/src/lib/auth-http.service.ts
libs/ui-watt/src/lib/components/shell/shell.stories.ts

- Fixed logout where body was set instead of options.
- https://github.com/Energinet-DataHub/energy-origin/issues/370

EO Fix logout 

---

.github/workflows/ett.yml
apps/ett/app-ett/src/index.html
infrastructure/eo/chart/Chart.yaml
infrastructure/eo/chart/values.yaml

- docs: Non-functional change to trigger deployment of Energy Origin app
- ci: Revert chart folder path
- https://github.com/Energinet-DataHub/energy-origin/issues/313

ci(eo): fix release flow

---

.github/workflows/ett.yml

Only run version check if is-affected is true.

Updated workflow to check is-affected

---

apps/dh/app-dh/project.json
libs/dh/shared/data-access-msw/src/lib/handlers.ts

fix(dh): allow js deps for msw and ignore file exts

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

adding message-archive side bar menu item

---

libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list.component.spec.ts

chore(watt): fix lint error

---

.github/workflows/app-dh-cd.yml
.github/workflows/app-dh-healthchecks.yml
.github/workflows/dh-backend-ci.yml
apps/dh/api-dh/project.json
apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
build/infrastructure/dh/main/app-bff.tf
global.json
libs/dh/shared/domain/src/lib/generated/v1/model/address-dto.ts
libs/dh/shared/domain/src/lib/generated/v1/model/change-organization-dto.ts
libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
libs/dh/shared/domain/src/lib/generated/v1/model/organization-dto.ts
libs/dh/shared/domain/src/lib/generated/v1/model/stream.ts

Update workflows, TF files and c# projects to use .NET 6
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/3

Update to .NET 6

---

infrastructure/eo/chart/Chart.yaml
infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/time-range-input/watt-time-range-input.component.ts

- update placeholder based on feedback from UX
- #418

feat(watt): update placeholder for time-range component

---

.github/workflows/dh-backend-ci.yml
build/infrastructure/dh/main/app-bff.tf
build/infrastructure/dh/main/kv-shared.tf

Change App Service Plan to Windows and enable metric alerts.
Use module for app service.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/267

Update infrastructure to use latest TF modules 

---

build/infrastructure/dh/main/app-bff.tf

Scale BFF App Service Plan to use a Production plan, as it currently uses a DEV/TEST B1 plan.

Use PremiumV2 P1v2

---

libs/dh/charges/data-access-api/src/lib/dh-charges-data-access-api.store.ts
libs/dh/metering-point/data-access-api/src/lib/dh-metering-point-data-access-api.store.ts
libs/dh/metering-point/data-access-api/src/lib/dh-processes-data-access-api.store.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/dh/metering-point/feature-tabs/src/lib/charges-tab-content/dh-charges-tab-content.component.ts
libs/dh/metering-point/feature-tabs/src/lib/processes-tab-content/dh-processes-tab-content.component.ts

- refactor sending of route param is sent to NgRx Component Store effect
- N/A

refactor(dh): simplify sending of route param to NgRx effect

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/shared/domain/src/lib/generated/v1/model/message-archive-search-result-item-dto.ts

message archive client upgrade to version 1.5.0
- #0000

message archive client upgrade150

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-datetime/danish-datetime.module.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/characters.spec.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/characters.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale-code.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale.initializer.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale.integration.spec.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale.module.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale.provider.spec.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/danish-locale/danish-locale.provider.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/storybook-configuration-localization.module.ts
libs/ui-watt/src/lib/components/input/+storybook/configuration-localization/test-util/space-to-non-breaking-space.ts
libs/ui-watt/src/lib/components/input/date-range-input/+storybook/date-range-input-reactive-forms.stories.ts
libs/ui-watt/src/lib/components/input/date-range-input/+storybook/date-range-input-template-driven-forms.stories.ts
libs/ui-watt/src/lib/components/input/time-range-input/+storybook/storybook-time-range-input-reactive-forms.stories.ts
libs/ui-watt/src/lib/components/input/time-range-input/+storybook/storybook-time-range-input-template-driven-forms.stories.ts

Add storybook localization configuration module to avoid imports from watt -> dh

feat(ui-watt): add storybook localization configuration module

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.html
libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts
libs/dh/shared/domain/src/lib/generated/v1/model/message-archive-search-criteria.ts

rsm processtype multiselect search
- #0000

rsm processtype multiselect search

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.module.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.spec.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

Adding metering points to metering page through the API call related to this
- https://github.com/Energinet-DataHub/energy-origin-issues/issues/232

Add metering point API call to metering points page

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list.component.scss

- use correct color variable in `watt-nav-list` component
- N/A

refactor(watt): use correct color variable in watt-nav-list component

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

eo(ci): bump project version

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/message-archive/feature-log-search/src/lib/blobcontent/dh-message-archive-log-search-blob-content.component.html
libs/dh/message-archive/feature-log-search/src/lib/blobcontent/dh-message-archive-log-search-blob-content.component.scss
libs/dh/message-archive/feature-log-search/src/lib/blobcontent/dh-message-archive-log-search-blob-content.component.ts
libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts

adding traceid to show on log page
- #0000

adding traceid to show on log page

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list.component.scss
libs/ui-watt/src/lib/foundations/_variables.scss
libs/ui-watt/src/lib/foundations/typography/+storybook/shared/typography-html-snippets.ts
libs/ui-watt/src/lib/foundations/typography/+storybook/storybook-typography-overview.component.html
libs/ui-watt/src/lib/foundations/typography/_typography.import.scss
libs/ui-watt/src/lib/foundations/typography/index.scss

This adds the text emphasis part to Storybook and exposes variables for use in apps
https://app.zenhub.com/workspaces/fenris---team-board-20-616bc40121d71900140955f8/issues/energinet-datahub/greenforce-frontend/357

(design) Text colors and emphasis

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list.component.scss

Removing the line from this PR made DH project get black text in menu. This needs to be investigated at some point, but for now we fix it by putting the color back in.

BUG: Reinstate white menu text color

---

build/infrastructure/dh/main/apima-bff.tf

Trace caller id in application insights by logging it from API Management.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/270

Trace caller id in application insights

---

.github/workflows/eo-cd.yml
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.spec.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.ts

This adds testing to the CD flow of EO

Add tests to flow for EO

---

.github/workflows/eo-cd.yml
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.spec.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.ts

Reverts Energinet-DataHub/greenforce-frontend#497

Revert "Add tests to flow for EO"

---

.github/workflows/eo-cd.yml

This adds concurrency to the workflow of EO, as well as implements checking E2E and unit tests if any build-related files have changed

Add concurrency and tests to workflow

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

bump EO trying fix main

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/shell.stories.ts

- use correct property for link in Storybook
- N/A

fix(watt): use correct property for link in Storybook

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/ui-watt/src/lib/foundations/icon/icons.ts

Implement the save_alt icon from Material Design

(Watt) Implement save_alt icon from Material

---

.github/workflows/app-dh-cd.yml
.github/workflows/design-system-cd.yml
.github/workflows/design-system-infrastructure-cd.yml
.github/workflows/dh-backend-cd.yml
.github/workflows/dh-backend-ci.yml
.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml
.github/workflows/license-check-ci.yml

This adds concurrency to all actions, and makes them cancel the jobs if a PR has commits added quickly after each other

Add concurrency to actions

---

apps/eo/e2e-eo/src/support/landing-page.po.ts
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/landing-page/shell/src/lib/eo-landing-page-call-to-action.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-company.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-header.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-hero.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-introduction.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-login-button.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-origin-of-energy.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-shell.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-shell.module.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-store.spec.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page.presenter.ts
libs/eo/landing-page/shell/src/lib/eo-landinge-page-audience.component.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/atomic-design/ui-organisms/src/lib/header/eo-header.component.ts

This replaces the buttons on the landing page with watt-button

Replace buttons on landing page with watt-button

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/index.ts
libs/ui-watt/src/lib/components/chips/index.ts
libs/ui-watt/src/lib/components/chips/watt-chips.component.html
libs/ui-watt/src/lib/components/chips/watt-chips.component.scss
libs/ui-watt/src/lib/components/chips/watt-chips.component.spec.ts
libs/ui-watt/src/lib/components/chips/watt-chips.component.ts
libs/ui-watt/src/lib/components/chips/watt-chips.module.ts
libs/ui-watt/src/lib/components/chips/watt-chips.stories.ts
libs/ui-watt/src/lib/styles/@energinet-datahub/watt/theme/light-theme.scss

Simple implementation of chips, covering only the "choice chips variant". 
- #487

feat(ui-watt): add chips component

---

workspace.json

- add project to workspace file
- N/A

fix(dh): add project to workspace file

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-tips.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-global-goals-media.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-hourly-declaration.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-renewable-energy.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts

This PR makes it possible to send [data] as an input to pie chart to control data visualization.

Make pie chart data controlable via input

---

build/infrastructure/dh/env/b-002/apima-bff_override.tf
build/infrastructure/dh/main/apima-bff.tf

APIM BFF policy: move base and fix environment override

APIM BFF move base and fix environment override

---

apps/dh/e2e-dh/src/integration/b2c.spec.ts

Fix healthchecks of dh to correspond with the new URL of U-002 and add itlev environment 
- #506

fix(e2e-dh): adjust b2c healthchecks

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.store.ts

This implements a preliminary API call for data to the pie chart of "origin of energy"

feature/implement API call for pie chart

---

.github/CODEOWNERS

chore: adjust codeowners not to include EO infrastructure

---

docs/getting-started.md

- update "Getting started" guide to describe how to generate HttpClient and DTOs
- N/A

docs: update getting started guide

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/domain/src/lib/generated/v1/model/asset-type.ts

Upgraded MP client version to 3.0.1 - Update to .NET 6 and added AssetType value
- https://github.com/Energinet-DataHub/geh-market-roles/issues/1034

Updated MP client to latest version

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

Make sure emissions number updates on receiving it

Push data for updating emissions

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-shell.component.ts

- Fixed a small bug where the landing page would show cookie banner after refresh
- Added a loading spinner for when emissions is being fetched

Small bugfix of cookie banner and emissions loader

---

apps/eo/app-eo/src/index.html
apps/eo/app-eo/src/main.ts
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

Integrate HOTJAR into EO, so user activity is tracked

Integrate hotjar to EO

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-privacy-policy/eo-privacy-policy.component.ts

This PR adds styling to the privacy policy page to make the backend returned HTML prettified.

Styling for privacy policy

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.spec.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts

Changes to emissions and meteringpoints API

Changes to emissions and meteringpoints API

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts

Bugfixing before it becomes an issue, to check for null or NaN in API response

Correct for NaN

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts

Backend API for origin of energy changed. This change is to reflect that.

Change origin of energy api

---

apps/eo/app-eo/project.json
apps/eo/app-eo/src/index.html
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/assets/src/scripts/hotjar.js

Move Hotjar implementation out of inline scripting to avoid CSP security issues.

Move hotjar out of inline scripting

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
build/infrastructure/eo/host/nginx.conf

Allow *.hotjar.io into connect-src

Integrate new Url to connect-src

---

libs/dh/market-participant/feature-organization/src/lib/overview/dh-market-participant-organization-overview.component.html

missing rename

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-shell.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-shell.module.ts
libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
libs/eo/emissions/shell/src/lib/eo-emissions.store.ts
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.spec.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.service.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.module.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.store.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

Enabling component store caching for
- Metering points
- Origin of Energy
- Emissions

Component store implementation

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/auth/feature-terms/src/lib/eo-auth-feature-terms.component.ts
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-scroll-view/eo-scroll-view.component.ts

Setting a height for terms page content for easier access to buttons

Set new terms height

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/faq/shell/src/lib/eo-faq-shell.component.ts

This updates the link to Origins of Energy on Energinets website

Update link to Origins of Energy

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

This PR implements addresses for metering points

Metering points address

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts

Small bugfixes to:
- Remove decimals from the pie chart
- Add type filtering for metering points

Remove decimals from pie chart and put type on metering points

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
package.json
yarn.lock

- update Cypress to latest v9
- bump project version for Energy Origin 
- #563

chore: update Cypress to latest v9

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
build/infrastructure/eo/host/nginx.conf
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions.store.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.store.ts

Adding hotjar button, and making quality of life changes to store API calls on error

Add hotjar survey button

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/consumption-page/shell/src/lib/eo-consumption-chart-card.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-info.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-shell.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-notification.component.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-line-chart/eo-line-chart.component.ts

Small batch of visual and functional updates before demo

Small batch of visual updates

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/auth/feature-terms/src/lib/eo-auth-feature-terms.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-chart-card.component.ts
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-privacy-policy/eo-privacy-policy.component.ts
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-line-chart/eo-line-chart.component.ts
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-scroll-view/eo-scroll-view.component.ts

Fixes the showing of data on consumption chart, and removes privacy policy version from being shown

Comsumption chart fix

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/modal/watt-modal.component.html
libs/ui-watt/src/lib/components/modal/watt-modal.component.scss
libs/ui-watt/src/lib/components/modal/watt-modal.component.spec.ts
libs/ui-watt/src/lib/components/modal/watt-modal.component.ts
libs/ui-watt/src/lib/components/modal/watt-modal.module.ts
libs/ui-watt/src/lib/components/modal/watt-modal.stories.ts

feat(ui-watt): modal configuration

---

libs/dh/shared/feature-flags/src/index.ts
libs/dh/shared/feature-flags/src/lib/feature-flag.directive.spec.ts
libs/dh/shared/feature-flags/src/lib/feature-flag.directive.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.service.ts
libs/dh/shared/feature-flags/src/test-setup.ts

Add feature flag directive which is based on the feature flags configuration and service. 
- #409

feat(dh): add feature flag directive

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.scss

The datepicker had too much spacing at the top and too little at the bottom.
**Before:**
**After:**

fix(ui-watt): adjust whitespace in datepicker

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-shell.component.ts
libs/eo/privacy-policy/routing/project.json
libs/eo/shared/atomic-design/ui-organisms/src/lib/footer/eo-footer.component.spec.ts
libs/eo/shared/atomic-design/ui-organisms/src/lib/footer/eo-footer.component.ts

This implements a footer link to our new accesssibility statement

Implement accessibility link

---

apps/dh/app-dh/project.json

- replace `load-dh-app-environment` in prod build
- remove unnecessary `.gitkeep` files
- #393

feat(dh): replace `load-dh-app-environment` in prod build

---

.github/workflows/app-dh-cd.yml
.github/workflows/design-system-cd.yml
.github/workflows/dh-backend-ci.yml
.github/workflows/frontend-ci.yml
.github/workflows/license-check-ci.yml
apps/dh/api-dh/project.json
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/README.md

- various minor adjustments
- N/A

chore: minor adjustments

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Startup.cs

Register service for Application Insights telemetry.

Add App Insights telemetry service

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/+storybook/watt-drawer.stories.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.spec.ts

test(ui-watt): add specs for drawer

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/+storybook/watt-drawer.stories.ts

docs(ui-watt): fine-tune code example of the drawer

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/+storybook/watt-drawer.stories.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer-top-bar.directive.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.html
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.spec.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.module.ts

- add support for top bar in drawer component
- bump project version
- #698

feat(watt): add support for top bar in drawer component

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/landing-page/shell/src/lib/eo-landing-page-introduction.component.ts

This fixes the link to "read more about" on the landing page

Fix landing page link

---

.github/workflows/design-system-infrastructure-cd.yml

Align TF versions for Design System deployment

Align TF versions

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/faq/shell/src/lib/eo-faq-shell.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts

Adding responsiveness to the FAQ page

FAQ small screen

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json
libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.html
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.ts

- Add close on click of router links
- Make it wider to support having "close" button inside
- Make the menu burger button smaller to fit mobile theme
- Changes should only hit on screen smaller than LARGE size

Make watt nav mobile friendly

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-core-shell.module.ts
libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts

Rename Origin of Energy page to Renewable Share

Rename Origin of energy page

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
libs/eo/shared/assets/src/assets/configuration/eo-api-environment.local.json

This adds a tag to the metering points list for each metering point, whether they are production or consumption

Add tag to metering point

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts

Instead of filtering metering points, just show all of them

Show all metering points

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/shell.component.ts

- close sidenav on navigation
- N/A

refactor(ui-watt): close sidenav on navigation

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/shell.stories.ts

- fix shell component in Storybook
- N/A

fix(ui-watt): fix shell component in Storybook

---

docs/dh/logging.md
libs/dh/shared/util-application-insights/src/lib/dh-application-insights.service.ts
libs/dh/shared/util-application-insights/src/lib/dh-shared-util-application-insights.module.spec.ts
libs/dh/shared/util-application-insights/src/lib/dh-shared-util-application-insights.module.ts

- send uncaught errors to Application Insights
- document how to find exceptions in Application Insights
- #762

feat(dh): implement global error handler 

---

apps/dh/app-dh/project.json

Generate source maps of `app-dh` for production build so that it can be uploaded by CD to a storage account, Application Insights can point at. 
Creation of the storage accounts, changes to CD and configuration of the application insights instances has been created as an task for The Outlaws (see dependency of the referenced issue).
- #765

Source maps for app-dh

---

README.md
tools/generators/dh-library-generator/files/configuration/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/domain/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/e2e-util/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/environments/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/routing/constant/dh-__domain__-path.ts__tmpl__
tools/generators/dh-library-generator/files/routing/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/test-util/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/ui/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/files/util/test-setup/test-setup.ts__tmpl__
tools/generators/dh-library-generator/index.ts
tools/generators/dh-library-generator/schema.json
tools/tsconfig.tools.json

This adds generators for the remaining library types. 
Closes #722

feat(dh): library generator part 2

---

.github/actions/publish-release-contents/action.yml

fixed bugs in cicd

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
package.json
yarn.lock

- update dependency to resolve a security vulnerability
- N/A

chore: update dependency

---

apps/eo/app-eo/project.json
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-shell.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption.store.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-shell.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions.store.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.store.ts
libs/eo/production/shell/src/lib/eo-production-shell.component.ts
libs/eo/production/shell/src/lib/eo-production-tip.component.ts
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts

This puts error message popups on pages after login

Error messages on pages

---

apps/dh/app-dh/project.json
apps/dh/app-dh/staticwebapp.config.json

Add `staticwebapp.config.json` for DataHub to enable CORS configuration.
[403](https://github.com/Energinet-DataHub/the-outlaws/issues/403)

chore(dh): add CORS configuration

---

apps/dh/app-dh/staticwebapp.config.json

chore(dh): change PUT -> OPTIONS

---

.github/workflows/dh-backend-cd.yml
.github/workflows/dh-backend-ci.yml
.github/workflows/dh-frontend-cd.yml
.github/workflows/watt-backend-cd.yml
.github/workflows/watt-backend-ci.yml
.github/workflows/watt-frontend-cd.yml

Use v8 tag for reusable workflows/actions
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/479

Use v8 tag for reusable workflows/actions

---

build/infrastructure/dh/env/b-002/apima-bff_override.tf
build/infrastructure/dh/main/apima-bff.tf

Rename Correlation-ID header to CorrelationId.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/440

Rename correlation id header

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/metering-point/feature-search/src/lib/form/dh-metering-point-search-form.component.scss
libs/ui-watt/src/lib/components/form-field/form-field.component.scss

- fix alignment issue with input label
- fix alignment issue with form button
- bump project version
- N/A

fix(ui-watt): fix alignment issue with input label

---

build/infrastructure/dh/main/apima-bff.tf
build/infrastructure/dh/main/app-bff.tf
build/infrastructure/dh/main/kv-shared-access-policies.tf
build/infrastructure/dh/main/kv-shared.tf
build/infrastructure/dh/main/st-source-maps.tf
build/infrastructure/dh/main/ui-app.tf

added sourcemaps storage for DH app

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-date-picker/eo-date-picker-dialog.component.ts

Fixed a bug where we couldn't pick the same date for start and end

Fix calender pick on same date

---

libs/dh/core/shell/src/lib/dh-core-shell.component.ts

Add track exceptions to shell component to see these in application insights
- #0000

Test application insights sourcemaps

---

.github/workflows/eo-cd.yml
libs/eo/shared/styles/src/lib/@energinet-datahub/eo/shared/styles/generic/_generic-normalize.scss

Fix code smells

---

.github/workflows/eo-cd.yml

EO pipeline

---

.github/workflows/eo-cd.yml

Only run EO build in master, if affected

Only run EO if affected

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/market-participant/feature-gridarea/src/lib/overview/dh-market-participant-gridarea-overview.component.html

gridarea list header

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/feature-gridarea/src/lib/details-header/dh-market-participant-gridarea-details-header.component.html
libs/dh/market-participant/feature-gridarea/src/lib/details-header/dh-market-participant-gridarea-details-header.component.scss
libs/dh/market-participant/feature-gridarea/src/lib/details-header/dh-market-participant-gridarea-details-header.component.ts
libs/dh/market-participant/feature-gridarea/src/lib/overview/dh-market-participant-gridarea-overview.component.html

Co-authored-by: KarstenM <xnetsrak@gmail.com>
Co-authored-by: Jesper Justesen <juj@energinet.dk>

feat: grid area details header section

---

.github/workflows/eo-cd.yml

- revert changes to Energy Origin pipeline
- N/A

revert: revert EO pipeline changes

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- group "Settlements" menu items into an expandable group
- #807

feat(dh): group settlements menu items

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list.component.scss

- adjust hover styling in sidebar menu
- bump project version
- #807

feat(ui-watt): adjust hover styling in sidebar menu

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.store.ts
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-pie-chart/eo-pie-chart.component.ts

Show "No data available, try another date" text on origin of energy pie charts if they are empty of data after loading

Show no data text on pie chart

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-pie-chart/eo-pie-chart.component.ts

Set background depending on amount of data incoming

Fix background color for pie chart

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/globalization/feature-language-picker/src/lib/language-button/dh-language-button.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.scss

- adjust language toggle buttons height 
- set top bar height to 4rem
- bump project version
- #816

feat: adjust top bar height 

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/shared/data-access-msw/src/assets/mockServiceWorker.js
package.json

- update Mock Service Worker script to get rid of console error
- N/A

chore: update Mock Service Worker script

---

libs/dh/core/shell/src/lib/dh-core-shell.component.html
libs/dh/core/shell/src/lib/dh-core-shell.component.scss

- remove DataHub logo from top bar
- #816

feat(dh): remove DataHub logo from top bar

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

This PR bumps the charges packages. 
The .Clients package contains a URL fix.
https://github.com/Energinet-DataHub/geh-charges/issues/1123

Bump: `Energinet.DataHub.Charges.Clients` and `Energinet.DataHub.Charges.Clients.Registration` to `3.0.13`

---

libs/dh/core/shell/src/lib/dh-core-shell.component.spec.ts
libs/dh/core/shell/src/lib/dh-core-shell.component.ts
libs/dh/core/shell/src/lib/dh-core-shell.module.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.ts

- refactor some global components to be Standalone
- N/A

refactor(dh): change global components to be Standalone

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/shell/nav-list/watt-expand-on-active-link.directive.ts
libs/ui-watt/src/lib/components/shell/nav-list/watt-nav-list-item.component.ts

- replace Subject with EventEmitter in `watt-nav-list-item` component
- N/A

refactor(ui-watt): replace Subject with EventEmitter

---

apps/dh/app-dh/project.json

allow `inputmask` and `flat` in commenjs deps for DataHub

chore(dh): allow inputmask and flat in commenjs deps

---

libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Fixed wrong translations for from and to date

---

libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts

fix: formatting datetime to iso

---

.eslintrc.json
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

replace `plugin:ngrx/component-store-strict` with `plugin:@ngrx/component-store-strict` in `.eslintrc.json`, to fix broken build on main.

fix: remove plugin:ngrx/component-store-strict from .eslintrc.json

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/toast/index.ts

- export `WattToastRef` type
- N/A

fix(ui-watt): export toast ref type

---

libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.html
libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.ts

Adjust the icons used in the charges result component to match the design.
- #1655

feat(dh): adjust icons on charges result

---

.github/workflows/dh-frontend-cd.yml
.github/workflows/watt-frontend-cd.yml

Fix failing build caused by double underscores.

remove _ from RELEASE_VERSION

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.scss
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts

Add no result state for searching batches

feat(wholesale): add no result state for searching batches

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.spec.ts
libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.html

Adjust label of execution time

refactor(wholesale): adjust label of execution time

---

libs/dh/core/shell/src/lib/dh-core-shell.component.html
libs/dh/core/shell/src/lib/dh-core-shell.component.scss
libs/dh/globalization/feature-language-picker/src/lib/language-picker/dh-language-picker.component.scss

- adjust spacing in top bar so it aligns with main content on large screens
- #384

feat(dh): adjust spacing in top bar

---

README.md
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

docs: add Java to Prerequisites

---

apps/dh/api-dh/documents/development.md
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
docs/dh/testing.md

- update testing documentation
- #995

docs: update testing documentation

---

README.md

Reverts changes to Getting Started regarding BFF and mocks, as well as removes the troubleshooting section, since the content is no longer relevant after githook implementation.

docs: minor fixes to readme

---

apps/eo/app-eo/src/index.html
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

This adds siteimprove to the site in general

Add siteimprove

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
build/infrastructure/eo/host/nginx.conf

Iimprove CSP

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/consumption-page/shell/src/lib/eo-consumption.service.ts

Force app build for argoCD

---

libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.html
libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

When pressing the download button on charge search page, a csv file is created with the search results
story 1766 from the Volt board
- #1766

feat:the download button is enabled and will generate a csv file with all charges from search result

---

tools/generators/watt-component/index.ts

- use correct name in path mapping for Watt components
- N/A

fix: use correct name in path mapping for Watt components

---

libs/dh/charges/feature-prices/src/lib/drawer/price-tab/dh-charges-charge-prices-tab.component.html
libs/dh/charges/feature-prices/src/lib/drawer/price-tab/dh-charges-charge-prices-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Added ToDateTime when resolution is Day or Month.
Changed some texts.
- Charges [#1688](https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/1688)

feat: Adjustments to charge price table

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

https://github.com/Energinet-DataHub/geh-post-office/issues/793

Changed from status to aktørstatus

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

This PR bumps below packages to v. 5.0.0
* Energinet.DataHub.Charges.Clients
* Energinet.DataHub.Charges.Clients.Registration
This version is without `ChargeLinkV2Dto.cs`.
- #0000

Update: `Charges.Clients` and `Charges.Clients.Registration` to latest v `5.0.0`

---

libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.ts

Needs the format the dates to a specific format, to get the message.
- #0000

fix: Message view convert dates to correct format.

---

.github/workflows/dh-backend-cd.yml

fix dispatch event name

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/datepicker/index.ts
libs/ui-watt/src/lib/components/input/timepicker/index.ts

- export `WattRange` interface from Watt
- #948

fix(watt): export WattRange interface from Watt

---

libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.html

Change default sorting columns.
- #1799
https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/1799

feat: Change charges table default sort column

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.ts
libs/ui-watt/src/lib/components/input/shared/watt-picker-base.ts
libs/ui-watt/src/lib/components/input/timepicker/watt-timepicker.component.ts

To fix an issue with the slider button getting out of state, I added a manual change detection when changing the enable / disabled value.

Added change detection to picker-base

---

apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/domain/src/lib/generated/v1/api/wholesale-batch-http.service.ts

This PR implements GetBatchAsync
- #0000

feat: implement GetBatchAsync

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/certificates/src/lib/eo-certificates.component.ts
libs/eo/certificates/src/lib/eo-certificates.store.ts

Add button for mocking certs data

Allow mock data for certs

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/WholesaleControllerTests.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

This PR will add the functionality to retrieve a `ProcessStepResultDto` from the Wholesale Client
- 502 in Wholesale repo

feat: processStepResult implmented

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/certificates/src/lib/eo-certificates.component.ts
libs/eo/certificates/src/lib/eo-certificates.store.ts

Removes the mock button from certificates pages again. Not needed anymore.

Remove mock button from certificates page

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/table/+storybook/watt-table.stories.ts
libs/ui-watt/src/lib/components/table/watt-table.component.scss
libs/ui-watt/src/lib/components/table/watt-table.component.ts

This vertically aligns table headers, in case any table headers span multiple lines. Also fixes infinitely stretching rows, as well as some minor issues with the table story.

fix(ui-watt): minor watt-table fixes

---

.github/workflows/watt-cd.yml

- fix workflow by adding environment variables
- N/A

fix(ci): add environment variables to workflow

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/card/watt-card.component.ts

The card component had a transparent background. This makes it white instead.
<!--- Please leave a helpful description of the pull request here. ---

fix(ui-watt): card background

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/help/shell/src/lib/eo-geography-page.component.ts
libs/eo/help/shell/src/lib/eo-introduction-page.component.ts
libs/eo/help/shell/src/lib/eo-simultaneity-page.component.ts

Fix width issues on help pages

Limit width on help pages

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
libs/dh/admin/feature-user-management/src/lib/user-management-tabs/dh-users-tab.component.ts
libs/dh/shared/data-access-msw/src/lib/handlers.ts
libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserOverview.json

- update store to get users data for "user-management" page
- add mock
- https://github.com/Energinet-DataHub/geh-post-office/issues/882

feat(dh): update store to get users data

---

libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts
libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts
libs/dh/message-archive/feature-log-search/src/lib/shared/dh-message-archive-status.component.ts
libs/dh/message-archive/shell/src/lib/dh-message-archive-shell.module.ts

Convert message archive feature log search components to standalone
- N/A

refactor: dh message archive as standalone

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts

- dropdown model should update continuously as options are selected. Previously, the model updated only after the dropdown was blurred. 
- #590

feat(watt): dropdown model should update continuously

---

libs/dh/shared/data-access-msw/src/lib/handlers.ts
libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipantUser.ts
libs/dh/shared/data-access-msw/src/lib/mocks/token.ts

Currently, the mock environment is broken; this PR adds the missing mocks making the environment work again.

fix: add missing mocks

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- add page number and page size as params to request
- rename column names in user management page
- https://github.com/Energinet-DataHub/geh-post-office/issues/882

feat(dh): add page number and page size as params to request

---

libs/dh/shared/ui-paginator/src/lib/dh-shared-ui-paginator.component.ts

- add type to Output property
- N/A

feat(dh): add type to Output property

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-user-status.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- add status badge to user management page
- https://github.com/Energinet-DataHub/geh-post-office/issues/882

feat(dh): add status badge to user management page

---

apps/dh/api-dh/source/DataHub.WebApi/Registration/HealthEndpointRegistrationExtensions.cs

- remove old health check calls
- N/A

feat(dh): remove old health check calls

---

libs/dh/metering-point/feature-overview/src/lib/breadcrumb/dh-breadcrumb.component.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-feature-overview.module.ts
libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
libs/dh/metering-point/feature-overview/src/lib/general-error/dh-metering-point-general-error.component.ts
libs/dh/metering-point/feature-overview/src/lib/not-found/dh-metering-point-not-found.component.ts

Standalone update [^1]
[^1]: Standalone components, directives, and pipes aim to streamline the authoring experience by reducing the need for NgModules
- @frontend-specialisten said to do it

chore: standalone the master data overview components

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/foundations/_variables.scss
yarn.lock

change label color to align with Figma
- [#1268](https://app.zenhub.com/workspaces/bounty-hunters-61941fea47ab810010e9aa91/issues/gh/energinet-datahub/greenforce-frontend/1268)

chore(ui-watt): change label color from primary-dark -> neutral-black

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.html
libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-reactive-forms.stories.ts
libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.html
libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts

Make it possible to disable the dropdown

feat(watt): make it possible to disable the dropdown

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-reactive-forms.stories.ts
libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
libs/ui-watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts

change name of mighty ducks

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-search.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- implement user search in user management page
- https://github.com/Energinet-DataHub/geh-post-office/issues/922

feat(dh): implement user search

---

libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-master-data.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-master-data.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

user role drawer details
- #0000

user role drawer details

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts

userroleid param fix

---

.vscode/extensions.json

add liveshare to recommendations
- #943

docs: add liveshare to recommendations

---

libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetAll.json

- mock `v1/MarketParticipantUserRole/GetAll` endpoint
- N/A

feat(dh): add endpoint mock

---

libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json

- highlight selected table row
- mock `MarketParticipantUserRole/GetUserRoleWithPermissions` endpoint
- N/A

feat(dh): highlight table row and mock endpoint

---

libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-permissions.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- restructure localization
- https://github.com/Energinet-DataHub/geh-post-office/issues/904

chore(dh): restructure localization

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts

Make contracts conditional because of using 204 to return nothing if no contracts available, instead of returning empty array

Bug: Make contracts conditional

---

libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- Added Created column to users.
- Fixed missing translation of Status filter options.

feat: Added created column to users.

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/certificates/src/lib/certificate-details/eo-certificate-details.component.ts

This puts the Certificates page disclaimer on the details page for a certificate as well

Put a disclaimer on certificate details page

---

libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- Add Actor column to user list.
- Remove Created column from user list.

feat: Add Actor column to user list.

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/certificates/src/lib/eo-certificates-table.component.ts
libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
libs/eo/metering-points/shell/src/lib/eo-metering-point-table.component.ts
libs/eo/shared/services/src/feature-flag/feature-flag.service.ts

This removes the feature flag for certificates, so it will be publicly available
Also fixed an issue with the certificates page, where it would load the page slowly if revisiting, because of the order of loading component data.

Remove certificates feature flag

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts

Simplify the language on error messages

Change language on error message

---

apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-permissions.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
libs/dh/shared/domain/src/lib/generated/v1/model/user-role-with-permissions-dto.ts

marketparticipant client nuget update
- #0000

marketparticipant client nuget update

---

libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserSearchUsers.json

- fix mock so users are shown in `user-management` page
- N/A

chore(dh): fix mock

---

libs/dh/admin/data-access-api/src/index.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts
libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.scss
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts

- update translations
- implement user role name edit in modal
- mock ednpoint
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/891

feat(dh): implement user role name edit in modal

---

libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts

fix(wholesale): change type to TimeSeriesType.NonProfiledConsumption

---

libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.html
libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.scss
libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts

Added invite user modal
https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/1027

Added invite user modal

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.spec.ts
libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.spec.ts
libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleAuditLogs.json

- adjust tests, mock data and typing
- N/A

chore(dh): adjust tests, mock data and typing

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles.store.spec.ts

- fix missing enum value
- N/A

test(dh): fix missing enum value

---

libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.html
libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.scss

Removed chars

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts

- use correct error property 
- N/A

fix(dh): use correct error property

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/table/watt-table.component.ts

When a table is selectable, and new data is sent in, any previously selected rows are still returned by `selectionChange` event. The table is extended to expose a method that can be used to clear a selection.
- expose method for clearing selection
- N/A

feat(watt): expose method for clearing selection

---

libs/dh/wholesale/feature-calculation-steps/src/lib/steps/meta-data.ts

Avoid `undefined` values in meta-data

fix(wholesale): make sure processStepResults won't emit undefined values

---

libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html

Add grid area code for settlement reports

feat(wholesale): add grid area code for settlement reports

---

.editorconfig

We all have big wide screens. Lets use the real state to get more readable code with less line breaks.

Set line length 100

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/card/watt-card.component.ts
libs/ui-watt/src/lib/components/card/watt-card.stories.ts

Added variant to card, so the border style can be changed

Added variant, with solid and elevation

---

.vscode/settings.json

- specify list of generators, so custom DataHub generators are preferred over Nx generators
- N/A

chore: specify list of Nx generators

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts

Sat wrong enddate on emissions, and forgot to divide other dates with 1000 to give backend better timestamp

bugfix wrong time end

---

README.md
apps/dh/e2e-dh/src/integration/b2c.spec.ts
docs/dh/datahub-bookmarks.html

chore: update T-001 URL

---

libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.html
libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRolePermissions.json

- set initially selected permissions in edit user role
- handle selection change in permissions table
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/893

feat(dh): add support for permissions selection in edit user role 

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/admin/feature-edit-user-role-modal/tsconfig.json

- remove logic that disables save button
- handle form submission in save method
- disable compiler options for a library
- format files
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/893

feat(dh): adjustments to edit user role

---

.vscode/extensions.json

Add GraphQL VS Code plugin to recommendations

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Adjust translations for calculation steps

feat(wholesale): adjust translations for calculation steps

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.routes.ts
libs/dh/wholesale/feature-calculation-steps/src/lib/steps/3-consumption-per-balance-responsibles.ts

Add results for non-profiled consumption per balance responsible
- [#789](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/789)

feat(wholesale): add balance responsibles process step result

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.ts
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/details-header/dh-charge-details-header.component.html
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/details-header/dh-charge-details-header.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/dh-charge-content.component.html
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/history-tab/dh-charges-charge-history-tab.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/message-tab/dh-charges-charge-messages-tab.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/price-tab/dh-charges-charge-prices-tab.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.html
libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.scss
libs/dh/charges/feature-prices/src/lib/drawer/dh-charges-prices-drawer.component.html
libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.html
libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.scss
libs/ui-watt/src/lib/components/badge/watt-badge.component.scss
libs/ui-watt/src/lib/components/description-list/watt-description-list.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer-actions-content.component.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer-actions.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer-heading.component.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer-topbar.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.html
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer.module.ts
libs/ui-watt/src/lib/foundations/_variables.scss
libs/ui-watt/src/lib/foundations/typography/_typography.import.scss

Fixing drawer design after tab re-design

Fixing drawer design, after tab redesign

---

libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.html
libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts

Send process type from start batch to the API.
- [#855](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/855)

fix(wholesale): send process type from start batch to the api

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/PermissionDtoType.cs
libs/dh/shared/domain/src/lib/generated/v1/model/permission-details-dto.ts

permission created added to permission list api
- #0000

permission created added to permission list api

---

codegen.ci.ts
codegen.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.ts
schema.graphql

The executionTime (DateTimeOffset) was typed as `any`. This caused an error to slip through the checks.

fix(dh): settlement reports missing execution time

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Bumped wholesale client to version 5.0.18
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/855

Bumped wholesale client to version 5.0.18

---

libs/dh/shared/ui-date-time/src/index.ts
libs/dh/shared/ui-date-time/src/lib/dh-date-range.pipe.spec.ts
libs/dh/shared/ui-date-time/src/lib/dh-date-range.pipe.ts
libs/dh/shared/ui-date-time/src/lib/dh-date.pipe.spec.ts
libs/dh/shared/ui-date-time/src/lib/dh-date.pipe.ts
libs/dh/shared/ui-date-time/src/lib/dh-datetime-range.pipe.spec.ts
libs/dh/shared/ui-date-time/src/lib/dh-datetime-range.pipe.ts
libs/dh/shared/ui-date-time/src/lib/dh-datetime.pipe.spec.ts
libs/dh/shared/ui-date-time/src/lib/dh-datetime.pipe.ts
libs/dh/shared/ui-date-time/src/lib/dh-format-danish-datetime.ts
libs/dh/shared/ui-date-time/src/lib/dh-shared-ui-date-time.module.ts

Added pipes to format date range

Added pipes for date(time) range formats

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/admin-get-permissions.ts

- add admin permissions mock data
- https://github.com/Energinet-DataHub/Titans/issues/13

feat(dh): add admin permissions mock

---

yarn.lock

Updated browserslist-db

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.html
libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/admin/feature-user-management/src/lib/tabs/permissions-tab/dh-permissions-tab.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/admin-get-permissions.ts
libs/dh/shared/domain/src/lib/permission.ts

- add `permissions:manage` permission
- add edit permissions button to drawer
- move text to drawer heading
- https://github.com/Energinet-DataHub/Titans/issues/13

feat(dh): add new permission and edit button in drawer

---

libs/dh/shared/domain/src/lib/permission.ts
libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.module.ts

By request, we have added permission guard to the areas of the frontend that concerns settlements in wholesale.

Add permission guard and claim to wholesale

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html

Add permission guard to nav buttons

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/WholesaleControllerTests.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/WholesaleClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
libs/dh/shared/domain/src/lib/generated/v1/model/wholesale-batch-request-dto.ts

refac: Move CreateBatch to use nswag client

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/GraphQLQuery.cs

Include the initial created audit log for permissions

Fix GraphQL Query for permission AuditLogs

---

libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-audit-logs.component.html
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-audit-logs.component.scss
libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-audit-logs.component.html
libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-audit-logs.component.scss

feat(dh): minor styling adjustments

---

apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantPermissionController.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/GraphQLQuery.cs

Changed ChangedBy Username in Permission Auditlog

---

apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
libs/dh/shared/domain/src/lib/generated/v1/model/wholesale-batch-request-dto.ts

Rolleback to use package for create batch

---

apps/dh/api-dh/source/DataHub.WebApi/Registration/DomainRegistrationExtensions.cs

Register WholesaleClientV3

---

.github/workflows/create-tokens.yml

Ignore main

---

.github/workflows/create-tokens.yml

--preserveRawValue=true

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Fixing case

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/GraphQLSchema.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/EicFunctionEnum.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/PermissionDtoType.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/UserRoleStatusEnum.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/UserRoleType.cs
libs/dh/admin/data-access-graphql/get-permissions.graphql
libs/dh/shared/data-access-msw/src/lib/mocks/data/admin-get-permissions.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
schema.graphql

Added what EIC functions the permission is assignable to and what userroles the permission is currently added to.

Add more data to Permission document in GraphQL

---

libs/dh/wholesale/feature-settlement-reports/src/lib/dh-wholesale-settlement-reports.component.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/form/dh-wholesale-form.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/form/dh-wholesale-form.component.ts

Add filtering of process types at settlement reports (until now, selecting process type(s) didn't actually do anything).

feat(wholesale): add filtering of process types at settlement reports

---

libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-masterdata-tab/dh-create-userrole-masterdata-tab.component.html
libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-masterdata-tab/dh-create-userrole-masterdata-tab.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- remove status field from user role creation flow
- https://github.com/Energinet-DataHub/Titans/issues/38

feat(dh): remove status field from user role creation flow

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/forgotpassword-unified.html

invite flow template setup changes
- #0000

invite flow template setup changes

---

libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-masterdata-tab/dh-create-userrole-masterdata-tab.component.html

- move market role field as first
- https://github.com/Energinet-DataHub/Titans/issues/38

chore(dh): move market role field as first

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/WholesaleClient.cs

Settlement report temp fix

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

Fixed texts

---

.github/actions/dotnet-prepare-outputs/action.yml
.github/actions/dotnet-tests-prepare-outputs/action.yml
.github/actions/yaml-increment-version/action.yaml
.github/workflows/ci-orchestrator.yml
.github/workflows/dh-cd.yml
.github/workflows/dh-ci-dotnet.yml
.github/workflows/watt-cd.yml

AC at:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/966

Enable YAML casing validation

---

apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/ProcessStepType.cs

Adjust if statement from || to && in processStepType.cs
- #0000

adjust if statement from || to && in processStepType.cs

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/tabs/watt-tab.component.ts
libs/ui-watt/src/lib/components/tabs/watt-tabs.component.ts

- see change detection to default
- use template ref directly to query for element
- https://github.com/Energinet-DataHub/Titans/issues/41

feat(watt): set change detection to default on tabs component

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Correct path

---

.github/workflows/frontend-ci.yml

- point SonarCloud action to master branch
- N/A

feat(dh): point SonarCloud action to master branch

---

.github/workflows/app-dh-healthchecks.yml

- use correct command in pipeline step
- N/A

fix: use correct command

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/admin/domain/.eslintrc.json
libs/dh/admin/domain/README.md
libs/dh/admin/domain/jest.config.ts
libs/dh/admin/domain/project.json
libs/dh/admin/domain/src/dh-danish-phone-number-pattern.ts
libs/dh/admin/domain/src/index.ts
libs/dh/admin/domain/src/test-setup.ts
libs/dh/admin/domain/tsconfig.json
libs/dh/admin/domain/tsconfig.lib.json
libs/dh/admin/domain/tsconfig.spec.json
libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.ts
package.json
tsconfig.base.json
yarn.lock

- move Danish phone number pattern to domain lib
Needed so the same pattern can be used in edit user modal.
- https://github.com/Energinet-DataHub/Titans/issues/85

feat(dh): move Danish phone number pattern to domain lib

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessageSearchCriteriaDto.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessagesSearch.cs

Archived messages filter

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessageSearchCriteriaDto.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessagesSearch.cs

refactor dto to edi

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/help/shell/src/lib/eo-faq-page.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-call-to-action.component.ts
libs/eo/landing-page/shell/src/lib/eo-landing-page-hero.component.ts

Removed nemid + info icon

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts

- add "Started by" column to "Search batch" page. The column shows an em dash until data is available
- https://github.com/Energinet-DataHub/team-titans/issues/60

feat(dh): add "Started by" column to "Search batch" page

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessageSearchCriteria.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessageSearchCriteriaDto.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessagesSearch.cs
libs/dh/shared/domain/src/lib/generated/v1/model/archived-message-search-criteria.ts

added senderNumber search criteria

---

libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.scss

Fix max-width issue on start batch:

fix(wholesale): adjust max-width of container on start batch

---

libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.html
libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.ts

- make it possible to filter batches by "Started by"
- https://github.com/Energinet-DataHub/team-titans/issues/60

feat(dh): make it possible to filter batches by "Started by"

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/form-field/form-field.component.scss
libs/ui-watt/src/lib/components/form-field/form-field.component.ts

- remove "size" Input from form field component
- N/A

feat(watt): remove "size" Input from form field component

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-with-mitid-unified.html

- https://github.com/Energinet-DataHub/team-titans/issues/141

feat(dh): remove links to "Sign up" flow

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/ArchivedMessagesSearch.cs

updated apis to match edi

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/metering-point/feature-identity-and-master-data/src/lib/identity/identity-text-field/dh-metering-point-identity-text-field-with-icon.component.ts
libs/dh/metering-point/feature-tabs/src/lib/charges-tab-content/dh-charge-item/dh-charge-item.component.html
libs/dh/metering-point/feature-tabs/src/lib/child-metering-points-tab-content/dh-child-metering-points-tab-content.component.html
libs/dh/metering-point/feature-tabs/src/lib/processes-tab-content/processes-detail-item/dh-processes-detail-item.component.html
libs/dh/metering-point/feature-tabs/src/lib/processes-tab-content/processes-table/dh-processes-table.component.html
libs/ui-watt/src/lib/components/clipboard/+storybook/storybook-clipboard.component.ts
libs/ui-watt/src/lib/components/table/+storybook/watt-table.stories.ts
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.html
libs/ui-watt/src/lib/foundations/icon/_watt-icon-variables.scss

- Update icon sizes and usage in `app-dh`
- Usage of small icons has now been changed to xs

feat(watt): update icon sizes and usage in app-dh

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts

displaying archived message document

---

libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts

Fix error with disabling download btn in Archived Search

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-core-shell.module.ts
libs/eo/help/shell/src/lib/eo-faq-page.component.ts
libs/eo/shared/utilities/src/index.ts
libs/eo/shared/utilities/src/lib/shared-utilities.ts

This PR creates a utility function that can scroll to an ID of an item on a page

Scroll to page anchor

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/reset-password.html

- minor adjustments to reset password layout
- https://github.com/Energinet-DataHub/team-titans/issues/141

feat(dh): minor adjustments to reset password

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.ts

refactor(watt): use util function in datepicker

---

libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.html

fix(dh): start batch execution type

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/input/datepicker/watt-date-range-chip.component.ts
libs/ui-watt/src/lib/utils/date/watt-date.mdx

This PR adds a documentation page for the WattDatePipe util. Also includes a small fix for date chip since I can't be bothered to make a separate PR...

docs(ui-watt): WattDatePipe

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/changepassword-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/forgotpassword-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-with-mitid-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/multifactorauth-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/reset-password.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/self-asserted.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/signup-unified.html

- remove `box-shadow` from buttons
- https://github.com/Energinet-DataHub/team-titans/issues/141

feat(dh): remove box shadow from buttons

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/utilities/src/lib/shared-utilities.ts
libs/eo/transfers/src/lib/eo-transfers-table.component.ts
libs/eo/transfers/src/lib/eo-transfers.service.ts
libs/eo/transfers/src/lib/eo-transfers.store.ts

This adjusts the EO app to use the correct return types from API of transfer agreements

Adjust transfers API response to reflect reality

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/shared/services/src/auth/auth.service.ts

Fix the timeout timer not calling refresh

Fix the timeout timer not calling refresh

---

libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts

- set size on drawer in message archive depending on screen size
- https://github.com/Energinet-DataHub/opengeh-edi/issues/270

feat(dh): set size on drawer in message archive

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.html
libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.spec.ts
libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.ts
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/ui-watt/src/lib/foundations/icon/icons.ts

This PR fixes some minor issues:
- [#1005](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/1005)

fix(dh): minor batches filter issues

---

libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantOrganizationGetFilteredActors.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserSearchUsers.ts

- update mock data
- mock request
- N/A

chore(dh): update mock data

---

.github/workflows/frontend-ci.yml

- fix upload of Cypress artifacts on failure
- #1781

ci: fix upload of Cypress artifacts on failure

---

libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts

Fix for GetBatches query not being properly unsubscribed to.

fix(dh): unsubscribe from batches query

---

apps/dh/app-dh/src/app/datahub-app.component.spec.ts
libs/dh/shared/test-util-auth/src/lib/msal-fake.service.ts

- update MSAL mock service
- N/A

test(dh): fix failing test

---

libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.routes.ts

fix(dh): correct version of settlement reports

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.ts

- update translations
- change default sorting column and direction
- sort options in grid area dropdown
- https://github.com/Energinet-DataHub/team-titans/issues/208
- https://github.com/Energinet-DataHub/team-titans/issues/205

feat(dh): minor adjustments to settlement reports page

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/configuration/watt-danish-datetime.providers.ts
libs/ui-watt/src/lib/configuration/watt-date-adapter.ts

- import locales from date-fns/locale instead of using deep import
- N/A

refactor(watt): import locale from date-fns/locale

---

libs/dh/wholesale/domain/src/actor.ts
libs/dh/wholesale/domain/src/index.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.ts

- sort actors by display value in dropdown filter in "Settlement reports" page
- https://github.com/Energinet-DataHub/team-titans/issues/206

feat(dh): sort actors by display value in dropdown 

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/search/watt-search.component.scss
libs/ui-watt/src/lib/components/search/watt-search.component.spec.ts
libs/ui-watt/src/lib/components/search/watt-search.component.ts

This adds a clear button to the watt-search component.

feat(ui-watt): watt-search clear button

---

.github/workflows/dh-healthchecks.yml
.github/workflows/watt-cd.yml

https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1226

changed texasrangers to teamfrontend

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.ts
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.html
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.scss
libs/dh/wholesale/feature-settlement-reports/src/lib/tabs/dh-wholesale-settlements-reports-tabs-balance.component.ts

- add reset button to settlement reports filters
- replace datepicker with chip version
- move translations to global shared object
- minor styling adjustments
- https://github.com/Energinet-DataHub/team-titans/issues/207

feat(dh): add reset button to settlement reports filters

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.html
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.scss
libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts

- adjustments to message archive drawer
- N/A

feat(dh): adjustments to message archive drawer

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-unified.html

Use build in button

---

.github/workflows/frontend-ci.yml
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
nx.json

chore: enable nx-cloud

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/main.css
libs/dh/shared/assets/src/assets/b2c-custom-layouts/multifactorauth-unified.html

We were missing a custom layout for add mitid to an existing account

Added design for add mitid to account

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/changepassword-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/main.css
libs/dh/shared/assets/src/assets/b2c-custom-layouts/totp-unified.html

Added styles to add authentication app dialog

Style authentication app dialog

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/routing/src/lib/routing.ts

This PR renames batch to calculation the quick and dirty way. The proper way (renaming in code as well), is coming in a separate PR.
- [#1879](https://github.com/Energinet-DataHub/greenforce-frontend/issues/1879)

chore(dh): rename batch to calculations

---

tools/github/create-branch-from-issue.ts

Set limit to 1000 (default 30)

---

libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-with-mitid-unified.html

- change "Forgot password" text on login screen
- remove "Sign in" heading from login screen
- https://github.com/Energinet-DataHub/team-titans/issues/141
- https://github.com/Energinet-DataHub/team-titans/issues/232

feat(dh): login screen adjustments

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.html
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.scss
libs/dh/wholesale/feature-calculations/src/lib/details/details.component.scss
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss
libs/ui-watt/src/lib/components/shell/shell.component.html
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/components/table/watt-table.component.scss

This PR tries to implement what #1297 failed to do.

feat(dh): shell grid layout

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/transfers/src/lib/eo-transfers-table.component.ts

Fix sorting of `startDate` under transfer agreements table

fix(eo, transfers): adjust accessor of startDate of ta for table

---

.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml

- exclude translation files from SonarCloud duplication
- update SonarCloud's GH Action to v2 to get rid of Java 11 warning
- N/A

chore: exclude translation files from SonarCloud duplication

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/watt-drawer-content.component.ts

Fixing overflow problem on drawer

Added overflow, to fix drawer with wide content

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-graphql/get-actors.graphql
libs/dh/market-participant/actors/data-access-graphql/project.json
libs/dh/market-participant/actors/feature-actors/src/lib/actors-filters.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipant.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

- load actors in Actors page
- add "Status" and "Market roles" filters (non-functional for now)
- mock get actors query
- https://github.com/Energinet-DataHub/team-titans/issues/215

feat(dh): load actors and add filters to Actors page

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/status-badge/dh-actor-status-badge.component.ts

- rename translation property
- filter out irrelevant statuses in filter
- translate status values in filter
- translate market roles in table
- https://github.com/Energinet-DataHub/team-titans/issues/215

feat(dh): adjustments to actors page

---

.github/workflows/dh-ci-dotnet.yml

Use new integration test env

---

.github/workflows/dh-cd.yml

use new integration test environment in dh-cd

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/search/watt-search.component.scss
libs/ui-watt/src/lib/components/search/watt-search.component.ts

- add hover state to Search component
- hide output property from Storybook
- N/A

feat(dh): add hover state to Search component

---

libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.html

- fix infinite loading spinner on button
- https://github.com/Energinet-DataHub/team-titans/issues/243

fix(dh): fix infinite loading spinner on button

---

.github/workflows/dh-cd.yml
.github/workflows/dh-ci-dotnet.yml

https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1201

Use new tenant variable

---

libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-table.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-table.component.ts

- mvoe actors table to separate component in preparation for drawer
- https://github.com/Energinet-DataHub/team-titans/issues/225

refactor(dh): move actors table to separate component

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-table.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-table.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts

- show drawer with details when actor is selected in table
- https://github.com/Energinet-DataHub/team-titans/issues/225

feat(dh): actors drawer component

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html

- add GLN/EIC to actor drawer headline 
- https://github.com/Energinet-DataHub/team-titans/issues/225

feat(dh): add GLN/EIC to actor drawer headline

---

.github/workflows/frontend-ci.yml

chore: remove non-existing path from ignore filter

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

Just a small fix to translations.

fix(dh): update translation for wholesale fixing

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.html
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.scss
libs/dh/wholesale/feature-calculations/src/lib/calculations.component.ts
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.html
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.scss
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts
libs/watt/src/lib/components/search/watt-search.component.scss
libs/watt/src/lib/components/table/watt-table.component.html
libs/watt/src/lib/components/table/watt-table.component.scss
libs/watt/src/lib/components/table/watt-table.component.ts
libs/watt/src/lib/components/vater/vater-spacer.component.ts

Use vater components for layout in calculations.

feat(dh): use vater in calculations

---

libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-message.ts
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages-table.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages-table.component.ts
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/shell/src/lib/dh-market-participant-actors-shell.component.ts

- add empty table to eSett page

feat(dh): add table to eSett page

---

libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages-filters.ts
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/dh-outgoing-messages.component.ts
libs/dh/esett/shell/src/lib/outgoing-messages/filters/dh-filters.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/filters/dh-filters.component.ts
libs/dh/esett/shell/src/lib/outgoing-messages/table/dh-table.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/table/dh-table.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/esett-mocks.ts

- send filters and pagination data to GraphQ query
- make filter dropdowns single-select
- move paginator to parent component
- update mock data

feat(dh): send filters and pagination data to GraphQ query

---

libs/dh/esett/shell/src/lib/outgoing-messages/filters/dh-filters.component.html
libs/dh/esett/shell/src/lib/outgoing-messages/filters/dh-filters.component.ts
libs/dh/esett/shell/src/lib/outgoing-messages/status-badge/dh-outgoing-message-status-badge.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- use new Watt dropdown component
- fix translations

feat(dh): adjustments to Outgoing messages in eSett

---

libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.html

- implement table download
- remove sorting inputs from table

feat(dh): implement table download

---

libs/dh/esett/feature-balance-responsible/.eslintrc.json
libs/dh/esett/feature-balance-responsible/README.md
libs/dh/esett/feature-balance-responsible/jest.config.ts
libs/dh/esett/feature-balance-responsible/project.json
libs/dh/esett/feature-balance-responsible/src/index.ts
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible-message.ts
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.html
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.ts
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.ts
libs/dh/esett/feature-balance-responsible/src/test-setup.ts
libs/dh/esett/feature-balance-responsible/tsconfig.json
libs/dh/esett/feature-balance-responsible/tsconfig.lib.json
libs/dh/esett/feature-balance-responsible/tsconfig.spec.json
libs/dh/esett/shell/src/lib/dh-esett-shell.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
tsconfig.base.json

- add "Balance responsible" tab to eSett

feat(dh): add balance responsible tab

---

build/infrastructure/eo/configuration.yaml
libs/eo/certificates/src/lib/eo-certificate-details.component.ts
libs/eo/certificates/src/lib/eo-certificates.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-chart-card.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-energy-consumption.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-info.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-shell.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-tip.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-chart-card.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-emissions-card.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-get-data.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-hourly-declaration.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-links.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-greenhouse-gasses.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-info.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-lead-by-example.component.ts
libs/eo/emissions/shell/src/lib/eo-emissions-page-tip.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-card.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-chart-tips.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-hourly-declaration.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-renewable-energy.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-what-is-it.component.ts
libs/eo/production/shell/src/lib/eo-production-chart-card.component.ts
libs/eo/production/shell/src/lib/eo-production-info.component.ts
libs/eo/production/shell/src/lib/eo-production-tip.component.ts
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-cookie-banner/eo-cookie-banner.component.ts
libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts

- Replaced `mat-card` with `watt-card`
https://github.com/Energinet-DataHub/energy-origin-issues/issues/1771

refactor(eo): replaced mat-card with watt-card

---

libs/dh/esett/feature-outgoing-messages/src/lib/status-badge/dh-outgoing-message-status-badge.component.ts

chore(dh): minor adjustments to date comparison

---

libs/dh/esett/shell/src/lib/dh-esett-shell.component.ts
libs/dh/market-participant/actors/shell/src/lib/dh-market-participant-actors-shell.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/market-participant-actors.ts

chore(dh): minor adjustments

---

libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/table/dh-table.component.ts
libs/dh/esett/shell/src/lib/dh-esett-shell.component.ts

feat(dh): layout adjustments to eSett page

---

libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.html
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.ts

- remove search from eSett tabs

fix(dh): remove search from eSett tabs

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/tabs/watt-tabs.component.scss

feat(watt): change padding on tab body wrapper

---

README.md

Added contributions to the readme

---

build/infrastructure/eo/configuration.yaml
libs/eo/transfers/src/lib/eo-transfers.service.ts

**Adjust contract for transfer automation status**
Contract can be found here: https://demo.energioprindelse.dk/swagger/?urls.primaryName=Transfer%20v1#/TransferAgreementAutomation/get_api_transfer_automation_status
https://github.com/Energinet-DataHub/energy-origin-issues/issues/1718

feat(eo, transfers): adjust contract for transfer automation status

---

libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html

chore(dh): remove extra spacing from component

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql

chore(dh): update GraphQL snapshot

---

libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html

fix(dh): paginator in eSett

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1435

Bump App package

---

libs/dh/esett/data-access-graphql/get-balance-responsible-messages.graphql
libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.html
libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.ts
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/data/esett-balance-responsible-messages.ts
libs/dh/shared/data-access-msw/src/lib/mocks/esett-mocks.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

- change date format in table
- update drawer to reflect latest design
- show XML message in drawer

feat(dh): show XML message in drawer

---

apps/dh/api-dh/source/DataHub.WebApi/Generated/HotChocolate.Types.Analyzers/HotChocolate.Types.Analyzers.TypeModuleGenerator/HotChocolateTypeModule.g.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Resolvers/EsettExchangeResolvers.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/EsettOutgoingMessageType.cs

Fixes route for downloading eSett documents

Fixed route for documents

---

libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts

Fixed range error when loading large documents

Fixed range error, when loading large document

---

libs/dh/esett/feature-balance-responsible/src/lib/drawer/dh-drawer.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts

Use the new webapi text decoder

use text decoder instead

---

libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/drawer/dh-outgoing-message-drawer.component.ts

- fix missing translation warning in console
- remove unused import

fix(dh): missing translation warning

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/EdiB2CWebAppClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Generated/HotChocolate.Types.Analyzers/HotChocolate.Types.Analyzers.TypeModuleGenerator/HotChocolateTypeModule.g.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/EdiB2CProcessType.cs

https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/75
- #0000

refac: edi business reason to enum process types

---

libs/dh/market-participant/actors/feature-market-roles/src/lib/dh-market-roles-overview.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/dh-organizations-overview.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/dh-organizations-overview.component.ts

- add search and download to Organizations
- remove ElOverblik from Market roles table
- disable sorting on description column for Market roles
- https://github.com/Energinet-DataHub/team-titans/issues/224

feat(dh): add search and download to Organizations

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/market-participant/shell/src/lib/dh-market-participant-shell.routes.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

- remove actors feature flag 
- https://github.com/Energinet-DataHub/team-titans/issues/224

chore(dh): remove actors feature flag

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/dropdown/watt-dropdown.component.html
libs/watt/src/lib/components/dropdown/watt-dropdown.component.ts

Fixed required on dropdown

---

build/infrastructure/eo/configuration.yaml
libs/eo/transfers/src/lib/eo-transfers-wallet-modal-component.ts

Adjust condition for error message in wallet deposit endpoint
- #0000

fix(eo): adjust condition for error message in wallet deposit endpoint

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/edit/dh-actors-edit-actor-modal.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/dh-organization.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.ts
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.ts
libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipant.ts

- basic edit organisation modal
- email validation message
- mock for edit actor
- https://github.com/Energinet-DataHub/team-titans/issues/224

feat(dh): basic edit organisation modal

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/field/watt-field.component.ts
libs/watt/src/lib/components/picker/datepicker/watt-datepicker.component.ts

Report error when form is submitted

---

build/infrastructure/eo/configuration.yaml
libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.spec.ts
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/dh-charge-content.component.spec.ts
libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.spec.ts
libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/dh-market-participant-actor-market-roles.component.spec.ts
libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/master-data/dh-market-participant-actor-master-data.component.spec.ts
libs/dh/market-participant/feature-edit-organization/src/lib/market-participant-edit-organization/master-data/dh-market-participant-organization-master-data.component.spec.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point-search.component.spec.ts
libs/dh/wholesale/feature-calculations/src/lib/calculations.cy.ts
libs/eo/connections/feature-invite-connection/invite-connection.component.ts
libs/eo/transfers/src/lib/eo-transfers.component.ts
libs/watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts
libs/watt/src/lib/components/field/watt-field.component.ts
libs/watt/src/lib/components/picker/timepicker/watt-timepicker.module.spec.ts

Had an issue with FormGroupDirective this PR fixes this

Fixed FormGroupDirctive issue

---

build/infrastructure/eo/configuration.yaml
libs/eo/shared/services/src/idle-timer/idle-timer.service.ts

Fix time of the idle timer
- #0000

fix(eo): fix time of idle timer

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/EdiB2CWebAppClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/swagger.json

https://github.com/Energinet-DataHub/opengeh-edi/pull/575
- #0000

fix: update edi b2c contract

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/field/watt-field.component.ts

- Make _formGroupDirective optional in `watt-field`. This fixes errors in the storybook-like the screenshot below:

fix(watt, watt-field): make _formGroupDirective optional

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

translation update

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html

Fixed permission issue

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-certificate.component.ts

- add basic Certificate tab in market party drawer
- add translations

feat(dh): add basic certificate tab in drawer

---

apps/dh/api-dh/openapitools.json
apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/GraphQL/__snapshots__/SchemaTests.ChangeTest.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/EdiB2CWebAppClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V1/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
libs/dh/shared/domain/src/lib/generated/graphql.ts
schema.graphql

fix: Metering point type is nullable in bff

---

libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-participant-certificate.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-certificate.component.ts

fix(dh): send actor id to endpoint

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-certificate.component.ts

- change certificate extension and mime type
- fetch data after upload

feat(dh): adjustments to certificate upload

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-participant-certificate.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-certificate.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-remove-certificate-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

- implement removal of certificate
- bump feature flag date

feat(dh): implement removal of certificate

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-participant-certificate.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/tabs/dh-certificate.component.ts

- clear credentials on removal
- show button text depending on certificate existence

feat(dh): adjustments to certificate removal

---

libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-roles.component.html
libs/dh/admin/feature-permissions/src/lib/details/tabs/dh-admin-permission-roles.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

added market role to permissions user roles

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/create/dh-actors-create-actor-modal.component.ts

added missing gridarea dropdown, and fix some bugs

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/modal/watt-modal.service.ts

- extend modal config to take Injector so dependencies injected in modal components can resolve. Otherwise `NullInjector` error was thrown.
- N/A

feat(watt): extend modal config to take injector

---

libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-party-credentials.store.ts

- https://github.com/Energinet-DataHub/team-titans/issues/326

fix(dh): remove credentials before generating new client secret
