Energinet-DataHub/greenforce-frontend

.github/actions/affected/action.yml
.github/actions/affected/affected.mjs
.github/workflows/ett.yml
apps/ui-watt-e2e/src/integration/app.spec.ts
infrastructure/ett/host/Dockerfile
infrastructure/ett/host/nginx.conf

Energy Track and Trace app workflow:
- Build the app when the app is affected by a PR or merge
- Build, tag, and publish the host container image to GitHub Container Registry when the app is affected by a PR or merge
- Host container image is tagged as `pr-<pull-request-number>` or `latest` for PRs and merge runs, respectively
Energy Track and Trace host:
- Nginx server with port 80 exposed
- Gzip compression
- SPA routing
Affected action:
- Licensed by ngworkers
- Determines whether a project is affected by changes in a pull request or merge commit

ci(ett): build and publish host

---

.github/workflows/ett.yml

The `base-branch` parameter is currently set to `undefined` on merge commits. This is an attemtp to fix that by setting it to `HEAD~1`.

ci(ett): fix affected `base-commit` on merge

---

.github/workflows/ett.yml

- The `base-branch` parameter is currently set to `undefined` on merge runs. The parameter is now correctly set.
- The host container image tag is incorrect for PR runs.

ci(ett): fix affected `base-branch` parameter for merge commits and PR host container image tag

---

.github/actions/affected/action.yml
.github/actions/affected/affected.mjs
.github/workflows/ett.yml

Replace `base-branch` and `base-commit` with single required `base` parameter to fix the affected job on merge runs.

ci(ett): fix affected job on merge runs

---

.github/workflows/ett.yml

The `BASE_BRANCH` environment variable is referred in two different ways which causes one of them to fail.

ci(ett): fix environment variable

---

libs/api-dh-app/documents/development.md
libs/api-dh-app/source/DataHub.WebApi.Tests/Integration/Controllers/MeteringPointControllerTests.cs
libs/api-dh-app/source/DataHub.WebApi/ApiClientSettings.cs
libs/api-dh-app/source/DataHub.WebApi/BaseUrls.cs
libs/api-dh-app/source/DataHub.WebApi/Controllers/MeteringPointController.cs
libs/api-dh-app/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/api-dh-app/source/DataHub.WebApi/Startup.cs
libs/api-dh-app/source/DataHub.WebApi/appsettings.json

Metering Point Controller added to BFF. It makes it possible to make a search for a single metering point based on _GSRN number_.
Note that ApiClientSettings:MeteringPointBaseUrl must be applied in appsettings.json (Environment variable?) when IaC for deployment is added.
- #0000

Add metering point controller

---

libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.html
libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.scss
libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.component.html
libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.component.scss
libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.component.ts
libs/ui-watt/src/lib/components/button/icon-button/watt-icon-button.module.ts
libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.module.ts
libs/ui-watt/src/lib/components/button/watt-button.stories.ts
libs/ui-watt/src/lib/components/empty-state/+storybook/storybook-empty-state-overview.component.html
libs/ui-watt/src/lib/components/input/+storybook/storybook-input-wrapper.component.ts

- Add separate `<watt-icon-button>` component
- Expose the component from `WattButtonModule`
- Adjust Storybook to use the new component
- Fix property values in Storybook overview page
- https://github.com/Energinet-DataHub/MightyDucks/issues/215

feat(watt): add icon button to Design System

---

.github/workflows/ett.yml
libs/ett/core/shell/src/lib/ett-core-shell.module.ts

Revert trigger filters that broke the ETT CD workflow when introduced.
*N/A*

ci(ett): remove trigger filters

---

infrastructure/eo/host/Dockerfile

Update host Nginx configuration path after #164 renamed a folder without updating the host Dockerfile.
- #164
- #168

ci(ett): correct Nginx configuration path

---

apps/dh/app-dh/project.json

- Fix warning by allowing "date-fns-tz" as CommonJS dependency
- N/A

fix(dh): allow "date-fns-tz" as CommonJS dependency

---

apps/dh/e2e-dh/src/integration/language-selection.spec.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-overview/src/lib/child-metering-point-tab-content/dh-child-metering-point-tab-content.component.html

- Remove "now" text from date range format
- Fix failing tests
- https://github.com/Energinet-DataHub/geh-metering-point/issues/601

feat(dh): remove "now" text from date range format

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

This PR bumps `Energinet.DataHub.Charges.Clients` to 1.0.22 which copes with enum (ChargeType) being passed from Charges Web API as string.
https://github.com/Energinet-DataHub/geh-charges/issues/827

Bump `Energinet.DataHub.Charges.Clients` to 1.0.22

---

.github/workflows/ett.yml

Energy Origin currently only has the Production environment except for on demand feature environments, so we're merging directly to `main`.
- https://github.com/Energinet-DataHub/energy-origin/issues/305

ci(eo): deploy to Production on merge to main

---

.github/workflows/ett.yml
README.md
apps/ett/app-ett/src/index.html
apps/ett/e2e-ett/src/integration/app.spec.ts
libs/ett/auth/data-access-security/README.md
libs/ett/auth/feature-login/README.md
libs/ett/auth/routing-security/README.md
libs/ett/auth/shell/README.md
libs/ett/auth/shell/src/lib/ett-auth-shell.component.ts
libs/ett/core/shell/README.md
libs/ett/core/shell/src/lib/ett-shell.component.ts

Change title of _Energy Track and Trace_ app to _EnergyOrigin_.
- https://github.com/Energinet-DataHub/energy-origin/issues/305

feat(eo): rename app to EnergyOrigin

---

.github/workflows/frontend-ci.yml
libs/dh/metering-point/feature-identity-and-master-data/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.html
libs/dh/metering-point/feature-identity-and-master-data/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.scss
libs/dh/metering-point/feature-identity-and-master-data/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.ts
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.html
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.scss
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.ts
libs/ui-watt/src/lib/foundations/icon/icon.component.scss
libs/ui-watt/src/lib/foundations/icon/icon.component.spec.ts
libs/ui-watt/src/lib/foundations/icon/icon.component.ts
libs/ui-watt/src/lib/foundations/icon/watt-icon-state.ts

- Extend icon to support state colors
- Update Storybook to showcase examples
- Refactor component to use state property on icon component
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/295

feat(watt): extend icon to support state colors

---

libs/dh/metering-point/feature-identity-and-master-data/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.html
libs/dh/metering-point/feature-identity-and-master-data/src/lib/primary-master-data/dh-metering-point-primary-master-data.component.ts
libs/ui-watt/src/lib/foundations/icon/+storybook/storybook-icon-overview.component.html
libs/ui-watt/src/lib/foundations/icon/icon.component.spec.ts
libs/ui-watt/src/lib/foundations/icon/icon.component.ts
libs/ui-watt/src/lib/foundations/icon/watt-icon-state.ts

- Set default state to `success`, `danger`, `warning` and `info` icons
- Allow state on `success`, `danger`, `warning` and `info` icons to be overwritten by `state` property
- Update showcase in Storybook
- Remove state property on icon in master data component
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/295

feat(watt): add default state to special icons

---

libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.ts

- Prevent Chrome/Edge/Safari from firing click events when disabled button is clicked
- #348

fix(watt): prevent emitting click events when disabled button is clicked

---

infrastructure/eo/chart/Chart.yaml
infrastructure/eo/chart/values.yaml

- Tag Helm chart version without `v` prefix to fix semantic version check in  #329 
- https://github.com/Energinet-DataHub/energy-origin/issues/313

ci(eo): tag Helm chart without `v` prefix

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json

In search metering point page the charge owner title has been erroneously changed to "Tarif ejer" for all charge tables. This PR reverts this change back to "Ejer" for the Danish translation.

Reverted charge owner title back to "Ejer" for danish translation

---

infrastructure/eo/chart/Chart.yaml
infrastructure/eo/chart/values.yaml
libs/eo/origin-of-energy/routing/project.json

There was a typo in the routing for origin of energy from when the lib was generated. For some reason the linter didn't catch this until it was merged to main, so this bugfix will fix it
https://github.com/Energinet-DataHub/energy-origin-issues/issues/431

Fix a typo for origin of energy lib

---

infrastructure/eo/chart/Chart.yaml
infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/time-range-input/watt-time-range-input.component.ts

- automatically jump to "end" field when the value in "start" field is complete
- provide custom comparator to `distinctUntilChanged` operator
- #418

feat(watt): improvements to time-range component

---

.github/workflows/eo-cd.yml
apps/eo/app-eo/src/index.html
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

- Remove base parameters for chart version files after they have been renamed
- https://github.com/Energinet-DataHub/energy-origin-issues/issues/244
- Feature environment http://eo-u-244removebasew.westeurope.cloudapp.azure.com/

ci(eo): remove base chart properties after rename

---

libs/dh/metering-point/feature-search/src/lib/form/dh-metering-point-search-form.component.html
libs/dh/metering-point/feature-search/src/lib/form/dh-metering-point-search-form.component.scss

Adjust styling on metering point search form so the input field looks consistent with input fields in Watt.
- remove class from label 
- adjust spacing on input element 
- adjust spacing on button element
Before
After
- N/A

refactor(dh): adjust styling on metering point search form

---

libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.spec.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart/eo-origin-of-energy-pie-chart.component.ts
libs/eo/origin-of-energy/shell/tsconfig.spec.json

This is a refactor for the pie chart component test, so that it works more performantly. 
It was originally intended for testing that we can't merge when tests fail, but now that the test has been confirmed for this repository, this refactor does not need to go to waste.

(EO) Refactor of pie chart component test

---

apps/dh/e2e-dh/src/integration/b2c.spec.ts
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

When Datahub E2E runs to confirm redirect of pages in PlayWright, the tests would fail without leaving a good error description that could be turned into actions.
This change will now make it easier to pinpoint when environments start giving other status returns than 200, and also fail the test a lot quicker if it fails.
EDIT: Commented out the current failing server, so E2E can run again until the server has been fixed.

(DH) Fail E2E early if page returns 404

---

libs/dh/shared/assets/src/assets/reset-password-page/self-asserted.html

Change selector from `h2` -> `h1` since `h1` is used for reset password flow and not `h2`.
- #0000

fix(dh): adjust styling of heading (reset password)

---

apps/dh/e2e-dh/src/integration/b2c.spec.ts

Add health checks for signup and forgot password link (b2c)
- Checks that `sign up` and `forgot password` exist
- Checks that  `sign up` and `forgot password` redirects to correct b2c userflow 
- #705

feat(dh-e2e): add healthcheck for signup and forgot password link (b2c)

---

.github/workflows/dh-backend-cd.yml
.github/workflows/dh-backend-ci.yml

Speed up CI execution time by using default .NET Core SDK version pre-installed on hosted Github Runner
Reference: https://github.com/Energinet-DataHub/the-outlaws/issues/360

Remove DOTNET_VERSION

---

libs/ui-watt/src/lib/components/drawer/+storybook/watt-drawer.stories.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.spec.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.ts

Trying to take the simplest approach here, since I agree that this is normally a non-issue if using the drawer "correctly" (as in reusing the same drawer component and then just updating the content instead of opening a new drawer).
However, in certain cases reusing the same drawer component might not be that feasible (for instance if on the same page two separate components are using a drawer to render completely different data).
I considered various solutions such as using a [Portal](https://material.angular.io/cdk/portal/overview) along with a service, but they were all too complex solutions for something that might not even be an issue. So I settled on just storing the current drawer instance in a static property, making it shared between multiple drawer instances. Then if you open a …

feat(ui-watt): only allow one drawer at a time

---

libs/dh/shared/feature-flags/README.md
libs/dh/shared/feature-flags/src/lib/feature-flags.spec.ts

Increase feature flag expiration to 62 days (2 month'ish)
- #771

fix(dh): increase feature flag expiration to 62 days (2 month'ish)

---

apps/eo/app-eo/project.json
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/consumption-page/shell/src/lib/eo-consumption-chart-card.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-info.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption-page-shell.component.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption.service.ts
libs/eo/consumption-page/shell/src/lib/eo-consumption.store.ts
libs/eo/production/shell/src/lib/eo-production-chart-card.component.ts
libs/eo/production/shell/src/lib/eo-production-info.component.ts
libs/eo/production/shell/src/lib/eo-production-shell.component.ts
libs/eo/production/shell/src/lib/eo-production.service.ts
libs/eo/production/shell/src/lib/eo-production.store.ts
libs/eo/shared/services/src/app-settings/app-settings.store.ts
libs/eo/shared/services/src/feature-flag/feature-flag.directive.ts
libs/eo/shared/services/src/feature-flag/feature-flag.service.spec.ts
libs/eo/shared/services/src/feature-flag/feature-flag.service.ts

Date range picker is now being being soft-pushed to consumption and production pages.
They are going to be in production, but hidden behind the feature flag 'daterange' for now.
They can be seen at https://demo.energioprindelse.dk/consumption?enableFeature=daterange

Datarange picker for consumption and production

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/form-field/form-field.component.scss
libs/ui-watt/src/lib/components/input/+storybook/input.directive.stories.ts
libs/ui-watt/src/lib/components/input/+storybook/storybook-input-wrapper.component.ts

This PR improves the styling of `<textarea>` when used with `[wattInput]`. I had to change the css `height` to `minHeight` for input fields, to allow the `<textarea>` to increase the height of the input field.
- #626

style(ui-watt): make textarea work with wattInput

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.html
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.spec.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.ts
libs/ui-watt/src/lib/components/drawer/watt-drawer.module.ts

The global keydown handler for the drawer was being triggered by pressing ESC within a modal, meaning if you were to open a modal within a drawer and then press ESC, both modal and drawer would close. This aims to solve that by making the keydown event scoped to the host element. For that to work though, the drawer must have focus, which is why I had to add a focus trap.

fix(ui-watt): esc no longer closes both modal and drawer"

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.html
libs/dh/message-archive/shell/src/lib/dh-message-archive-shell.module.ts

- move page title to top bar on "message-archive" page
- #816

feat(dh): move page title to top bar

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.html
libs/dh/wholesale/shell/src/lib/dh-wholesale-shell.module.ts

- move title for Start process page in top bar
- #816

feat(dh): move title for Start process page to top bar

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss

Very simple PR, just increases the z-index of the drawer component to ensure it stays above tables with sticky headers (while still below modals).
- #845

fix(ui-watt): increase drawer z-index

---

tools/generators/dh-library-generator/index.ts

When using the `dh-library-generator` to make routing libs, the import paths in `tsconfig.base.json` was incorrectly being generated with dashes (`-`) as separators instead of slashes (`/`).
Before it would generate something like this:
```json
"@energinet-datahub/dh-charges-routing"
```
Now it correctly generates:
```json
"@energinet-datahub/dh/charges/routing"
```

fix(dh): set import path explicitly

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/watt-drawer-actions.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer-topbar.component.scss
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.html
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss

- allow placing content on the same line* as action buttons in drawer component
\* only works for sizes `normal` and `large`. Size `small` will render the action buttons and content as stacked. 
- #874

feat(watt): support placing content on the same line as action buttons

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/tabs/tab/tab.component.ts
libs/ui-watt/src/lib/components/tabs/tabs.component.html
libs/ui-watt/src/lib/components/tabs/tabs.component.ts

This is needed for the charge drawer, which has tabs. 
We want to know whenever a tab has been selected, so we can load the data inside that tab. 
We would also like to know which tab is currently active when the drawer is open, to load the correct data.
- #0000

feat(ui-watt): Add output changes to tabs

---

libs/dh/shared/feature-flags/src/lib/feature-flags.ts

Organizations/GridAreas should now be visible in B002.

Show Organizations/GridAreas in B002.

---

apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
libs/dh/shared/domain/src/lib/generated/v1/model/batch-dto-v2.ts
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts

Disable download basis data icon when data is not available
- [#17](https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/energinet-datahub/opengeh-wholesale/17)

feat: Download icon is (only) visible (or enabled) when the batch is complete

---

tools/generators/watt-component/index.ts

The generated path in tsconfig.base.json pointed to a src folder that doesn't exist.

fix(ui-watt): wrong path in watt component generator

---

libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.html
libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.ts
libs/dh/message-archive/data-access-api/src/lib/dh-message-archive-data-access-api-blob.store.ts

When clicking on the download button in Charge Message, the drawer closes. It should stay open.
- #0000

fix: Drawer closes on downloading message

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/ChargesControllerTests.cs
apps/dh/api-dh/source/DataHub.WebApi/Controllers/ChargesController.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
libs/dh/shared/domain/src/lib/generated/v1/api/charges-http.service.ts

This PR bumps below packages to v. 6.0.0
* Energinet.DataHub.Charges.Clients
* Energinet.DataHub.Charges.Clients.Registration
This PR also removes the BFF's ChargeController method `GetAsync()`. Which is no longer used by frontend, nor supported by backend.
- https://github.com/Energinet-DataHub/geh-charges/issues/1799

Update: `Charges.Clients` and `Charges.Clients.Registration` to latest v `6.0.0`

---

libs/dh/core/shell/src/lib/dh-core-shell.module.ts

Only import `DhSharedUtilApplicationInsightsModule` in production to eliminate console noise and ensure application insights aren't hijacking any error messages in the `mock` or `development` environment. 
- #944

feat(dh): only import DhSharedUtilApplicationInsightsModule in production

---

libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts

The list of grid areas in start batch screen has been extended with the following 4 grid areas: 512, 533, 543, 584
- [632](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/632)

feat(wholesale): add new grid areas

---

libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts

The list of grid areas in start batch screen has been extended with the `351` grid area
- [632](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/632)

feat(wholesale): add grid area 351

---

libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts

Adjust wholesale mocks to get rid of following warning in the console:
`[MSW] Found a redundant usage of query parameters in the request handler URL for "GET https://localhost:5001/v1/WholesaleBatch/ZippedBasisDataStream?batchId=123". Please match against a path instead and access query parameters in the response resolver function using "req.url.searchParams".`

fix(wholesale): remove redundant usage of query params in mocks

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/table/watt-table.component.ts

Make sure `getCellData` won't fail if the column is undefined and breaks the sorting.

fix(watt): make sure getCellData won't fail if column is undefined (watt-table)

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/table/watt-table.component.ts

This PR makes it possible to supply the table header values directly in the template. Example:
```tsx
<ng-container *wattTableCell="columns.id; header: translate('columns.id'); let cell">
...
</ng-container>
```

Add optional header input to wattTableCellDirective

---

libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts

Reset the selected batch on search if no query param of the batch is set. 
Currently, if you select a batch ->, select grid area -> click on search batch in the menu - the table will highlight the selected batch. With this PR, it will be reset.

fix(wholesale): reset selected batch on search

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/metering-point/feature-search/src/lib/form/dh-metering-point-search-form.component.html
libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.html
libs/ui-watt/src/lib/components/button/watt-button.component.scss
libs/ui-watt/src/lib/components/button/watt-button.component.spec.ts
libs/ui-watt/src/lib/components/button/watt-button.component.ts

remove large version of the watt button and adjust text field on metering-point
- #1267
- #1266 (partially)

chore:(ui-watt): remove size option from button

---

.github/workflows/production-dependencies-license-check.yml

`license-checker-rseidelsohn` updated to 4.0.0 which doesn't support node 16. 
This PR sets it to the latest version of 3 that is supporting node 16
https://github.com/RSeidelsohn/license-checker-rseidelsohn/releases
- N/A

fix: set version on license-checker-rseidelsohn package

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
libs/eo/dashboard/shell/src/lib/eo-dashboard-get-data.component.ts

This removes the following links from navigation:
- Renewable share
- Consumption
- Emission
As well as removes the link to the emissions page from dashboard

Remove unneeded links

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-api/src/lib/states.ts

- display validation error message when user role name exists
- add new error state type
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/891

feat(dh): display validation error message when user role name exists

---

libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- make description field in edit user role required
- display required error on name field
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/891

feat(dh): make description field in edit user role required

---

libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- show notification on edit user role success/error
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/891

feat(dh): show notification on success/error

---

libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html

Fix default sorting of settlement reports

fix(wholesale): default sorting of settlement reports

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html

Add calculation step for non-profiled consumption per balance responsible
- [#786](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/786)

feat(wholesale): add calculation step for non-profiled consumption per balance responsible

---

libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.html
libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.ts
libs/dh/admin/ui-permissions-table/.eslintrc.json
libs/dh/admin/ui-permissions-table/README.md
libs/dh/admin/ui-permissions-table/jest.config.ts
libs/dh/admin/ui-permissions-table/project.json
libs/dh/admin/ui-permissions-table/src/index.ts
libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.html
libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.ts
libs/dh/admin/ui-permissions-table/src/test-setup.ts
libs/dh/admin/ui-permissions-table/tsconfig.json
libs/dh/admin/ui-permissions-table/tsconfig.lib.json
libs/dh/admin/ui-permissions-table/tsconfig.spec.json
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
tsconfig.base.json
workspace.json

- move permissions table component to its own library - `ui-permissions-table`. The idea is that the component is going to be used in "edit user role" soon.
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/893

refactor(dh): move permissions table component to its own library

---

.github/actions/yaml-increment-version/action.yaml
.github/workflows/eo-cd.yml
libs/ui-watt/src/lib/components/card/watt-card.stories.ts

This PR enables versions of helm chart and values files to me automagically bumped when changes to watt happens
See this PR to see it work https://github.com/Energinet-DataHub/greenforce-frontend/pull/1446

bump versions on watt changes

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
libs/eo/shared/services/src/app-settings/app-settings.store.ts

This makes time generation work for Safari, so it produces a time instead of NaN

This fixes date generation for Safari

---

libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json

- add spinner to permissions tab
- wrap permissions table in card
- show validation message in permissions tab
- https://github.com/Energinet-DataHub/ARCHIVED-geh-post-office/issues/893

feat(dh): adjustments to edit user role modal

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html

Add non-profiled consumption per grid area step
- [#820](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/820)

feat(wholesale): add non-profiled consumption per grid area step

---

libs/dh/shared/data-access-graphql/src/lib/dh-graphql.module.ts
libs/dh/shared/data-access-graphql/src/lib/error-handler.ts

Add global error handler for graphql logging to application insights.
Because requests made by graphQL, which returns errors, still return status 200, these are not automatically logged to application insights. 
- #0000

feat(shared): add global error handler for graphql logging to application insights

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.html
libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.html
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts

- refresh data when permission edit is successful
- https://github.com/Energinet-DataHub/Titans/issues/13

feat(dh): refresh data when permission edit is successful

---

libs/dh/admin/feature-permissions/src/lib/details/dh-admin-permission-detail.component.ts
libs/dh/admin/feature-permissions/src/lib/overview/dh-admin-permission-overview.component.ts
libs/dh/admin/feature-permissions/src/lib/shared/dh-get-permissions-watch-query.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.service.ts

- refresh data in drawer when permission edit is successful
- https://github.com/Energinet-DataHub/Titans/issues/13

feat(dh): refresh data in drawer when permission edit is successful

---

apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/nswag.json
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Adds Swagger.json file to see what version of API spec is being used and adds it as a condition in generating new client so you actively have to remove local swagger.json to generate a new client that creates a new swagger.json. This is to prevent local rebuild from breaking when a new version of openapi spec is push from wholesale domain
- #0000

fix: local build does not break when new openapi spec 

---

libs/dh/wholesale/feature-settlement-reports/src/lib/dh-wholesale-settlement-reports.component.ts

Make sure settlement reports aren't calling the API twice at init

fix(wholesale): make sure settlement reports aren't calling the API twice at init

---

libs/dh/shared/data-access-graphql/src/lib/dh-graphql.module.ts

Add query param for graphQL request with the operation name. 
Before, all requests were `/graphql` in the network tab. Now, the operation name is added `/graphql?some-awesome-operation` to make it easier to identify the requests.

feat(dh): add query param for graphQL request with the operation name

---

libs/dh/shared/data-access-graphql/src/lib/error-handler.ts

Improve graphql error handler
- Use error details instead of just the message to make it easier to debug the error based of logged exceptions in application insights. If no details are available, the message will be used as a fallback. 
**Before:** `Error trying to resolve field 'batches'.`
**After:** `GraphQL.Execution.UnhandledError: Error trying to resolve field 'batches'.\r\n ---> System.InvalidOperationException: No service for type 'Energinet.DataHub.WebApi.AuthorizedHttpClientFactory' has been registered.\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider …

Improve graphql error handler

---

.vscode/settings.json

I was seeing an error in VS Code due to too many files being watched. This change appears to fix the issue for me.

fix: add yarn and angular cache to watcherExclude

---

apps/dh/e2e-dh/src/e2e/b2c-healthchecks.cy.ts

Trying to fix flaky b2c health checks
- Increasing the timeout for the redirect to `10000ms`
- Setting the retries to `3`

fix(dh): trying to fix flaky b2c healthchecks

---

.github/workflows/dh-ci-dotnet.yml

- set .NET version in pipelines
Note: The default version is 6.0.408 as seen in [this run](https://github.com/Energinet-DataHub/greenforce-frontend/actions/runs/4828488928/jobs/8603196565).
- N/A

feat(ci): set dotnet version in pipelines

---

.github/workflows/ci-orchestrator.yml
.github/workflows/dh-cd.yml
.github/workflows/dh-ci-dotnet.yml
.github/workflows/dh-healthchecks.yml
.github/workflows/watt-cd.yml

- remove .NET version from workflow. Note: 7.0.203 is now a default version in `dotnet-build-prerelease` workflow
- bump `.github` workflows to v11
- N/A

chore: bump `.github` workflows to v11

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/eo/core/shell/src/lib/eo-core-shell.providers.ts
libs/eo/core/shell/src/lib/eo-shell.component.ts
libs/eo/transfers/src/lib/eo-transfers-modal.component.ts
libs/eo/transfers/src/lib/eo-transfers-table.component.ts
tsconfig.base.json

Fix a bug where after migrating to completely standalone components, the dates in a daterange picker were wrongly showed on 1st, 2nd and 3rd days in the month.
Also fixed the text for the cancel button on the "create transfer" modal
Also fixed that the modal will reset its data no matter how it is closed

Fix Date range picker showing in danish time correctly

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
docs/dh/testing.md
libs/dh/charges/feature-create-prices/src/lib/dh-charges-create-prices.component.spec.ts
libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.spec.ts
libs/dh/charges/feature-prices/src/lib/drawer/charge-content/dh-charge-content.component.spec.ts
libs/dh/core/shell/src/lib/dh-core-shell.component.spec.ts
libs/dh/core/shell/src/lib/dh-core-shell.component.ts
libs/dh/core/shell/src/lib/dh-core-shell.providers.ts
libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.spec.ts
libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.cy.ts
libs/eo/core/shell/src/lib/eo-core-shell.providers.ts
libs/ui-watt/src/lib/components/input/timepicker/watt-timepicker.module.spec.ts
libs/ui-watt/src/lib/configuration/watt-danish-datetime.providers.ts
libs/ui-watt/src/lib/configuration/watt-date-adapter.ts
libs/ui-watt/src/lib/configuration/watt-locale.service.ts

- remove `MatDateFnsModule` from providers. The reason is that our own `danishDatetimeProviders` provide the same providers that are coming from `MatDateFnsModule`. If we want to keep both `MatDateFnsModule` and `danishDatetimeProviders` then **the order is important** and `danishDatetimeProviders` **must** come last. Otherwise `MatDateFnsModule` will overwrite our providers.
- remove `MatDateFnsModule` from spec files
- update documentation
- Closes #1827

fix(dh): remove date-fns module from providers

---

package.json

Renamed task from create to branch, to avoid name conflict with yarn. It also better reflects what it does.

Renamed task

---

apps/eo/app-eo/src/main.ts
build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml

- configure ZoneJS. The configuration was disabled while migrating from NgModule to Standalone. In Angular v15 it was not possible to configure ZoneJS (with Standalone). This option was first added in v16.
- N/A

feat(eo): configure ZoneJS

---

.github/workflows/frontend-ci.yml
libs/dh/shared/assets/src/assets/b2c-custom-layouts/changepassword-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/forgotpassword-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/login-with-mitid-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/main.js
libs/dh/shared/assets/src/assets/b2c-custom-layouts/multifactorauth-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/reset-password.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/self-asserted.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/signup-unified.html
libs/dh/shared/assets/src/assets/b2c-custom-layouts/totp-unified.html
libs/dh/shared/feature-flags/src/lib/feature-flags.ts

Wait scripts and elements are loaded before trying to show html

Made loading more resilient

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/ui-watt/src/lib/components/drawer/watt-drawer.component.ts
libs/ui-watt/src/lib/components/shell/shell.component.scss
libs/ui-watt/src/lib/foundations/_variables.scss
libs/ui-watt/src/lib/utils/css-custom-properties.service.ts

- because of a `z-index` value, the topbar component was overlaying the drawer on pages with tabs. Pages without tabs worked fine. This PR couples the drawer with the topbar (in a way) by reading and updating a CSS variable but fixes the overlay issue.
- N/A

fix(watt): drawer should overlay topbar when open

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/dh/market-participant/feature-organization/src/lib/overview/dh-market-participant-organization-overview-grid-areas-list.component.ts
libs/ui-watt/src/lib/styles/@energinet-datahub/watt/theme/light-theme.scss

Removed legacy tooltip, readded styles for menu
Keept the default style, because organization is going to be removed.
- https://github.com/Energinet-DataHub/greenforce-frontend/issues/1930

Fixed default menu style, removed legacy tooltip

---

build/infrastructure/eo/chart/Chart.yaml
build/infrastructure/eo/chart/values.yaml
libs/watt/.eslintrc.json
libs/watt/src/lib/components/vater/vater-flex.component.ts
libs/watt/src/lib/components/vater/vater-spacer.component.ts
libs/watt/src/lib/components/vater/vater-stack.component.ts
libs/watt/src/lib/components/vater/vater-utility.directive.ts
libs/watt/src/lib/components/vater/vater.mdx
libs/watt/src/lib/components/vater/vater.stories.ts
libs/watt/src/lib/foundations/_vater.scss
libs/watt/src/lib/styles/@energinet-datahub/watt/_index.scss

As a response to some of the feedback on vater, this PR aims to make it a little bit smarter by adding support for common utility (+ the spacer component).

feat(watt): VaterSpacer and VaterUtility

---

build/infrastructure/eo/configuration.yaml
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.html
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.ts
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.ts
libs/watt/src/lib/components/tabs/watt-tabs.component.scss

- use new Vater components in Balance responsible tab
- add height to tabs so new Vater components can work inside tabs

feat(dh): use new Vater components in Balance responsible tab

---

libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.html
libs/dh/esett/feature-balance-responsible/src/lib/dh-balance-responsible.component.ts
libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html

- add download to balance responsible 
- move drawer after table because it was affecting spacing

feat(dh): add download to balance responsible in eSett

---

build/infrastructure/eo/configuration.yaml
libs/watt/src/lib/components/picker/shared/picker.scss

- use monospace font in date- and timepicker components.
Before
After
- https://github.com/Energinet-DataHub/team-titans/issues/299

fix(watt): use monospace font in date- and timepicker components

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-api/src/lib/dh-market-party-credentials.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-certificate-view.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/certificate/dh-replace-certificate-modal.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-client-secret-view.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/client-secret/dh-generate-client-secret.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/b2b-access-tab/dh-b2b-access-tab.component.ts

- implement replace certificate with client secret
- reset client secret when loading data in tab
- https://github.com/Energinet-DataHub/team-titans/issues/326

feat(dh): implement replace certificate with client secret

---

libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts

Currently, the filter$ is also returning empty execution times, which makes GraphQL fail. 
- Add a filter to avoid nullable execution times causing the application to fail. 
- Adjust mocks to return an error like the actual API if nullable execution times are sent to the API. 
[#74](https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/74)

fix(dh, wholesale): Fix API error handling in getCalculations()

---

libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/filters/dh-actors-filters.component.ts

- reset search when filters get reset
- add fallback value to table data 
- use operator to clear subscription
- https://github.com/Energinet-DataHub/team-titans/issues/367

fix(dh): reset search when filters get reset

---

build/infrastructure/eo/configuration.yaml
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/dh-metering-gridarea-imbalance.component.html
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.html
libs/dh/esett/feature-metering-gridarea-imbalance/src/lib/filters/dh-filters.component.ts
libs/dh/esett/feature-outgoing-messages/src/lib/dh-outgoing-messages.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/filters/dh-filters.component.html
libs/dh/esett/feature-outgoing-messages/src/lib/filters/dh-filters.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/dh-actors-overview.component.ts
libs/watt/src/lib/components/search/watt-search.component.ts

- reset search input when filters get reset
- remove unused import
- do not clear input if it's already empty
- N/A

feat(dh): reset search input when filters get reset

---

libs/eo/certificates/feature-details/eo-certificate-details.component.ts
libs/eo/certificates/shell/certificates.routes.ts

Since the upgrade of Angular v17, the title hasn't been updated as it should on the certificate details page. 
To fix the issue, a resolver for the title has been created. 
- #0000

fix(eo): add resolver for certificate details title

---

libs/eo/metering-points/shell/src/lib/eo-metering-point-table.component.ts

Remove "source" from consumption metering points
- #0000

Remove "source" from consumption metering points

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/market-participant/actors/data-access-graphql/update-organization.graphql
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.html
libs/dh/market-participant/actors/feature-organizations/src/lib/edit/dh-edit-modal.component.ts
libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-error-handling.ts
libs/dh/shared/data-access-mocks/src/lib/marketParticipant.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts

- show descriptive error when domain is taken when editing an organization 
- add update actor mock 
- update phone number in mock
- set `loading` on modal
- N/A

fix(dh): show descriptive error when domain is taken

---

libs/dh/market-participant/actors/feature-organizations/src/lib/drawer/dh-organization-drawer.component.html
libs/dh/shared/data-access-mocks/src/lib/data/admin-get-permissions.ts
libs/dh/shared/data-access-mocks/src/lib/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
libs/dh/shared/data-access-mocks/src/lib/data/marketParticipantUserRolePermissions.json
libs/dh/shared/domain/src/lib/permission.ts

- replace "organizations:manage" with "actors:manage"
- N/A

fix(dh): remove "organizations:manage" permission

---

.github/workflows/dh-cd.yml

Code coverage results for .NET are not used, and it often causes the CD to fail. This PR remove the step from CD.

build: Delete code coverage step from CD

---

libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.html
libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.ts
libs/dh/shared/data-access-mocks/src/lib/admin.ts
libs/dh/shared/data-access-mocks/src/lib/data/marketParticipantOrganizationGetFilteredActors.ts
libs/watt/src/lib/components/stepper/watt-stepper-step.component.ts
libs/watt/src/lib/components/stepper/watt-stepper.component.html

- set button in loading state while a request is active
- update mock
- extend step component to allow setting next button in loading state
- N/A

fix(dh): set button in loading state while a request is active

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Extensions/WholesaleClientExtensions.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/CalculationQuery.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/CalculationQueryInput.cs
libs/dh/shared/data-access-mocks/src/lib/wholesale.ts
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/wholesale/data-access-graphql/get-calculations.graphql
libs/dh/wholesale/data-access-graphql/get-latest-balance-fixing.graphql
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts
libs/dh/wholesale/feature-calculations/src/lib/filters/filters.component.ts
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts
schema.graphql

This PR refactors the calculations GraphQL query to use an input type instead of several arguments. I needed this in my work with subscriptions, but decided to split the work into a separate PR because I'm a good boy.

refac(dh): calculations input type

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Extensions/TopicEventReceiverExtensions.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/CalculationQuery.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Subscription/CalculationSubscription.cs
libs/dh/shared/domain/src/lib/generated/graphql.ts
libs/dh/wholesale/data-access-graphql/on-calculation-progress.graphql
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.html
libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts
schema.graphql

This PR implements a calculation progress subscription on the calculations page. After this change, new calculations will be inserted in the table in realtime, while status updates will be pushed periodically (currently every 10 sec).
- [#18](https://github.com/Energinet-DataHub/team-mandalorian/issues/18)

feat: calculation progress subscription

---

.licenserc.json
libs/dh/shared/assets/src/favicon/browserconfig.xml

fix: ignore license headers for files in favicon folder

---

libs/dh/core/shell/src/lib/dh-core-shell.component.ts
libs/dh/core/shell/src/lib/dh-core-shell.providers.ts
libs/dh/profile/feature-profile-modal/src/lib/dh-profile-modal/dh-profile-modal.component.ts

- move `ApolloModule` to core providers so `Apollo` injectable is provided globally. Before this change, `ApolloModule` had to be imported in *some* `..Modal` components due to `No provider for _Apollo!` error.
- #0000

refactor(dh): move ApolloModule to shell providers

---

libs/dh/shared/assets/src/assets/configuration/dh-app-environment.local.json
libs/dh/shared/environments/src/lib/app-environment/dh-app-environment.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.service.spec.ts
libs/dh/shared/feature-flags/src/lib/feature-flags.ts
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts

[Tak GitHub actions fordi du automatisk formaterer min (STRING) dato til et andet format, jeg skulle heller ikke bruge tidszonen til noget...](https://github.com/Energinet-DataHub/dh3-environments/pull/982) (hackede virkede ikke)

fix: quarterly-resolution-transition-datetime-override

---

libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts
libs/watt/src/lib/components/picker/datepicker/watt-datepicker.component.html
libs/watt/src/lib/components/picker/datepicker/watt-datepicker.component.ts

This PR includes the min and max date configuration in the Maskito options. This means we can skip validating min and max in form controls, since maskito will prevent entering dates outside of this range.

feat: use min and max in datepicker mask

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-filter.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.html
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation-tab.component.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation.store.ts
libs/dh/market-participant/actors/feature-actors/src/lib/drawer/balance-responsible-relation-tab/dh-balance-responsible-relation.ts

- rework logic so filters are reset whenever a new market participant is loaded in the drawer.
Note: I'm not particularly happy with resetting the filters inside an `effect` but couldn't come up with a better solution, for now. Open for other suggestion. :)
- #0000

refactor(dh): adjustments to balance responsible relations

---

libs/dh/shared/util-apollo/src/lib/mutation.spec.ts
libs/dh/shared/util-apollo/src/lib/mutation.ts
libs/dh/shared/util-apollo/src/lib/query.spec.ts
libs/dh/shared/util-apollo/src/lib/query.ts

This PR makes it possible to reset queries and mutations to an initial, pending state, essentially clearing the result fields. This can come in handy if, for example, you are using `lazyQuery` to do some validations in combination with `computed`:
```ts
validation = lazyQuery(GetUserByEmailDocument);
userExists = computed(() => this.validation.data()?.user ? true : false);
resetForm() {
// This will cause `userExists` to be `false` again
this.validation.reset();
}
async validate(email: string) {
await validation.query({ variables: { email }});
}
```

feat(dh): apollo signal reset function

---

libs/eo/consent/feature-grant-consent/grant-consent.component.ts
libs/eo/consent/feature-overview/consent-overview.component.ts
libs/eo/shared/data-access-mocks/src/index.ts
libs/eo/shared/data-access-mocks/src/lib/authorization.ts
libs/eo/shared/services/src/auth/auth.interceptor.ts

- Add mocks for `/authorization/consent` requests
- Ensure grant consent modal is not opened after consent is granted
- Make sure token refresh by the "old" auth is not triggered on the consent related API requests
- #0000

fix(eo, consent): Add mocks and fixes issues with onboarding flow

---

libs/eo/shared/services/src/auth/auth.interceptor.spec.ts

- Add tests for Authorization header, so we don't misses these again
- #0000

test(eo, auth.interceptor): add test for Authorization header

---

libs/eo/api-documentation/shell/api-documentation.component.ts

This commit updates the `api-documentation.component.ts` file to handle the dev portal link in a better way. It replaces the `target="_blank"` attribute with a click event listener that prevents the default behavior and instead opens the dev portal link in the current window. This change improves the user experience and ensures that the link is handled consistently across different browsers.
Note: This commit is based on recent user commits and repository commits.
- #0000

feat(api-docs): update dev portal link handling

---

libs/dh/shared/util-apollo/src/lib/query.spec.ts
libs/dh/shared/util-apollo/src/lib/query.ts

- do not complete stream on error by moving `catchError` operator inside `valueChanges`
- add `fetchPolicy` on `refetch` method
- add test to verify behaviour. The test show that a query can be recovered from error state when calling `refetch`. The test DO NOT show that `loading` Signal is set to `true` after `refetch` is called because I couldn't figure out how to set the `query` in that state. However, this is what happens in the browser.
- #0000

fix(dh): improvements to `query` function

---

libs/watt/src/lib/components/modal/watt-modal.component.scss

- add `margin` to title
- align close button
- set height of title and close button row to `auto`
These adjustments are needed to handle long `title` values.
Before
After
- #0000

fix(watt): adjustments to modal component

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/Orchestrations/Dto/CancelScheduledCalculationRequestDto.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/Orchestrations/IWholesaleOrchestrationsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/Orchestrations/WholesaleOrchestrationsClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/WholesaleClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/Wholesale/V3/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Enums/ProgressStatus.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Mutation/CalculationMutation.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Subscription/CalculationSubscription.cs
apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/Calculation/CalculationType.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculations/src/lib/details/details.component.ts
libs/watt/src/lib/components/progress-tracker/watt-progress-tracker-step.component.scss
libs/watt/src/lib/components/progress-tracker/watt-progress-tracker-step.component.ts
libs/watt/src/lib/foundations/icon/icons.ts

- Add cancel sceduled calculation Wholesale API
- Call new Wholesale API in calculation mutation
- This updates mutation input name from `guid` to `calculationId`
- Update Wholesale API client with new orchestration states
- The frontend might need to be updated to use these states:
- `Started` should be shown as calculating
- `Canceled` should be shown as canceled
Requires merged Wholesale PR's:
- https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/210

feat: Add cancel sceduled calculation Wholesale API

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.spec.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

Feature flags tests didn't fail because the difference between `parsedDate` and `new Date()` gave a negative number, which always satisfied the assertion. This PR fixes that.
- #0000

fix(dh): make feature flags fail again

---

libs/dh/wholesale/feature-calculations/src/lib/table/table.component.ts

This will become a problem eventually, since we need to retain at least 3.5 years worth of calculations in the view (equivalent to at least a couple thousand entries). But since we do not import calculation history from DH2, we have some time to figure out the correct solution (e.g. pagination). On launch, we reset calculations to 0.

fix(dh): remove hidden executionTime filter

---

.github/workflows/detect-changes.yml
.github/workflows/dh-ci-frontend.yml
.github/workflows/dh-healthchecks.yml
.github/workflows/eo-cd.yml
.github/workflows/frontend-ci.yml
.github/workflows/license-check-ci.yml
.github/workflows/production-dependencies-license-check.yml
.github/workflows/watt-cd.yml
.github/workflows/watt-ci.yml
package.json

- upgrade Bun to v1.1.26
**Note**: Doesn't look like Volta automatically upgrades to this new version, so after merge you should run `bun upgrade`.
- #0000

chore: upgarde Bun to latest

---

libs/watt/src/lib/components/picker/datepicker/watt-date-range-chip.component.ts

- fix date range chip component so it emits a value when end date stayed the same during a new selection
Fixes https://app.zenhub.com/workspaces/raccoons-sprint-board-60d029726fc7570010362aa7/issues/gh/energinet-datahub/internal-repo/1330
- #0000

fix(watt): emit values on same end date selection

---

libs/watt/src/lib/components/shell/nav-list/watt-nav-list.component.scss
libs/watt/src/lib/components/shell/shell.component.scss
libs/watt/src/lib/foundations/_variables.scss

- update color for sidenav and nav list item `active`/`hover` state
After / Before in DH and ET&T apps 👇
- #0000

feat(watt): adjust color in sidenav

---

libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts
libs/dh/wholesale/feature-calculations/src/lib/create/create.component.ts

Per agreement, it should no longer be possible to create new calculations with a period starting more than 38 months ago.

chore(dh): remove create-calculation-minimum-date feature flag

---

libs/watt/src/lib/components/chip/watt-filter-chip.component.ts

This PR fixes a bug with filter chip, causing errors with create calculation. I'm reverting the change for now, although that means breaking a small thing in message-archive-v2. But since that is still behind a feature flag (and it is a minor thing), I think that's okay.

Revert change to watt-filter-chip

---

libs/eo/auth/feature-terms/terms.component.ts
libs/eo/shared/components/ui-footer/footer.component.ts
libs/eo/shared/components/ui-header/eo-header.component.ts

This pull request focuses on improving the print layout for various components in the `eo` library by adding media queries to handle print-specific styles. The most important changes include hiding certain components when printing and adjusting the layout for better print compatibility.
Print layout improvements:
* [`libs/eo/auth/feature-terms/terms.component.ts`](diffhunk://#diff-2a6fe44dd8575c03e149dea6ec78cfe5a0316662b24672ac4363fe348a97ff2cR71-R75): Added print-specific styles to adjust padding and max-height for the `eo-auth-terms` component.
* [`libs/eo/shared/components/ui-footer/footer.component.ts`](diffhunk://#diff-aedbd5ba03f536f1fc6b66ea9ee80f8d2d0974ae43fc3f94c32e04363ea0dd53R38-R41): Added a media query to hide the `eo-footer` component when printing.
* …

feat(print): add print styles to hide header and footer, adjust terms component

---

libs/eo/auth/data-access/auth.interceptor.ts
libs/eo/auth/data-access/auth.service.ts
libs/eo/auth/feature-terms/terms.component.ts

This pull request includes several changes to the authentication and terms acceptance flow in the `eo/auth` library. The most important changes include updating the handling of token refresh URLs, improving the `acceptTos` method to handle asynchronous operations, and adding a toast notification for error handling in the terms component.
* [`libs/eo/auth/data-access/auth.interceptor.ts`](diffhunk://#diff-bfc346fbd147000fc136749dce76c253fb4a74bee99bfe340c03eb433f9c42a3L42-R42): Added a new URL to the `ignoreTokenRefreshUrls` array to include `/api/authorization/terms/accept`.
* [`libs/eo/auth/data-access/auth.service.ts`](diffhunk://#diff-7e7ef35de5c69cb1d2cfefb81a03b975caf099ecfd741e71ccc6fa9525e80a51L116-R154): Updated `acceptTos` method to use `lastValueFrom` for asynchronous handling …

ETT: enhance TOS acceptance flow and add error handling

---

libs/eo/auth/data-access/auth.service.ts

This pull request introduces enhancements to the `EoAuthService` class in the `libs/eo/auth/data-access/auth.service.ts` file, specifically focusing on the `refreshToken` method to include additional query parameters and improving the token refresh process.
Enhancements to `refreshToken` method:
* Modified the `refreshToken` method to accept `extraQueryParams` as an optional parameter and pass it to `signinSilent`. (`libs/eo/auth/data-access/auth.service.ts`)
* Updated the call to `refreshToken` to include specific query parameters (`prompt`, `max_age`, and `t`) for better control over the authentication flow. (`libs/eo/auth/data-access/auth.service.ts`)
- #0000

ETT: enhance refreshToken method with additional query parameters for login prompt

---

libs/watt/src/lib/components/dropdown/watt-dropdown.component.scss

This pull request includes updates to the `watt-dropdown` component's styles to improve visual consistency and layout. The changes primarily focus on padding adjustments and border styling for dropdown options.
Styling adjustments for `watt-dropdown` component:
* Added padding of `0` to `.watt-dropdown-panel` and set specific height for `.mat-select-search-inner-row .mat-select-search-input` and `mat-option.contains-mat-select-search` to `48px`. (`libs/watt/src/lib/components/dropdown/watt-dropdown.component.scss`)
* Added a top border to the second `mat-option` within `.watt-dropdown-panel`. (`libs/watt/src/lib/components/dropdown/watt-dropdown.component.scss`)
* Removed padding and margin adjustments for `.mat-select-search-input` within `ngx-mat-select-search` and adjusted the margin …

fix(watt, dropdown): adjust spacing and alignment

---

.github/workflows/ci-orchestrator.yml
.github/workflows/dh-cd.yml

This pull request includes changes to the GitHub workflow configuration files to refine the conditions under which certain jobs are executed. Specifically, it removes the dependency on `dh_frontend` outputs for the `dh_ci_dotnet` and `dotnet_promote_prerelease` jobs.
Changes in GitHub workflow configurations:
* [`.github/workflows/ci-orchestrator.yml`](diffhunk://#diff-c2a8e2dd83b46864483c9706f8e843ef2eef7e0a17b4ae45194a5a671e3c8739L55-R55): Modified the `if` condition for the `dh_ci_dotnet` job to only check for `dh_dotnet` outputs.
* [`.github/workflows/dh-cd.yml`](diffhunk://#diff-2097bc6b995e5600ae4b86db05e241f7045182bfe072452e55c43f64b381eeceL37-R37): Modified the `if` condition for the `dotnet_promote_prerelease` job to only check for `dh_dotnet` outputs.
- #0000

Only release dotnet if changes

---

libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html

This pull request includes a minor change to the `dh-actor-drawer.component.html` file. The change adds a permission requirement to the "Edit Organization" button to ensure only users with the appropriate permissions can access this functionality.
* [`libs/dh/market-participant/actors/feature-actors/src/lib/drawer/dh-actor-drawer.component.html`](diffhunk://#diff-8952241426bad1008df2ef915f202a4e60136c6f1e898d64848f12a16470b54dR117): Added `*dhPermissionRequired="['actors:manage']"` to the "Edit Organization" button.

Added permission on button

---

libs/dh/message-archive/feature-search/src/lib/table.component.ts
libs/dh/shared/util-apollo/src/lib/dataSource.ts

Do not reset entire dataSource on refetch, but instead set the data to an empty array. This is enough to trigger the loading state and prevents the issue where the filter variable was no longer present in the options variables since options had been reset.

fix(dh): issue with message archive searchById

---

libs/eo/landing-page/shell/src/lib/login-button.component.ts

There is some hydration issue in Angular which causes the @if and @else to be rendered at the same time for the login button at the landing-page. The fix should be available in v19. Until then I've removed the condition so we always shows the text as "unauthorized" 
- #0000

fix(eo, landing-page): remove condition if user is logged in

---

libs/eo/dashboard/shell/src/lib/eo-dashboard-shell.component.ts

remove unused NgIf import and update variable declarations to readonly
- #0000

EO: dummy change to trigger CD

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
apps/dh/api-dh/source/DataHub.WebApi.Tests/Unit/Clients/Wholesale/ProcessManager/OrchestrationInstanceMapperExtensionsTests.cs
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj

Use latest NuGet packages and fix constructor parameters for `OrchestrationInstanceTypedDto`.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/423

chore: Bump NuGet packages

---

libs/eo/shared/data-access-mocks/src/lib/transfer.ts
libs/eo/transfers/src/lib/eo-transfers.service.ts

This pull request includes significant changes to the `libs/eo/shared/data-access-mocks` and `libs/eo/transfers` modules to improve the handling of transfer agreements and enhance the `EoTransfersService` class. The most important changes include the addition of new utility functions, refactoring of transfer agreement data structures, and improvements to the `EoTransfersService` class.
Improvements to `libs/eo/shared/data-access-mocks`:
* [`libs/eo/shared/data-access-mocks/src/lib/transfer.ts`](diffhunk://#diff-47fc638e22e36cc864088dfefc29a74488f4157cf1f68b4ba65ab249b897a303R21): Added utility functions from `date-fns` and refactored transfer agreement data structures to use a new `TransferAgreement` interface and predefined user constants. …

refactor(eo, transfer): transfer agreement mocks

---

workspace-tools/src/executors/generate-translation-keys/executor.ts

- Add license executor to run after generating translation keys
- #0000

EO: Add license executor to run after generating translation keys

---

libs/eo/onboarding/shell/signin-callback.component.ts

This pull request includes a small but important change to the `EoSigninCallbackComponent` class in the `libs/eo/onboarding/shell/signin-callback.component.ts` file. The change modifies the logic used to determine if an error description indicates a MitID Erhverv error.
* [`libs/eo/onboarding/shell/signin-callback.component.ts`](diffhunk://#diff-00e15509bc7bcaf80f056d54a2a8d93efc5eedc6dc717f69644f3437d808b554L68-R68): Updated the `isMitIDErhverv` computed property to use `startsWith` instead of a strict comparison for detecting the 'AADB2C90273' error code.
- [#3599](https://github.com/Energinet-DataHub/energy-origin-issues/issues/3599)

fix(eo, signin-callback): update isMitIDErhverv logic

---

libs/dh/core/routing/src/dhPaths.ts
libs/dh/core/shell/src/lib/dh-core-shell.routes.ts
libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/metering-point/feature-search/src/index.ts
libs/dh/metering-point/feature-search/src/lib/dh-metering-point.routes.ts
libs/dh/metering-point/feature-search/src/lib/dh-search.component.ts
libs/dh/shared/feature-flags/src/lib/dh-feature-flags.ts

- empty metering point search page
- routing setup
- add metering point feature flag
- bump feature flag date
- #0000

feat(dh): create empty metering point search page

---

libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
libs/dh/metering-point/feature-search/src/lib/dh-metering-point.routes.ts

fix(dh): enable metering point page only for users with right permission

---

.github/workflows/dh-ci-dotnet.yml
.github/workflows/dh-ci-frontend.yml
.github/workflows/frontend-ci.yml
apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
apps/dh/api-dh/source/DataHub.WebApi/Registration/GraphQLRegistrationExtensions.cs
global.json

The update apparently required a later version of the dotnet sdk than was specified in the `global.json` file. So I updated it to the latest version (same as I was running on my own machine). But this wasn't enough, as I also had to the setup-dotnet actions to our frontend ci (since they rely on dotnet during the generate phase). It should have probably been there from the start, but since the runner comes with dotnet preinstalled (at version 8.0.1xx something), it didn't fail (until now).

chore: update HotChocolate to v15

---

libs/watt/package/package.json
libs/watt/package/year-field/watt-year-field.component.ts
libs/watt/package/yearmonth-field/watt-yearmonth-field.component.ts

This is what happens when all developers use Firefox 😄

fix(watt): make YearField and YearMonthField close popover correctly in chromium browsers

---

libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-month.component.ts
libs/dh/metering-point/feature-overview/src/components/measurement/dh-measurements-year.component.ts
libs/watt/package/package.json
libs/watt/package/year-field/watt-year-field.component.ts
libs/watt/package/year-field/watt-year-field.stories.ts
libs/watt/package/yearmonth-field/watt-yearmonth-field.component.ts
libs/watt/package/yearmonth-field/watt-yearmonth-field.stories.ts

- add step through buttons to year picker
- add step through buttons to year-month picker
- enable step through buttons on year and year-month pickers in Measurements
- #0000

feat: add step through buttons to year and month pickers

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/wholesale/feature-calculations/src/lib/create/create-form.ts
libs/dh/wholesale/shared/src/gridareas-dropdown.ts
libs/dh/wholesale/shared/src/period-field.ts
libs/watt/package/core/styles/@energinet-datahub/watt/_index.scss
libs/watt/package/core/styles/_animations.scss
libs/watt/package/package.json

Some of the asynchronous fields in create calculation can be slow at times. This change adds a hint with some animating dots to the period and grid areas fields to indicate that stuff is happening in the background.

feat(dh): loading indicators for create calculation

---

apps/dh/api-dh/source/DataHub.WebApi.Tests/Snapshots/SchemaTests.ChangeTest.verified.graphql
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V3/EdiB2CWebAppClient.cs
apps/dh/api-dh/source/DataHub.WebApi/Clients/EDI/B2CWebApi/V3/swagger.json
apps/dh/api-dh/source/DataHub.WebApi/Modules/MessageArchive/Enums/DocumentType.cs
apps/dh/api-dh/source/DataHub.WebApi/Modules/MessageArchive/Extensions/SearchDocumentTypeExtensions.cs
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/message-archive/domain/src/lib/documentType.ts
libs/dh/message-archive/feature-search/src/lib/form.service.ts

It should be possible to search for missing measurement in the archived messages tab.
This should not be possible on production
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/749
- #0000

feat: Add missing measurement to archived messages

---

libs/watt/package/field/watt-field.component.ts
libs/watt/package/package.json
libs/watt/package/text-field/watt-text-field.component.ts

Quick fix - Perhaps we should, as @dzhavat mentioned, stop using both ng-template and viewchild at the same time.
But this gets ETT Going again 🙂

Fixes issue with autocomplete text fields

---

apps/dh/app-dh/src/styles.scss

I just realized that Angular does not replace `<router-outlet />` in the DOM, but instead places the matched component underneath it, as a sibling. It is empty and normally has a "zero-size", but if it happens to be part of fx. a VaterFlex component, it actually flexes along with other components, causing weird layout issues. This change just hides all `router-outlet` components as I see no reason why it should be visible.

fix(dh): remove router-outlet from layout

---

libs/watt/package/package.json
libs/watt/package/tooltip/watt-tooltip.component.scss

This PR fixes an issue where a hidden tooltip could overflow the parent, causing a scrollbar. By positioning it on the left side, this is much less likely to occur. Once the tooltip is shown, it will automatically position itself properly, so it should have no effect otherwise.

fix(watt): move watt-tooltip to left side

---

libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/grid-areas/src/components/grid-areas.component.html
libs/dh/message-archive/feature-search/src/lib/table.component.ts
libs/dh/wholesale/feature-requests/src/lib/table.ts
libs/watt/package/data/watt-data-table.component.ts
libs/watt/package/package.json
libs/watt/package/search/watt-search.component.ts

This pull request introduces several updates across multiple components, focusing on enhancing search functionality, and adding user feedback during data fetching. Below is a summary of the most significant changes, grouped by theme:
- Updated the `WattSearchComponent` to include a `trim` input property, allowing search values to be trimmed of whitespace before being emitted **(This is now default behaviour).** 
- Updated `watt-data-table` to trim search fields as default
- Enhanced the `DhMessageArchiveSearchTableComponent` to display a loading toast message during data refetching. 
- Updated the display format for date ranges in the `wholesale/feature-requests`, ensuring dates are not splitten.
- [#760](https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet …

Minor UI adjustments

---

libs/dh/core/feature-notifications/src/lib/dh-get-route-by-type.ts
libs/dh/globalization/assets-localization/src/assets/i18n/da.json
libs/dh/globalization/assets-localization/src/assets/i18n/en.json
libs/dh/shared/data-access-mocks/src/lib/notifications.mocks.ts

- Update grid loss notification to use metering point id.
- Deep link to metering point when clicking the notification.
- #0000

fix: Use metering point for grid loss notification

---

apps/dh/api-dh/source/DataHub.WebApi/Modules/Processes/Calculations/Client/CalculationsClient.cs

- Filter out scheduled calculations when querying for pending state
- [#561](https://github.com/Energinet-DataHub/team-mosaic/issues/561)

fix(calculations): filter out scheduled calculations when querying for pending state

---

.github/workflows/dh-ci-frontend.yml

This pull request makes minor improvements to the frontend CI workflow configuration. The most notable change is the addition of a step to generate a Software Bill of Materials (SBOM) for `node_modules`, which enhances supply chain security and transparency.
**Security and dependency management:**
* Added a step to generate an SBOM using `anchore/sbom-action` based on `yarn.lock`, outputting the results in SPDX JSON format for the release artifact.
**Dependency installation:**
* Updated the dependency installation command to use the `--yarn` flag with `bun install`, ensuring compatibility with Yarn lockfiles.

Enable node SBOM generation

---

libs/dh/shared/ui-util/src/lib/generate-csv-file.ts

Every time a report is downloaded, a set of headers is added. This is a fix for that.

Fixed header

---

libs/dh/profile/feature-avatar/src/lib/dh-profile-avatar.component.ts
libs/watt/package/menu/+storybook/menu-async-story.component.ts
libs/watt/package/menu/+storybook/watt-menu.stories.ts
libs/watt/package/menu/index.ts
libs/watt/package/menu/watt-menu-item.component.ts
libs/watt/package/menu/watt-menu.component.ts
libs/watt/package/package.json
tsconfig.base.json

- Add support for async menu items in `watt-menu`
- Optimize imports of `watt-menu`
- Replace `mat-menu` -> `watt-menu` in `dh-profile-avatar.component.ts`
- #0000

feat(watt, menu): add async menu items support, and fix imports
